force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>EP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/List_Price_Standard_price__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Standard_price__c</fullName>
    <label>List Price /Standard price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <label>Usage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELC</fullName>
            </value>
            <value>
                <fullName>DEO</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Engine Parts</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/Purchase_Indent__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Purchase Indent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Indents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent__c/fields/Against__c.field-meta.xml
<CustomField>
    <fullName>Against__c</fullName>
    <label>Against</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Procurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Import</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Sales_Officer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Indents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Indents</relationshipLabel>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/Purchase_Indent_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent Line Item</label>
    <nameField>
        <label>Purchase Indent Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Indent Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Purchase_Indent__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Indent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Indent</label>
    <referenceTo>Purchase_Indent__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Sales_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line Item</label>
    <referenceTo>Sales_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <formula>TEXT( Opportunity__r.Application__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>LI-{00}</displayFormat>
        <label>Sales Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <formula>Product_In__c  -  Product_Out__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PurchaseIndent.cls
public class PurchaseIndent {
	
    @AuraEnabled
    public static string doInit(String strRecordId){
        mainWrapper objMainWrap = new mainWrapper();
        objMainWrap.objIBUser = [Select Id, Name from User where Id =: UserInfo.getUserId()];
        objMainWrap.procurementPickList = getPickVal(Purchase_Indent__c.Procurement__c.getDescribe());
        objMainWrap.applicationPickList = getPickVal(Opportunity__c.Application__c.getDescribe());
        objMainWrap.againstPickList = getPickVal(Purchase_Indent__c.Against__c.getDescribe());
        objMainWrap.departmentPickList = getPickVal(Purchase_Indent__c.Department__c.getDescribe());
        
        if(String.isBlank(strRecordId)){
            IndentItemWapper objIIW = new IndentItemWapper();
            objIIW.isEdit = true;
            objMainWrap.lstIIW.add(objIIW);
        }
        else{
            List<String> PIFields = getObjectFields('Purchase_Indent__c');
            string PIQuery = 'select ' + string.join(PIFields, ',') +',Ware_house__r.Name,Sales_Officer__r.Name from Purchase_Indent__c where Id =: strRecordId';
            List<Purchase_Indent__c> lstPI = Database.query(PIQuery);
            
            if(lstPI.size() > 0){
                objMainWrap.objPurchaseIndent = lstPI[0];
                if(objMainWrap.objPurchaseIndent.Against__c == 'Direct')
                    objMainWrap.isDirect = true;
                else
                    objMainWrap.isDirect = false;
                
                List<String> PIIFields = getObjectFields('Purchase_Indent_Line_Item__c');
                string PIIQuery = 'select ' + string.join(PIIFields, ',') +',Sales_Order_Line_Item__r.Sales_Order__c from Purchase_Indent_Line_Item__c where Purchase_Indent__c =: strRecordId';
                List<Purchase_Indent_Line_Item__c> lstPII = Database.query(PIIQuery);
                
                set<Id> setId = new set<Id>();
                set<Id> setSO = new set<Id>(); 
                map<Id, Part__c> mapIdVsPart = new map<Id, Part__c>();
                String strWareHouse = objMainWrap.objPurchaseIndent.Ware_house__c;
                if(lstPII.size()> 0){
                    for(Purchase_Indent_Line_Item__c objPII : lstPII){
                        setId.add(objPII.Product_Part__c);
                        setSO.add(objPII.Sales_Order_Line_Item__r.Sales_Order__c);
                    }
                    
                    if(setId.size() > 0){
                        for(Part__c objPart : [Select Id, Name,Part_Name__c,Usage__c,HSN_CODE__c,UOM__c,List_Price_Standard_price__c,
                                               (select id, Total_Quantity__c, Ware_House__c from Stocks__r where Ware_House__c =: strWareHouse) 
                                               from Part__c where Id =:setId])
                        {
                            mapIdVsPart.put(objPart.Id, objPart);
                        }
                    }
                    if(setSO.size() >0 ){
                        for(Sales_Order__c obj : [Select Id, Sales_Order_Acknowledge_Number__c 
                                                  from Sales_Order__c
                                                  where Id=: setSO])
                        {
                            option opt = new option();
                            opt.value = obj.Id;
                            opt.label = obj.Sales_Order_Acknowledge_Number__c;
                            objMainWrap.lstSalesOrder.add(opt);
                        }
                    }
                    
                    for(Purchase_Indent_Line_Item__c objPII : lstPII){
                        IndentItemWapper objIIW = new IndentItemWapper();
                        if(mapIdVsPart.containskey(objPII.Product_Part__c))
                            objIIW.objPart = mapIdVsPart.get(objPII.Product_Part__c);
                        objIIW.strId = objPII.Id;   
                        objIIW.specification = objPII.Specification__c;
                        objIIW.strSalesOrderItemId = objPII.Sales_Order_Line_Item__c;
                        objIIW.pendingPOQty = 0;
                        objIIW.stockActual = objPII.Stock_Actual__c;
                        objIIW.quantity = objPII.QTY__c;
                        //objIIW.Unit = '';
                        objIIW.expectedDate = objPII.Expected_date__c;
                        objIIW.application = objPII.Application__c;
                        objIIW.Remarks = objPII.Remark__c;
                        objIIW.isEdit = true;
                        objIIW.strPartErr ='';
                        objIIW.strExpectedDateErr ='';
                        objIIW.strQuantityErr ='';
                        objIIW.strApplicationErr ='';
                        objIIW.boolShowError = false;
                        objMainWrap.lstIIW.add(objIIW);
                    }
                }
            }
        }
        return JSON.serialize(objMainWrap);
    }
    
    @AuraEnabled
    public static String getSalesOrderItems(string recordId, List<Id> lstId){
        List<SalesOrderItemWrapper> lstSOI = new List<SalesOrderItemWrapper>();
        if(String.isNotBlank(recordId)){
            set<Id> setId = new set<Id>();
            map<Id, Stock__c> mapIdvsStock = new map<Id, Stock__c>();
            List<Sales_Order_Line_Item__c> lstFilterItem = new List<Sales_Order_Line_Item__c>();
            
            List<Sales_Order_Line_Item__c> lst = [Select Id, Name, Quantity__c, Product_Part__c, Product_Part__r.Name, Product_Part__r.Part_Name__c,Product_Part__r.Usage__c, 
                                                  Product_Part__r.UOM__c,HSN_Code__c, Sales_Order__c, Sales_Order__r.Opportunity__r.Ware_House__c,Sales_Order__r.Application__c
                                                  From Sales_Order_Line_Item__c
                                                  where Sales_Order__c =: recordId
                                                  AND Product_Part__c != NULL];
            if(lst.size() > 0){
                
                String strWareHouseId = lst[0].Sales_Order__r.Opportunity__r.Ware_House__c;
                
                if(lstId.size() > 0){
                    for(Sales_Order_Line_Item__c obj : lst){
                        if(!lstId.contains(obj.Id))
                            lstFilterItem.add(obj);
                    }
                }
                else
                   lstFilterItem.addAll(lst);
                
                for(Sales_Order_Line_Item__c obj : lstFilterItem)
                    setId.add(obj.Product_Part__c);
                
                for(Stock__c objStock : [Select Id, Product_In__c, Product_Out__c, Product_Part__c, Total_Quantity__c,Ware_House__c
                                         from Stock__c 
                                         where Product_Part__c =: setId
                                         And Ware_House__c =: strWareHouseId])
                {                    
                    mapIdvsStock.put(objStock.Product_Part__c, objStock);
                }
                
                for(Sales_Order_Line_Item__c obj : lstFilterItem){
                    if(mapIdvsStock.containsKey(obj.Product_Part__c)){
                        //check if SOA Line Item's quantity not available on selected warehouse total quantity than only those item will be shown as an Indent Line Items.
                        if(obj.Quantity__c > mapIdvsStock.get(obj.Product_Part__c).Total_Quantity__c){
                            SalesOrderItemWrapper objwrap = new SalesOrderItemWrapper();
                            objwrap.objSOLI = obj;
                            objwrap.objStock = mapIdvsStock.get(obj.Product_Part__c);
                            lstSOI.add(objwrap);
                        }
                    }
                }
            }
        }
        return JSON.serialize(lstSOI);
    }
    
    @AuraEnabled
    public static string getSalesOrderItemsId(string strSalesOrderId){
        List<Id> lstId = new List<Id>();
        if(String.isNotBlank(strSalesOrderId)){
            for(Sales_Order_Line_Item__c obj : [Select Id from Sales_Order_Line_Item__c where Sales_Order__c =: strSalesOrderId])
                lstId.add(obj.Id);
        }
        return JSON.serialize(lstId);
    }
    
    @AuraEnabled
    public static String SavePurchaseIndent(String strMainWrapper){
        
        mainWrapper objMainWrap = new mainWrapper();
        String PurchaseIntendId ='';
        List<Purchase_Indent_Line_Item__c> lstPLI = new List<Purchase_Indent_Line_Item__c>();
        try{
            system.debug('strMainWrapper--'+strMainWrapper);
            objMainWrap = (mainWrapper)Json.deserialize(strMainWrapper, mainWrapper.class);
            objMainWrap.success = true;
            if(objMainWrap.objPurchaseIndent != null){
                objMainWrap.objPurchaseIndent.Indent_Date__c = system.today();
                upsert objMainWrap.objPurchaseIndent;
                
                String strPurchaseIndentId =objMainWrap.objPurchaseIndent.Id;
                set<Id> setIdPILI = new set<Id>();
                List<Purchase_Indent_Line_Item__c> DeletePILIList = new List<Purchase_Indent_Line_Item__c>();
                List<Purchase_Indent_Line_Item__c> lstSavedPILI =[Select Id, Name from Purchase_Indent_Line_Item__c where Purchase_Indent__c =: strPurchaseIndentId];
                
                for(IndentItemWapper objIIW : objMainWrap.lstIIW){
                    Purchase_Indent_Line_Item__c obj = new Purchase_Indent_Line_Item__c();
                    if(String.isNotBlank(objIIW.strId)){
                        obj.Id = objIIW.strId;
                        setIdPILI.add(obj.Id);
                    }
                    obj.Purchase_Indent__c = objMainWrap.objPurchaseIndent.Id;
                    obj.Product_Part__c = objIIW.objPart.Id;
                    obj.Name = objIIW.objPart.Part_Name__c;
                    obj.Expected_date__c = objIIW.expectedDate;
                    obj.QTY__c = objIIW.quantity;
                    obj.Remark__c = objIIW.remarks;
                    obj.Specification__c = objIIW.specification;
                    if(String.isNotBlank(objIIW.strSalesOrderItemId))
                       obj.Sales_Order_Line_Item__c = objIIW.strSalesOrderItemId;
                    obj.Application__c = objIIW.application;
                    obj.Stock_Actual__c = objIIW.stockActual;
                    lstPLI.add(obj);
                }
                if(lstPLI.size() > 0)
                    upsert lstPLI;
                
                //delete Purchase Indent Item
                if(lstSavedPILI.size()>0){
                    if(setIdPILI.size() > 0){
                        for(Purchase_Indent_Line_Item__c obj : lstSavedPILI)
                            if(!setIdPILI.contains(obj.Id))
                            	DeletePILIList.add(obj);
                    }
                    else{
                        DeletePILIList.addAll(lstSavedPILI);
                    }
                    if(DeletePILIList.size() > 0)
                        delete DeletePILIList;
                }
                //End delete Logic    
            }
        }
        catch(DMLException dm){
            objMainWrap.success = false;
            objMainWrap.strErrorMessage = dm.getDmlMessage(0);
        }
        return JSON.serialize(objMainWrap);
    }
    
    public static List<option> getPickVal(Schema.DescribeFieldResult fieldResult){
        List<option> lstOption = new List<option>();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        {
            option objOption = new option();
            objOption.label = f.getLabel();
            objOption.value = f.getValue();
            lstOption.add(objOption);
        }
        return lstOption;
    }
    
    public static List<String> getObjectFields(string strObjectName){
        map<String , Schema.SObjectType> globalDescription = Schema.getGlobalDescribe();
        Schema.sObjectType sObjType = globalDescription.get(strObjectName);
        Schema.DescribeSObjectResult describeResult = sObjType.getDescribe();
        List<string> lstfieldNames = new List<String>(describeResult.fields.getMap().keySet()); 
        return lstfieldNames;
    }
    
    public class mainWrapper{
        public List<IndentItemWapper> lstIIW;
        public List<option> procurementPickList;
        public List<option> applicationPickList;
        public List<option> againstPickList;
        public List<option> departmentPickList;
        public List<option> lstSalesOrder; //This list hold the the sales order for Edit mode
        
        public Purchase_Indent__c objPurchaseIndent;
        public user objIBUser;
        public boolean isDirect;
        public boolean success;
        public string strErrorMessage;
        
        public mainWrapper(){
            lstIIW = new List<IndentItemWapper>();
            procurementPickList = new List<option>();
            applicationPickList = new List<option>();
            againstPickList = new List<option>();
            departmentPickList = new List<option>();
            lstSalesOrder = new List<option>();
            objPurchaseIndent = new Purchase_Indent__c();
            isDirect = false;
            success = false;
            strErrorMessage = '';
        }
    }
    public class IndentItemWapper{
        public Part__c objPart;
        public String strId;
        public String specification;
        public String strSalesOrderItemId;
        public Integer pendingPOQty;
        public decimal stockActual;
        public decimal quantity;
        //public String unit;
        public Date expectedDate;
        public String application;
       	public String remarks; 
        public boolean isEdit;
        
        public String strPartErr;
        public String strExpectedDateErr;
        public String strQuantityErr;
        public String strApplicationErr;
        public boolean boolShowError;
        
        public IndentItemWapper(){
            objPart = new Part__c();
            strId = '';
            specification = '';
            strSalesOrderItemId='';
            pendingPOQty = 0;
            stockActual = 0;
            quantity = 0;
            //unit = '';
            expectedDate = null;
            application = '';
            remarks = '';
            isEdit = false;
            
            strPartErr ='';
            strExpectedDateErr = '';
            strQuantityErr = '';
            strApplicationErr = '';
            boolShowError = false;
        }
    }
    
    public class SalesOrderItemWrapper{
        Sales_Order_Line_Item__c objSOLI;
        Stock__c objStock;
        boolean isSelected ;
        
        public SalesOrderItemWrapper(){
            objSOLI = new Sales_Order_Line_Item__c();
            objStock = new Stock__c();
            isSelected = true;
        }
    }
    
    public class option
    {
        public string value;
        public string label;
    }
}