force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Reference_Date__c.field-meta.xml
<CustomField>
    <fullName>Reference_Date__c</fullName>
    <label>Reference Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>EP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <label>Usage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELC</fullName>
            </value>
            <value>
                <fullName>DEO</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Engine Parts</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/Purchase_Indent__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Purchase Indent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Indents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Indent_By__c.field-meta.xml
<CustomField>
    <fullName>Indent_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indent By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Indent_Date__c.field-meta.xml
<CustomField>
    <fullName>Indent_Date__c</fullName>
    <label>Indent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Procurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Import</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Reference_No__c</fullName>
    <label>Reference No old</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Sales_Officer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Indents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Indents</relationshipLabel>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/Purchase_Indent_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent Line Item</label>
    <nameField>
        <label>Purchase Indent Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Indent Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Purchase_Indent__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Indent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Indent</label>
    <referenceTo>Purchase_Indent__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>QTY</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Stock_Actual__c.field-meta.xml
<CustomField>
    <fullName>Stock_Actual__c</fullName>
    <label>Stock Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PurchaseIndentEdit.cls
public class PurchaseIndentEdit {
    
     @AuraEnabled
    public static string doInit(String recordId){
        mainWrapper objMainWrap = new mainWrapper();
        if(String.isNotBlank(recordId)){
            objMainWrap.success =true;
            objMainWrap.objPurchaseIndent = [Select Id,Indent_By__c,Indent_Date__c,Procurement__c,Reference_Date__c,Reference_No__c,
                                             Remark__c,Sales_Officer__c,Terms_and_Conditions__c, Ware_House__c,Department__c
                                             From Purchase_Indent__c 
                                             where Id =: recordId];
            
            List<Purchase_Indent_Line_Item__c> lstPILI =[ Select Id, Application__c, Expected_date__c,Product_Part__c, Product_Part__r.Name, Product_Part__r.Part_Name__c,
                                                         Product_Part__r.Usage__c,Purchase_Indent__c,QTY__c,Remark__c,Specification__c,Stock_Actual__c
                                                         From Purchase_Indent_Line_Item__c
                                                         where Purchase_Indent__c =: recordId];
            
            for(Purchase_Indent_Line_Item__c obj : lstPILI){
                IndentItemWapper objIIW = new IndentItemWapper();
                objIIW.objPILI = obj;
                objIIW.objPart.Id = obj.Product_Part__c;
                objIIW.objPart.Name = obj.Product_Part__r.Name;
                objIIW.objPart.Part_Name__c = obj.Product_Part__r.Part_Name__c;
                objIIW.objPart.Usage__c = obj.Product_Part__r.Usage__c;
                objIIW.isEdit = false;
                objMainWrap.lstIIW.add(objIIW);
            }                    
            
            if(String.isNotEmpty(objMainWrap.objPurchaseIndent.Indent_By__c))
                objMainWrap.objIBUser = [Select Id, Name from User where Id =: objMainWrap.objPurchaseIndent.Indent_By__c];
            if(String.isNotEmpty(objMainWrap.objPurchaseIndent.Sales_Officer__c))
                objMainWrap.objSOUser = [Select Id, Name from User where Id =: objMainWrap.objPurchaseIndent.Sales_Officer__c];
            
            objMainWrap.procurementPickList = getPickVal(Purchase_Indent__c.Procurement__c.getDescribe());
            objMainWrap.applicationPickList = getPickVal(Opportunity__c.Application__c.getDescribe());
            
        }
        return JSON.serialize(objMainWrap);
    }
        
    @AuraEnabled
    public static String SavePurchaseIndent(String strMainWrapper){
        
        mainWrapper objMainWrap = new mainWrapper();
        List<Purchase_Indent_Line_Item__c> lstPLI = new List<Purchase_Indent_Line_Item__c>();
        try{
            system.debug('strMainWrapper--'+strMainWrapper);
            objMainWrap = (mainWrapper)Json.deserialize(strMainWrapper, mainWrapper.class);
            objMainWrap.success = true;
            if(objMainWrap.objPurchaseIndent != null){
                update objMainWrap.objPurchaseIndent;
                String recordId = objMainWrap.objPurchaseIndent.Id;
                
                List<Purchase_Indent_Line_Item__c> lstPILI =[ Select Id From Purchase_Indent_Line_Item__c where Purchase_Indent__c =: recordId];
              
                List<Purchase_Indent_Line_Item__c> deleteList = new List<Purchase_Indent_Line_Item__c>();
                List<Purchase_Indent_Line_Item__c> updateList = new List<Purchase_Indent_Line_Item__c>();
                Set<Id> updateSetId = new Set<Id>();
                if(objMainWrap.lstIIW.size() > 0){
                    for(IndentItemWapper objIIW : objMainWrap.lstIIW){
                        updateList.add(objIIW.objPILI);
                        updateSetId.add(objIIW.objPILI.Id);
                    }
                    for(Purchase_Indent_Line_Item__c obj : lstPILI){
                        if(!updateSetId.contains(obj.Id))
                            deleteList.add(obj);
                    }
                    
                }
                else{
                    if(lstPILI.size() > 0)
                        delete lstPILI;
                }
                
                if(updateList.size() > 0)
                    update  updateList;
                if(deleteList.size() > 0)
                    delete  deleteList;
            }
        }
        catch(DMLException dm){
            objMainWrap.success = false;
            objMainWrap.strErrorMessage = dm.getDmlMessage(0);
        }
        return JSON.serialize(objMainWrap);
    }
    
    public static List<option> getPickVal(Schema.DescribeFieldResult fieldResult){
        List<option> lstOption = new List<option>();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        {
            option objOption = new option();
            objOption.label = f.getLabel();
            objOption.value = f.getValue();
            lstOption.add(objOption);
        }
        return lstOption;
    }
    
    public class mainWrapper{
        public List<IndentItemWapper> lstIIW;
        public List<option> procurementPickList;
        public List<option> applicationPickList;
        public Purchase_Indent__c objPurchaseIndent;
        public user objIBUser;
        public user objSOUser;
        public boolean success;
        public string strErrorMessage;
        
        public mainWrapper(){
            lstIIW = new List<IndentItemWapper>();
            procurementPickList = new List<option>();
            applicationPickList = new List<option>();
            objPurchaseIndent = new Purchase_Indent__c();
            success = false;
            strErrorMessage = '';
        }
    }
    public class IndentItemWapper{
        public Part__c objPart;
        public Purchase_Indent_Line_Item__c objPILI;
        public Integer pandingPOQty;
        public Integer stockActual;
        public boolean isEdit;
        
        public String strPartErr;
        public String strExpectedDateErr;
        public String strQuantityErr;
        public String strApplicationErr;
        public boolean boolShowError;
        
        public IndentItemWapper(){
            objPart = new Part__c();
            objPILI = new Purchase_Indent_Line_Item__c();
            pandingPOQty = 0;
            stockActual = 0;
            isEdit = false;
            
            strPartErr ='';
            strExpectedDateErr = '';
            strQuantityErr = '';
            strApplicationErr = '';
            boolShowError = false;
        }
    }

    public class option
    {
        public string value;
        public string label;
    }
}