force-app/main/default/objects/Powerparts_Service_Request_Team__c/Powerparts_Service_Request_Team__c.object-meta.xml
<CustomObject>
    <label>Powerparts Service Request Team</label>
    <nameField>
        <displayFormat>Team-{0000}</displayFormat>
        <label>Service Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Powerparts Service Request Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1__c.field-meta.xml
<CustomField>
    <fullName>Engineer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Engineer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Branch Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>A&amp;I Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer1_Check_In__c</fullName>
    <label>Engineer1 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer1_Check_Out__c</fullName>
    <label>Engineer1 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer2_Check_In__c</fullName>
    <label>Engineer2 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer2_Check_Out__c</fullName>
    <label>Engineer2 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3__c.field-meta.xml
<CustomField>
    <fullName>Engineer3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer3_Check_In__c</fullName>
    <label>Engineer3 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer3_Check_Out__c</fullName>
    <label>Engineer3 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4__c.field-meta.xml
<CustomField>
    <fullName>Engineer4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer4_Check_In__c</fullName>
    <label>Engineer4 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer4_Check_Out__c</fullName>
    <label>Engineer4 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Powerparts Service Request Team</relationshipLabel>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Safety_rules__c/Safety_rules__c.object-meta.xml
<CustomObject>
    <label>Safety Rule</label>
    <nameField>
        <displayFormat>Rules-{0000}</displayFormat>
        <label>Safety Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Safety_rules__c/fields/Fire_Hazard__c.field-meta.xml
<CustomField>
    <fullName>Fire_Hazard__c</fullName>
    <description>Any fire hazard or flammable/chemical liquids in open/exposed manner?</description>
    <label>Fire Hazard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Other_Safety_Hazard__c.field-meta.xml
<CustomField>
    <fullName>Other_Safety_Hazard__c</fullName>
    <description>Any other Safety Hazard?</description>
    <label>Other Safety Hazard</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipName>Safety_rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Closed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_Time__c</fullName>
    <label>Closed Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Date_Time_Attended__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Attended__c</fullName>
    <label>Date Time Attended</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Parts Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Visit_ReportedTime__c.field-meta.xml
<CustomField>
    <fullName>Visit_ReportedTime__c</fullName>
    <label>Visit ReportedTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Work_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Work_Start_Time__c</fullName>
    <label>Work Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CheckIncls.cls
global class CheckIncls
{
    public static string strResponse = '';
    
    @AuraEnabled
    public static string updateCheckIn(String strRecordId) 
    {
        ResponseWrapper objWrap = new ResponseWrapper();
        objWrap.success = true;
        objWrap.errorMessage = '';
        try
        {
            if(strRecordId != null && strRecordId != '')
            { 
                List<Powerparts_Service_Request_Team__c> lstUpdatePSRT = new List<Powerparts_Service_Request_Team__c>();
                list<Service_Request__c> lstupdateSr = new list<Service_Request__c>();
                Id strCurrentUserId = UserInfo.getUserId() ;
                
                List<Service_Request__c> lstSR = [Select Id,(SELECT Id, Name, Other_Safety_Hazard__c, Service_Request__c, Fire_Hazard__c FROM Safety_rules__r), Status__c,Date_Time_Attended__c,Work_Start_Time__c,Closed_Date_Time__c,Visit_ReportedTime__c from Service_Request__c where Id =: strRecordId Limit 1];
                if(lstSR.size() > 0)
                {
                    List<Powerparts_Service_Request_Team__c> lstPSRT = [SELECT Id,Name,Engineer1_Check_In__c,Engineer1_Check_Out__c,Engineer1__c,Engineer2_Check_In__c,Engineer2_Check_Out__c,Engineer2__c,Engineer3_Check_In__c,Engineer3_Check_Out__c,Engineer3__c,Engineer4_Check_In__c,Engineer4_Check_Out__c,Engineer4__c,Service_Request__r.Work_Start_Time__c,Service_Request__c 
                                                                        FROM Powerparts_Service_Request_Team__c
                                                                        Where Service_Request__c =: lstSR[0].Id Limit 1];
                    if(lstPSRT.size() > 0)
                    {
                        if(lstSR[0].Status__c != 'On Hold')
                        {
                            if(lstSR[0].Closed_Date_Time__c == null && lstSR[0].Status__c != 'Closed')
                            {
                                if(strCurrentUserId != null)
                                {
                                    if(strCurrentUserId == lstPSRT[0].Engineer1__c)
                                    {
                                        if(lstPSRT[0].Engineer1_Check_In__c == null || lstPSRT[0].Engineer1_Check_In__c.Date() != System.today())
                                        {
                                            lstPSRT[0].Engineer1_Check_In__c = system.now();
                                            lstUpdatePSRT.add(lstPSRT[0]);
                                        }
                                        else
                                        {
                                            objWrap.success = false;
                                            objWrap.errorMessage = system.label.Check_IN;
                                        }
                                        if(lstSR[0].Visit_ReportedTime__c == null )
                                        {
                                            if(lstSR[0].Work_Start_Time__c == null )
                                            {
                                                //lstSR[0].Work_Start_Time__c  = system.now();
                                            }
                                            lstSR[0].Visit_ReportedTime__c  = system.now();
                                            lstupdateSr.add(lstSR[0]);
                                            System.debug('lstSR[0].Visit_ReportedTime__c--'+lstSR[0].Visit_ReportedTime__c);
                                            
                                        }
                                        
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer2__c)
                                    {
                                        if(lstPSRT[0].Engineer2_Check_In__c == null || lstPSRT[0].Engineer2_Check_In__c.Date() != System.today())
                                        {
                                            lstPSRT[0].Engineer2_Check_In__c = system.now();
                                            lstUpdatePSRT.add(lstPSRT[0]);
                                        }
                                        else
                                        {
                                            objWrap.success = false;
                                            objWrap.errorMessage = system.label.Check_IN;
                                        }
                                        
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer3__c)
                                    {
                                        if(lstPSRT[0].Engineer3_Check_In__c == null || lstPSRT[0].Engineer3_Check_In__c.Date() != System.today())
                                        {
                                            lstPSRT[0].Engineer3_Check_In__c = system.now();
                                            lstUpdatePSRT.add(lstPSRT[0]);
                                        }
                                        else
                                        {
                                            objWrap.success = false;
                                            objWrap.errorMessage = system.label.Check_IN;
                                        }
                                        
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer4__c)
                                    {
                                        if(lstPSRT[0].Engineer4_Check_In__c == null || lstPSRT[0].Engineer4_Check_In__c.Date() != System.today())
                                        {
                                            lstPSRT[0].Engineer4_Check_In__c = system.now();
                                            lstUpdatePSRT.add(lstPSRT[0]);
                                        }
                                        else
                                        {
                                            objWrap.success = false;
                                            objWrap.errorMessage = system.label.Check_IN;
                                        }
                                    }
                                    else
                                    {
                                        objWrap.success = false;
                                        objWrap.errorMessage = 'This Service Request is not assign you.';
                                    }
                                }
                            }
                            else
                            {
                                objWrap.success = false;
                                objWrap.errorMessage = 'Service Request has been closed.'; 
                            }
                        }
                        else
                        {
                            objWrap.success = false;
                            objWrap.errorMessage = 'You Can not update record.Status is On Hold.';   
                        }
                    }
                    else
                    {
                        objWrap.success = false;
                        objWrap.errorMessage = 'The team is not created.';   
                    }
                }
                if(lstUpdatePSRT.size()>0)
                {
                 update lstUpdatePSRT;   
                }
                    
                if(lstupdateSr.size()>0)
                {
                  update lstupdateSr;
                }
                
            }
            else
            {
                objWrap.success = false;
                objWrap.errorMessage = 'Invalid record id.';
            }
        }
        catch(DMLException ex)
        {
            objWrap.success = false;
            objWrap.errorMessage = ex.getDmlMessage(0);
        } 
        return Json.serialize(objWrap);
    }
    
    public class ResponseWrapper{
        public boolean success;
        public string errorMessage;
    }
}