force-app/main/default/objects/Powerparts_Service_Request_Team__c/Powerparts_Service_Request_Team__c.object-meta.xml
<CustomObject>
    <label>Powerparts Service Request Team</label>
    <nameField>
        <displayFormat>Team-{0000}</displayFormat>
        <label>Service Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Powerparts Service Request Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1__c.field-meta.xml
<CustomField>
    <fullName>Engineer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Engineer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Branch Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>A&amp;I Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer1_Check_In__c</fullName>
    <label>Engineer1 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer1_Check_Out__c</fullName>
    <label>Engineer1 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer2_Check_In__c</fullName>
    <label>Engineer2 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer2_Check_Out__c</fullName>
    <label>Engineer2 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3__c.field-meta.xml
<CustomField>
    <fullName>Engineer3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer3_Check_In__c</fullName>
    <label>Engineer3 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer3_Check_Out__c</fullName>
    <label>Engineer3 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4__c.field-meta.xml
<CustomField>
    <fullName>Engineer4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Engineer4_Check_In__c</fullName>
    <label>Engineer4 Check In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Engineer4_Check_Out__c</fullName>
    <label>Engineer4 Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Powerparts Service Request Team</relationshipLabel>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Closed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date_Time__c</fullName>
    <label>Closed Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Date_Time_Attended__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Attended__c</fullName>
    <label>Date Time Attended</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Primary_Engineer_Check_Out__c.field-meta.xml
<CustomField>
    <fullName>Primary_Engineer_Check_Out__c</fullName>
    <label>Primary Engineer Check Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Parts Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckOutcls.cls
global class CheckOutcls
{
    public static string strResponse = '';
    
    @AuraEnabled
    public static string updateCheckOut(String strRecordId) 
    {
        ResponseWrapper objWrap = new ResponseWrapper();
        objWrap.success = true;
        objWrap.errorMessage = '';
        list<Service_Request__c> lstSRequest = new list<Service_Request__c>();
        try
        {
            if(strRecordId != null && strRecordId != '')
            { 
                List<Powerparts_Service_Request_Team__c> lstUpdatePSRT = new List<Powerparts_Service_Request_Team__c>();
                Id strCurrentUserId = UserInfo.getUserId() ;
                
                List<Service_Request__c> lstSR = [Select Id,Primary_Engineer_Check_Out__c  , Status__c,Date_Time_Attended__c,Closed_Date_Time__c from Service_Request__c where Id =: strRecordId Limit 1];
                if(lstSR.size() > 0)
                {
                    List<Powerparts_Service_Request_Team__c> lstPSRT = [SELECT Id,Name,Engineer1_Check_In__c,Engineer1_Check_Out__c,Engineer1__c,Engineer2_Check_In__c,Engineer2_Check_Out__c,Engineer2__c,Engineer3_Check_In__c,Engineer3_Check_Out__c,Engineer3__c,Engineer4_Check_In__c,Engineer4_Check_Out__c,Engineer4__c,Service_Request__c,Service_Request__r.Primary_Engineer_Check_Out__c 
                                                                        FROM Powerparts_Service_Request_Team__c
                                                                        Where Service_Request__c =: lstSR[0].Id Limit 1];
                    if(lstPSRT.size() > 0)
                    {
                        
                        if(lstSR[0].Status__c != 'On Hold')
                        {
                            if(lstSR[0].Closed_Date_Time__c == null && lstSR[0].Status__c != 'Closed')
                            {
                                if(strCurrentUserId != null)
                                {
                                    if(strCurrentUserId == lstPSRT[0].Engineer1__c)
                                    {
                                        if(lstPSRT[0].Engineer1_Check_In__c != null )
                                        {
                                            if(lstPSRT[0].Engineer1_Check_Out__c == null || lstPSRT[0].Engineer1_Check_Out__c.Date() != System.today())
                                            {
                                                lstPSRT[0].Engineer1_Check_Out__c = system.now();
                                                Service_Request__c objSR = new Service_Request__c();
                                                objSR.Id = lstPSRT[0].Service_Request__c;
                                                objSR.Primary_Engineer_Check_Out__c  = system.now();
                                                lstSRequest.add(objSR);
                                                system.debug('...objSR...'+objSR);
                                                lstUpdatePSRT.add(lstPSRT[0]);
                                            }
                                            else
                                            {
                                                objWrap.success = false;
                                                objWrap.errorMessage = system.label.Check_Out;
                                            }
                                        }
                                        else
                                        {
                                                objWrap.success = false;
                                                objWrap.errorMessage = 'Please Check In First.';
                                        }
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer2__c)
                                    {
                                        if(lstPSRT[0].Engineer2_Check_In__c != null )
                                        {
                                            if(lstPSRT[0].Engineer2_Check_Out__c == null || lstPSRT[0].Engineer2_Check_Out__c.Date() != System.today())
                                            {
                                                lstPSRT[0].Engineer2_Check_Out__c = system.now();
                                                lstUpdatePSRT.add(lstPSRT[0]);
                                            }
                                            else
                                            {
                                                objWrap.success = false;
                                                objWrap.errorMessage = system.label.Check_Out;
                                            }
                                        }
                                        else
                                        {
                                                objWrap.success = false;
                                                objWrap.errorMessage = 'Please Check In First.';
                                        }
                                        
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer3__c)
                                    {
                                        if(lstPSRT[0].Engineer3_Check_In__c != null )
                                        {
                                            if(lstPSRT[0].Engineer3_Check_Out__c == null || lstPSRT[0].Engineer3_Check_Out__c.Date() != System.today())
                                            {
                                                lstPSRT[0].Engineer3_Check_Out__c = system.now();
                                                lstUpdatePSRT.add(lstPSRT[0]);
                                            }
                                            else
                                            {
                                                objWrap.success = false;
                                                objWrap.errorMessage = system.label.Check_Out;
                                            }
                                        }
                                        else
                                        {
                                                objWrap.success = false;
                                                objWrap.errorMessage = 'Please Check In First.';
                                        }
                                        
                                    }
                                    else if(strCurrentUserId == lstPSRT[0].Engineer4__c)
                                    {
                                        if(lstPSRT[0].Engineer4_Check_In__c != null )
                                        {
                                            if(lstPSRT[0].Engineer4_Check_Out__c == null || lstPSRT[0].Engineer4_Check_Out__c.Date() != System.today())
                                            {
                                                lstPSRT[0].Engineer4_Check_Out__c = system.now();
                                                lstUpdatePSRT.add(lstPSRT[0]);
                                            }
                                            else
                                            {
                                                objWrap.success = false;
                                                objWrap.errorMessage = system.label.Check_Out;
                                            }
                                        }
                                        else
                                        {
                                                objWrap.success = false;
                                                objWrap.errorMessage = 'Please Check In First.';
                                        }
                                    }
                                    else
                                    {
                                        objWrap.success = false;
                                        objWrap.errorMessage = 'This Service Request is not assign you.';
                                    }
                                }
                            }
                            else
                            {
                                objWrap.success = false;
                                objWrap.errorMessage = 'Service Request has been closed.'; 
                            }
                        }
                        else
                        {
                            objWrap.success = false;
                            objWrap.errorMessage = 'You Can not update record.Status is On Hold.';   
                        }
                    }
                    else
                    {
                        objWrap.success = false;
                        objWrap.errorMessage = 'The team is not created.';   
                    }
                }
                if(lstUpdatePSRT.size()>0)
                    update lstUpdatePSRT;
                
                if(lstSRequest.size()>0)
                    update lstSRequest;
                    
                system.debug('.........'+lstUpdatePSRT.size());  
                 system.debug('..lstSRequest.......'+lstSRequest.size());   
                
            }
            else
            {
                objWrap.success = false;
                objWrap.errorMessage = 'Invalid record id.';
            }
        }
        catch(Exception e)
        {
            objWrap.success = false;
            objWrap.errorMessage = ''+e.getMessage();
        } 
        return Json.serialize(objWrap);
    }
    
    public class ResponseWrapper{
        public boolean success;
        public string errorMessage;
    }
}