force-app/main/default/objects/Generating_Account_Number__c/Generating_Account_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generating Account Number</label>
</CustomObject>

force-app/main/default/objects/Generating_Account_Number__c/fields/Unique_Number__c.field-meta.xml
<CustomField>
    <fullName>Unique_Number__c</fullName>
    <label>Unique Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/OEM_Customer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <label>Enquiry Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Proposal/Quote</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
                <isActive>false</isActive>
                <label>Discovery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestClassHandlerTotalCountofLineitem.cls
@istest
public class TestClassHandlerTotalCountofLineitem {
    public static testMethod void testOnInsertlineItemOnOpp(){
      
        Trigger_Setting__c ts=new Trigger_Setting__c();
        ts.Name = 'Account';
        ts.Active__c=true;
        insert ts;
        
        Generating_Account_Number__c gan=new Generating_Account_Number__c();
        gan.Name='Unique Number';
        gan.Unique_Number__c=458796;
        insert gan;
        
        Id RecordTypeIdContact = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
             
        Account a =new Account();

        a.Name='acc';
        a.RecordTypeId=RecordTypeIdContact;
        a.Type='Customer';
        a.PAN_NO__c='45656876';
        a.GSTIN_No__c='3976543';
        insert a;
        system.debug('account'+a);
        
        Opportunity__c o=new Opportunity__c();
        //o.Name='name';
        o.Stage__c='Negotiation';
        o.OEM_Customer__c=a.id;
        o.Opportunity_Close_Date__c=system.today()+10;
        insert o;
        
        system.debug('accountOpportunity'+o);
        
        line_item__c li=new line_item__c();
        li.Opportunity__c=o.id;
         system.debug('contact insertedx'+ li.Opportunity__c);
        li.Quantity__c=1;
        li.Discount__c=10;
        li.CGST__c=5;
        li.Sales_Price__c=1000;
        insert li;
        system.debug('accountOpportunityLineItem'+li);
        
        line_item__c lit=new line_item__c();
        lit.Id=li.Id;
        lit.Sales_Price__c=3000;
        update lit;   
        
        line_item__c litd=new line_item__c();
        litd.Id=lit.Id;
        
        delete litd;   
        
    }
}