force-app/main/default/objects/Generating_Account_Number__c/Generating_Account_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generating Account Number</label>
</CustomObject>

force-app/main/default/objects/Generating_Account_Number__c/fields/Unique_Number__c.field-meta.xml
<CustomField>
    <fullName>Unique_Number__c</fullName>
    <label>Unique Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/OEM_Customer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <label>Enquiry Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Proposal/Quote</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
                <isActive>false</isActive>
                <label>Discovery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>PPL-{000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Customer_Party__c.field-meta.xml
<CustomField>
    <fullName>Customer_Party__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddproductControllerTest.cls
@isTest
public class AddproductControllerTest {
    @isTest static void productTest(){
        // insert trigger on/Off custom setting of toolingSheet
        list<Trigger_Setting__c> accOnOffTLst = new list<Trigger_Setting__c>();
        Trigger_Setting__c objTrigFiles = new Trigger_Setting__c();
        objTrigFiles.Name = 'Account';
        objTrigFiles.Active__c = true;
        accOnOffTLst.add(objTrigFiles);
        insert accOnOffTLst;
        
        Generating_Account_Number__c accountNumber = new Generating_Account_Number__c();
        accountNumber.Name = 'Unique Number';
        insert accountNumber;
        integer intCountAccountNumber = integer.valueof(accountNumber.Unique_Number__c);
        //intCountAccountNumber = intCountAccountNumber++;

      //  @istest
    //static void execute(){
     //   clsUtility.testDataCustomSetting();
       // clsUtility.testDataAccountContact(20,20,true);
    //}
        
        Account aO = new Account();
        aO.Name = 'Test Account';
        aO.BillingCity = 'Agra';
        aO.Region__c = 'East'; 
        aO.Account_Number__c = intCountAccountNumber;
        insert aO; 
        
        Contact cO = new Contact();
        cO.AccountId = aO.Id;
        cO.LastName = 'Bhatiya';
        cO.Email = 'test@outlook.com';
        cO.MobilePhone = '8348583457';
        insert cO;
        
        Opportunity__c oO = new Opportunity__c();
        //oO.Name = 'Test Opp';
        oO.OEM_Customer__c = aO.Id;
        oO.Stage__c = 'New';
        oO.Opportunity_Close_Date__c = Date.newInstance(2021, 1, 9);
        insert oO; 
        
        Quote__c qO = new Quote__c();
       	qO.Customer_Party__c = aO.Id;
        qO.Contact_Name__c = cO.Id;
        qO.Opportunity__c = oO.Id;
        insert qO;
    }
}