force-app/main/default/objects/Generating_Account_Number__c/Generating_Account_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generating Account Number</label>
</CustomObject>

force-app/main/default/objects/Generating_Account_Number__c/fields/Unique_Number__c.field-meta.xml
<CustomField>
    <fullName>Unique_Number__c</fullName>
    <label>Unique Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>PPL-{000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Customer_Party__c.field-meta.xml
<CustomField>
    <fullName>Customer_Party__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestClassOnQuoteEmailSend.cls
@istest
public class TestClassOnQuoteEmailSend {
    public static testmethod void testemail(){
        Trigger_Setting__c ts=new Trigger_Setting__c();
        ts.Name = 'Account';
        ts.Active__c=true;
        
        insert ts;
        Generating_Account_Number__c gan=new Generating_Account_Number__c();
        gan.Name='Unique Number';
        gan.Unique_Number__c=458796;
        insert gan;
        
        Account a=new Account();
        a.name='AccName';
        a.GSTIN_No__c='5387393';
        a.Type='Customer';
        a.PAN_NO__c='4865979';
        a.BillingCity='city';
        a.Region__c='East';
        insert a;
        system.debug('Account insertedx'+a);
        
        contact c=new contact();
        c.Accountid=a.Id;
        c.LastName=a.Name;
        
        c.Email='krishan@cccinfotech.com';
        c.MobilePhone='6979780';
        insert c;
        system.debug('contact insertedx'+c);
        
        Quote__c qt=new Quote__c();
        qt.Contact_Name__c=c.Id;
        qt.Customer_Party__c=a.Id;
        insert qt;
         system.debug('Quote insertedx'+qt);
        
        ClassOnQuoteEmailSend.intid(qt.id);
        ClassOnQuoteEmailSend.send(qt.id ,'subject','String Bodyy' , 'krishan@cccinfotech.com' , 'krishanaggarwal750@gmail.com');
    }
}