force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Freeze</fullName>
                <isActive>false</isActive>
                <label>Freeze</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>LI-{00}</displayFormat>
        <label>Sales Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Sales Order Line Items (Stock)</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Freeze_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Freeze Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Total_Unbooked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Unbooked_Quantity__c</fullName>
    <formula>Total_Quantity__c -  Freeze_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Unbooked Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SalesOrderHelper.cls
public class SalesOrderHelper {
    public void onBeforeUpdate(List<Sales_Order__c> triggerNew, Map<Id, Sales_Order__c> TOM){
        checkLineItemsOnInsert(triggerNew,TOM);
    }
    
    public void checkLineItemsOnInsert(List<Sales_Order__c> triggerNew, Map<Id, Sales_Order__c> oldmap){
        set<string> setOfSOID = new set<string>();
        for(Sales_Order__c objSO : triggerNew)
        {
            if(objSO.Status__c == 'Freeze' && oldmap.get(objSO.Id).Status__c != objSO.Status__c){
                setOfSOID.add(objSO.Id);
            }
        }
        if(setOfSOID.size()>0)
        {
            set<string> setOfProduct = new set<string>();
            map<string, list<Sales_Order_Line_Item__c>> mapSORelatedProductItem = new map<string,list<Sales_Order_Line_Item__c>>();
            for(Sales_Order_Line_Item__c objSO : [SELECT Id,product_part__c,Sales_Order__r.Ware_House__c,Quantity__c,Sales_Order__c FROM Sales_Order_Line_Item__c where Sales_Order__c IN: setOfSOID])
            {
                setOfProduct.add(objSO.product_part__c);
                if(mapSORelatedProductItem.containskey(objSO.Sales_Order__c) && mapSORelatedProductItem.get(objSO.Sales_Order__c) != null)
                {
                    list<Sales_Order_Line_Item__c> lstSOI = new list<Sales_Order_Line_Item__c>();
                    lstSOI = mapSORelatedProductItem.get(objSO.Sales_Order__c);
                    lstSOI.add(objSO);
                    mapSORelatedProductItem.put(objSO.Sales_Order__c,lstSOI);
                }
                else
                {
                    list<Sales_Order_Line_Item__c> lstSOI = new list<Sales_Order_Line_Item__c>();
                    lstSOI.add(objSO);
                    mapSORelatedProductItem.put(objSO.Sales_Order__c,lstSOI);
                }
            }
            
            map<string,Stock__c> mapIdRelatedStock = new map<string,Stock__c>();
            map<string, Stock__c> mapWareHouseProductbasedQuantity = new map<string, Stock__c>();
            map<string, string> mapWareHouseProductbasedStockId = new map<string, string>();
            for(Stock__c objStock : [select id,Name,Product_Part__c,Quantity__c,Total_Unbooked_Quantity__c,Ware_House__c,Freeze_Quantity__c from Stock__c where Product_Part__c IN: setOfProduct])
            {
                mapIdRelatedStock.put(objStock.Id,objStock);
                mapWareHouseProductbasedQuantity.put(objStock.Ware_House__c+'-'+objStock.Product_Part__c,objStock);
                mapWareHouseProductbasedStockId.put(objStock.Ware_House__c+'-'+objStock.Product_Part__c,objStock.Id);
                System.debug(objStock.Ware_House__c+'-'+objStock.Product_Part__c);
            }
            
            for(Sales_Order__c objSO : triggerNew)
            {
                map<string,Stock__c> mapIdRelatedStockClone = new map<string,Stock__c>(mapIdRelatedStock);
                string strwareHouseDifferent = '';
                boolean isStockAvailableBothWareHouse = false;
                integer countLst = 0;
                if(objSO.Ware_House__c != system.label.Gurgaon_Ware_House)
                {
                    strwareHouseDifferent = system.label.Gurgaon_Ware_House;
                }
                else{
                    strwareHouseDifferent = system.label.Kolkata_Warehouse;
                }
                if(mapSORelatedProductItem.containskey(objSO.id) && mapSORelatedProductItem.get(objSO.id) != null)
                {
                    for(Sales_Order_Line_Item__c objSOI : mapSORelatedProductItem.get(objSO.id))
                    {
                        if(countLst >0 && isStockAvailableBothWareHouse)
                        {
                            System.debug('countLst------- '+countLst+'...isStockAvailableBothWareHouse'+isStockAvailableBothWareHouse);
                            countLst = countLst+1;
                            if(objSO.Ware_House__c != null && mapWareHouseProductbasedStockId.containskey(objSO.Ware_House__c+'-'+objSOI.Product_Part__c) && mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c) != null)
                            {
                                System.debug('objSO.Ware_House__c------- '+objSO.Ware_House__c);
                                if(mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c > objSOI.Quantity__c)
                                {
                                    Stock__c objStock = new stock__c();
                                    objStock = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c));
                                    objStock.Freeze_Quantity__c = objStock.Freeze_Quantity__c + objSOI.Quantity__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);
                                    isStockAvailableBothWareHouse = true;
                                }
                                else{
                                    isStockAvailableBothWareHouse = false;
                                }
                                if(mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c < objSOI.Quantity__c)
                                {
                                system.debug('objSOI.Product_Part__c)-----'+objSOI.Product_Part__c);
                                    decimal intCountWareHouseQuantity = objSOI.Quantity__c - mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c ;
                                    
                                    Stock__c objStock = new stock__c();
                                    objStock = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c));
                                    objStock.Freeze_Quantity__c = objStock.Freeze_Quantity__c+mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);
                                    
                                    Stock__c objStock2 = new stock__c();
                                    objStock2 = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(strwareHouseDifferent+'-'+objSOI.Product_Part__c));
                                    system.debug('--------'+isStockAvailableBothWareHouse );
                  system.debug('----objStock2.Total_Unbooked_Quantity__c----'+objStock2.Total_Unbooked_Quantity__c );
                  system.debug('-----intCountWareHouseQuantity---'+intCountWareHouseQuantity );
                                    if(objStock2.Total_Unbooked_Quantity__c >= intCountWareHouseQuantity)
                                    {
                                    system.debug('objStock2.Freeze_Quantity__c-----'+objStock2.Freeze_Quantity__c);
                                        objStock2.Freeze_Quantity__c = objStock2.Freeze_Quantity__c + intCountWareHouseQuantity;
                                        mapIdRelatedStock.put(objStock2.Id,objStock2);
                                        isStockAvailableBothWareHouse = true;
                                    }
                                    else{
                                        isStockAvailableBothWareHouse = false;
                                    }
                                }
                            }
                            
                            else 
                            {
                                System.debug('objSO.Ware_House__c---else---- ');
                                Stock__c objStock2 = new stock__c();
                                objStock2 = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(strwareHouseDifferent+'-'+objSOI.Product_Part__c));
                                if(objStock2 !=null)
                                if(objStock2.Total_Unbooked_Quantity__c > objSOI.Quantity__c)
                                {
                                    objStock2.Freeze_Quantity__c = objStock2.Freeze_Quantity__c + objSOI.Quantity__c;
                                    mapIdRelatedStock.put(objStock2.Id,objStock2);
                                    isStockAvailableBothWareHouse = true;
                                }
                                else{
                                        isStockAvailableBothWareHouse = false;
                                    }
                            }
                                                           
                        }
                        else if(countLst == 0){
                            countLst = countLst+1;
                            if(objSO.Ware_House__c != null && mapWareHouseProductbasedStockId.containskey(objSO.Ware_House__c+'-'+objSOI.Product_Part__c) && mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c) != null)
                            {
                                System.debug('objSO.Ware_House__c------- '+objSO.Ware_House__c);
                                if(mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c > objSOI.Quantity__c)
                                {
                                    Stock__c objStock = new stock__c();
                                    objStock = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c));
                                    objStock.Freeze_Quantity__c = objStock.Freeze_Quantity__c + objSOI.Quantity__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);
                                    isStockAvailableBothWareHouse = true;
                                }
                                else{
                                    isStockAvailableBothWareHouse = false;
                                }
                                if(mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c < objSOI.Quantity__c)
                                {
                                system.debug('objSOI.Product_Part__c)-----'+objSOI.Product_Part__c);
                                    decimal intCountWareHouseQuantity = objSOI.Quantity__c - mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c ;
                                    
                                    Stock__c objStock = new stock__c();
                                    objStock = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c));
                                    objStock.Freeze_Quantity__c = objStock.Freeze_Quantity__c+mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(objSO.Ware_House__c+'-'+objSOI.Product_Part__c)).Total_Unbooked_Quantity__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);
                                    
                                    Stock__c objStock2 = new stock__c();
                                    system.debug('--------'+strwareHouseDifferent+'-'+objSOI.Product_Part__c );
                                    system.debug('--------'+mapWareHouseProductbasedStockId.get(strwareHouseDifferent+'-'+objSOI.Product_Part__c) );
                                    objStock2 = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(strwareHouseDifferent+'-'+objSOI.Product_Part__c));
                                    system.debug('--------'+isStockAvailableBothWareHouse );
                                    system.debug('--------'+objStock2.Total_Unbooked_Quantity__c );
                                    system.debug('--------'+intCountWareHouseQuantity );
                                    if(objStock2.Total_Unbooked_Quantity__c > intCountWareHouseQuantity)
                                    {
                                    system.debug('objStock2.Freeze_Quantity__c-----'+objStock2.Freeze_Quantity__c);
                                        objStock2.Freeze_Quantity__c = objStock2.Freeze_Quantity__c + intCountWareHouseQuantity;
                                        mapIdRelatedStock.put(objStock2.Id,objStock2);
                                        isStockAvailableBothWareHouse = true;
                                    }
                                    else{
                                        isStockAvailableBothWareHouse = false;
                                    }
                                }
                            }
                            
                            else 
                            {
                                System.debug('objSO.Ware_House__c---else---- ');
                                Stock__c objStock2 = new stock__c();
                                objStock2 = mapIdRelatedStock.get(mapWareHouseProductbasedStockId.get(strwareHouseDifferent+'-'+objSOI.Product_Part__c));
                                if(objStock2.Total_Unbooked_Quantity__c > objSOI.Quantity__c)
                                {
                                    objStock2.Freeze_Quantity__c = objStock2.Freeze_Quantity__c + objSOI.Quantity__c;
                                    mapIdRelatedStock.put(objStock2.Id,objStock2);
                                    isStockAvailableBothWareHouse = true;
                                }
                                else{
                                        isStockAvailableBothWareHouse = false;
                                    }
                            }
                        }
                    }
                    system.debug('-----isStockAvailableBothWareHouse---'+isStockAvailableBothWareHouse );
                     if(!isStockAvailableBothWareHouse){
                                mapIdRelatedStock = mapIdRelatedStockClone;
                                objSO.addError('Stock is not available.');
                            }
                }
            }
            if(mapIdRelatedStock.size()>0)
                update mapIdRelatedStock.values();
        }
    }
}