force-app/main/default/objects/Packing_List__c/Packing_List__c.object-meta.xml
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Packing List No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Packing Lists</relationshipLabel>
    <relationshipName>Packing_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List__c/fields/Packing_List_Number__c.field-meta.xml
<CustomField>
    <fullName>Packing_List_Number__c</fullName>
    <formula>if( text( Delivery_Note__r.Sales_Order__r.Ware_House__r.City__c) == &apos;Kolkata&apos;, &apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PKL&apos;+RIGHT( Name , LEN(Name) - 4),if( text(Delivery_Note__r.Sales_Order__r.Ware_House__r.City__c) == &apos;Gurugram&apos;, &apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PKL&apos;+RIGHT( Name , LEN(Name) - 4),&apos;Please select Place of Supply from SO.&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Packing List Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/Packing_List_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>DC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Packing_List__c.field-meta.xml
<CustomField>
    <fullName>Packing_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packing List</label>
    <referenceTo>Packing_List__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Part_No__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_No__c.field-meta.xml
<CustomField>
    <fullName>Part_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part No.</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pdf_Header__mdt/Pdf_Header__mdt.object-meta.xml
<CustomObject>
    <label>Pdf Header</label>
    <pluralLabel>Pdf Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pdf_Header__mdt/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kolkata</fullName>
                <default>true</default>
                <label>Kolkata</label>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/GSTIN_No__c.field-meta.xml
<CustomField>
    <fullName>GSTIN_No__c</fullName>
    <label>GSTIN No.</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Shipping Account Address)</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Shipping_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Code__c</fullName>
    <label>Shipping State Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Delivery Note</relationshipLabel>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping  Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes (Shipping  Account)</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/GSTIN_No__c.field-meta.xml
<CustomField>
    <fullName>GSTIN_No__c</fullName>
    <label>GSTIN No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackingListPDFController.cls
public class PackingListPDFController
{
    public Sales_Order__c objSO{get;set;}
    public Sales_Order_Dispatch_Delivery_Note__c objSODN{get;set;}
    public Packing_List__c objPck{get;set;}
    public list<Packing_List_Line_Item__c> Litem{get;set;}
      public Pdf_Header__mdt pdfheader{get;set;}
    public contact con{get;set;}
    public Account acc{get;set;}
    public Account shippingAcc{get;set;}
    
    public string strBillingAddress{get;set;}
    public string strShippingAddress{get;set;}
    
    public string strBillingState{get;set;}
    public string strBillingCode{get;set;}
    public string strShippingState{get;set;}
    public string strShippingCode{get;set;}
    
    public PackingListPDFController(ApexPages.StandardController controller)      
    {
        objPck = new Packing_List__c();
        Litem=new list<Packing_List_Line_Item__c>();
        objSO=new Sales_Order__c();
        objSODN=new Sales_Order_Dispatch_Delivery_Note__c();
        con=new contact();
        Acc=new Account();
        
         pdfheader=new Pdf_Header__mdt();
        
        id queryString = ApexPages.currentPage().getParameters().get('id');
        
        List<String> lstSalesOrderField = UtilityClass.getAllFields('Sales_Order__c');
        List<String> lstDNField = UtilityClass.getAllFields('Sales_Order_Dispatch_Delivery_Note__c');
        List<String> lstDNLIField = UtilityClass.getAllFields('Packing_List_Line_Item__c');
        List<String> lstPck = UtilityClass.getAllFields('Packing_List__c');
      
        String strpckg = 'Select ' +String.Join(lstPck, ',')+' '+ ',Delivery_Note__r.Sales_Order__r.Ware_House__r.Branch__c  From Packing_List__c where Id =: queryString';
        List<Packing_List__c> lstPL =  Database.query(strpckg);
        if(lstPL.size() > 0 && lstPL[0] != null)
            objPck = lstPL[0];
            
          ApexPages.currentPage().getHeaders().put('content-disposition', 'filename=' +' Package List - '+objPck.Packing_List_Number__c+'.PDF');
                system.debug('strfileName '+' Package List - '+objPck.Packing_List_Number__c);  
        id striPckdn=   objPck.Delivery_Note__c;
        
        String strSalesOrderQuery = 'Select ' +String.Join(lstDNField, ',')+' '+ ' From Sales_Order_Dispatch_Delivery_Note__c where Id =: striPckdn';
        
        String strSalesOrderItemQuery = 'Select ' +String.Join(lstDNLIField, ',')+ ',Part_No__r.Name,Part_No__r.Part_Name__c,Part_No__r.uom__c,Part_No__r.Specification__c From Packing_List_Line_Item__c where Packing_List__c =: queryString';
        
       string branch = objPck.Delivery_Note__r.Sales_Order__r.Ware_House__r.Branch__c ;
            List<String> pdfheaderField = UtilityClass.getAllFields('Pdf_Header__mdt');
            String pdfHeaderQuery = 'Select ' +String.Join(pdfheaderField, ',')+ ' From Pdf_Header__mdt WHERE Branch__c =:branch Order by Effected_Date__c ASC LIMIT 1';
            pdfheader =  Database.query(pdfHeaderQuery);
        
       List<Sales_Order_Dispatch_Delivery_Note__c> lstDN =  Database.query(strSalesOrderQuery);
       if(lstDN.size() > 0 && lstDN[0] != null)
            objSODN = lstDN[0];
            
        id soId = objSODN.Sales_Order__c;
            
        String strSalesOrder = 'Select ' +String.Join(lstSalesOrderField, ',')+' '+ ' From Sales_Order__c where Id =: soId';
    
            
        list<Sales_Order__c> lstSO = new list<Sales_Order__c>();    
        lstSO = Database.query(strSalesOrder);
        if(lstSO.size()>0 && lstSO[0] != null)
            objSO = lstSO[0];
       
       Litem =  Database.query(strSalesOrderItemQuery);
        list<Account> acclist = [select id,GSTIN_No__c,BillingCity,BillingCountry,BillingState,BillingStreet,BillingAddress,BillingPostalCode,ShippingCountry,
             ShippingCity,ShippingPostalCode,ShippingStreet,ShippingState,ShippingAddress, name,Billing_State_Code__c,Shipping_State_Code__c from Account where id =:objSO.Customer_Name__c];
       if(!acclist.isempty())
        Acc= acclist[0];
        list<contact> conlist = [select id,Name,Email,MobilePhone,Accountid from contact where Accountid=:Acc.Id limit 1];
            if(!conlist.isempty())
            con = conlist[0];
        system.debug('contact'+con.id);
        
        strBillingAddress = '';
        strBillingAddress = Acc?.BillingStreet;
        if(strBillingAddress != null && strBillingAddress !='' && Acc.BillingCity != null && Acc.BillingCity !='')
            strBillingAddress = strBillingAddress+', '+Acc.BillingCity;
        else if(Acc.BillingCity != null && Acc.BillingCity !='')
            strBillingAddress = Acc.BillingCity;
            
        if(strBillingAddress != null && strBillingAddress !='' && Acc.BillingState != null && Acc.BillingState !='')
            strBillingAddress = strBillingAddress+', '+Acc.BillingState ;
        else if(Acc.BillingState != null && Acc.BillingState !='')
            strBillingAddress = Acc.BillingState;
        
        if(strBillingAddress != null && strBillingAddress !='' && Acc.BillingPostalCode != null && Acc.BillingPostalCode !='')
            strBillingAddress = strBillingAddress+', '+Acc?.BillingPostalCode  ;
        else if(Acc.BillingPostalCode != null && Acc.BillingPostalCode !='')
            strBillingAddress = Acc.BillingPostalCode ;
            
        if(strBillingAddress != null && strBillingAddress !='' && Acc.BillingCountry != null && Acc.BillingCountry !='')
            strBillingAddress = strBillingAddress+', '+Acc.BillingCountry  ;
        else if(Acc.BillingCountry != null && Acc.BillingCountry !='')
            strBillingAddress = Acc.BillingCountry ;
        
        
        /*
        Billing State And Billing Code, Shipping State and Shipping Code
        */
        shippingAcc = new Account();
        shippingAcc = [select id ,GSTIN_No__c,BillingCity,BillingCountry,BillingState,BillingStreet,BillingAddress,BillingPostalCode,ShippingCountry,
             ShippingCity,ShippingPostalCode,ShippingStreet,ShippingState,ShippingAddress,
                       name,Billing_State_Code__c,Shipping_State_Code__c from Account where id =:objSODN.Shipping_Account__c];
        
        strBillingState = '';
        strBillingCode = '';
        strShippingState = '';
        strShippingCode = '';
        
        strBillingState = shippingAcc?.BillingState ;
        strBillingCode = shippingAcc?.Billing_State_Code__c ;
        
        strShippingAddress = '';
        strShippingAddress = shippingAcc?.ShippingCity;
        if(strShippingAddress != null && strShippingAddress !='' && shippingAcc.ShippingCity != null && shippingAcc.ShippingCity !='')
            strShippingAddress = strShippingAddress+', '+shippingAcc.ShippingCity;
        else if(shippingAcc.ShippingCity != null && shippingAcc.ShippingCity != '')
            strShippingAddress = shippingAcc.ShippingCity;
            
        if(strShippingAddress != null && strShippingAddress !='' && shippingAcc.ShippingState != null && shippingAcc.ShippingState != '')
            strShippingAddress = strShippingAddress+', '+shippingAcc?.ShippingState ;
        else if(shippingAcc.ShippingState != null && shippingAcc.ShippingState != '')
            strShippingAddress = shippingAcc.ShippingState;
        
        if(strShippingAddress != null && strShippingAddress !='' && shippingAcc.ShippingPostalCode != null && shippingAcc.ShippingPostalCode != '')
            strShippingAddress = strShippingAddress+', '+shippingAcc.ShippingPostalCode  ;
        else if(shippingAcc.ShippingPostalCode != null && shippingAcc.ShippingPostalCode != '')
            strShippingAddress = shippingAcc.ShippingPostalCode ;
            
        if(strShippingAddress != null && strShippingAddress !='' && shippingAcc.ShippingCountry != null && shippingAcc.ShippingCountry != '')
            strShippingAddress = strShippingAddress+', '+shippingAcc.ShippingCountry  ;
        else if(shippingAcc.ShippingCountry != null && shippingAcc.ShippingCountry != '')
            strShippingAddress = shippingAcc.ShippingCountry ; 
        
            strShippingState = shippingAcc?.ShippingState;
            strShippingCode = shippingAcc?.Shipping_State_Code__c;
        
        if(strShippingAddress == null || strShippingAddress =='')
        {
            strShippingAddress = strBillingAddress;
            strShippingState = Acc?.BillingState;
            strShippingCode = Acc?.Billing_State_Code__c;
        }
        
    }  
    
}