force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Customer_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comments__c</fullName>
    <label>Customer Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/ESN__c.field-meta.xml
<CustomField>
    <fullName>ESN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ESN</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/showServiceReqCMP__c.field-meta.xml
<CustomField>
    <fullName>showServiceReqCMP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>showServiceReqCMP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Parts Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailCtrl.cls
global class SendEmailCtrl
{
    public static string strResponse = '';
    
    @AuraEnabled
    public static string sendEMail(String strRecordId) 
    {
        ResponseWrapper objWrap = new ResponseWrapper();
        objWrap.success = true;
        objWrap.errorMessage = '';
        try
        {
            if(strRecordId != null && strRecordId != '')
            {
                list<EmailMessage> lstEM = new list<EmailMessage>();
                list<Service_Request__c> lstSR = new list<Service_Request__c>();
                lstSR = [Select Id, ESN__c, Contact_Person_Name__c, Customer_Email__c ,Contact_Person_Name__r.Name, Contact_Person_Name__r.Email,Customer_Comments__c,Status__c, showServiceReqCMP__c from Service_Request__c where Status__c ='Closed' AND Id =: strRecordId];
                if(lstSR.size()>0)
                {
                   EmailTemplate etFback = [SELECT Id,HtmlValue,subject,Body,DeveloperName FROM EmailTemplate where DeveloperName = 'FeedBack_Form'];
                    List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                    system.debug('...lstSR[0].Customer_Comments__c..'+lstSR[0].Customer_Comments__c);
                    If(lstSR[0].showServiceReqCMP__c )
                    {
                        objWrap.success = false;
                        objWrap.errorMessage = 'Customer comment already submitted.';
                    }
                    else
                    {
                        if(lstSR[0].Contact_Person_Name__c != null && lstSR[0].Contact_Person_Name__r.Email != null)
                        {
                            list<string> strContactsEmail= new list<string>();
                            strContactsEmail.add(lstSR[0].Contact_Person_Name__r.Email);
                            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                            string strBody = etFback.HtmlValue;
                            string strSubject = etFback.subject;
                            strBody = strBody.replace('#CustomerName', lstSR[0].Contact_Person_Name__r.Name);
                            strBody = strBody.replace('#ID', lstSR[0].Id);
                            email.setToAddresses(strContactsEmail);
                            email.setSubject(strSubject);
                            email.setHtmlBody(strBody);
                            mails.add(email);  
                            
                            EmailMessage objEM = new EmailMessage();
                            objEM.RelatedToId = lstSR[0].Id;
                            objEM.Status = '3';
                            objEM.Subject = 'Sent Feedback Form.';
                            if(lstSR[0].Customer_Email__c != null)
                                objEM.toAddress = lstSR[0].Contact_Person_Name__r.Email;
                            lstEM .add(objEM);
                        }
                        else
                        {
                            objWrap.success = false;
                            objWrap.errorMessage = 'Contact person not have an email.';
                        }
                    }
                    
                     if(mails.size()>0)
                        Messaging.sendEmail(mails);
                       
                     if(lstEM.size()>0)
                         insert lstEM;   
                }
                else
                {
                   objWrap.success = false;
                   objWrap.errorMessage = 'Service Request is not closed.'; 
                }
            }
            else
            {
                objWrap.success = false;
                objWrap.errorMessage = 'Invalid record id.';
            }
        }
        catch(Exception e)
        {
            objWrap.success = false;
            objWrap.errorMessage = ''+e.getMessage();
        } 
        return Json.serialize(objWrap);
    }
    
    public class ResponseWrapper{
        public boolean success;
        public string errorMessage;
    }
}