force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Complaint_Description__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Description__c</fullName>
    <label>Complaint Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/isServiceReqCreatedByEmail__c.field-meta.xml
<CustomField>
    <fullName>isServiceReqCreatedByEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Service Request Created By Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Issue_Reported__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reported__c</fullName>
    <label>Issue Reported</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Parts Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateServiceRequest.cls
global class CreateServiceRequest implements Messaging.InboundEmailHandler 
{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email,
    Messaging.InboundEnvelope envelope) 
    {
        System.debug('result#########'+email);
        System.debug('envelope#######'+envelope);
        
        List<Group> lstgroup = [select id, name, type from group where type = 'queue' AND name = 'Service Request Queue'];
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        System.debug('############'+result);
        Service_Request__c objServReq = new Service_Request__c();
        objServReq.Status__c = 'New';
        objServReq.isServiceReqCreatedByEmail__c = true;
        objServReq.Issue_Reported__c = email.subject;
        objServReq.Complaint_Description__c = email.plainTextBody;
        objServReq.OwnerId = lstgroup[0].Id;
        insert objServReq;
        
        // Save attachments, if any
        if(email.textAttachments != null)
            for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
                Attachment attachment = new Attachment();
                
                attachment.Name = tAttachment.fileName;
                attachment.Body = Blob.valueOf(tAttachment.body);
                attachment.ParentId = objServReq.Id;
                insert attachment;
            }
        
        //Save any Binary Attachment
        if(email.binaryAttachments != null)
            for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                Attachment attachment = new Attachment();
                
                attachment.Name = bAttachment.fileName;
                attachment.Body = bAttachment.body;
                attachment.ParentId = objServReq.Id;
                insert attachment;
            }

    result.success = true;
        return result;
    }
}