force-app/main/default/objects/MRN__c/MRN__c.object-meta.xml
<CustomObject>
    <label>MRN</label>
    <nameField>
        <displayFormat>MRN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN__c/fields/MRN_Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>MRN_Delivery_Type__c</fullName>
    <label>MRN Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/MRN_Type__c.field-meta.xml
<CustomField>
    <fullName>MRN_Type__c</fullName>
    <label>MRN Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Return</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>MRN</relationshipLabel>
    <relationshipName>MRN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/MRN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>MRN Line Item</label>
    <nameField>
        <displayFormat>MLN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN_Line_Item__c/fields/Landed_Cost_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Landed_Cost_Unit_Rate__c</fullName>
    <formula>Total_Landed_Amount__c/ Bill_QTY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Landed Cost/Unit Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>MRN</label>
    <referenceTo>MRN__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock__c.Product_Part__c</field>
            <operation>equals</operation>
            <valueField>$Source.Part_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Ware_House_Formula__c.field-meta.xml
<CustomField>
    <fullName>Ware_House_Formula__c</fullName>
    <formula>CASESAFEID(MRN__r.Ware_House__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ware House Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/Stock_Landed_Amount__c.object-meta.xml
<CustomObject>
    <label>Stock Landed Amount</label>
    <nameField>
        <displayFormat>SLA-{000000}</displayFormat>
        <label>Stock Landed Amount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Landed Amount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/MRN_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>MRN_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRN Line Item</label>
    <referenceTo>MRN_Line_Item__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MRNLineItemHelper.cls
public class MRNLineItemHelper {
   public static void createStockLandedAmount(List<MRN_Line_Item__c> triggerNew, Map<Id, MRN_Line_Item__c> oldMapMRNLI)
    {
        set<string> setOfProductId = new set<string>();
        set<string> setOfWarehouseId = new set<string>();
        set<string> setOfMRNLineItemId = new set<string>();
        
        set<string> setOfMRNLineItemIdLandedAmount = new set<string>();
        for(MRN_Line_Item__c objMRNLI : triggerNew)
        {
            setOfMRNLineItemId.add(objMRNLI.Id);
            if(objMRNLI.Part_Number__c != null)
                setOfProductId.add(objMRNLI.Part_Number__c);
            if(objMRNLI.Ware_House_Formula__c != null)
                setOfWarehouseId.add(objMRNLI.Ware_House_Formula__c);
        }
        if(setOfMRNLineItemId.size()>0)
        {
            map<string,string> mapProductWareHouseBaseStock = new map<string,string>();
            for(Stock__c objStock : [select Id,Ware_House__c,Product_Part__c from Stock__c where Ware_House__c IN: setOfWarehouseId and Product_Part__c IN: setOfProductId])
            {
                mapProductWareHouseBaseStock.put(objStock.Product_Part__c+'-'+objStock.Ware_House__c,objStock.Id);
            }
            
            system.debug('...mapProductWareHouseBaseStock..'+mapProductWareHouseBaseStock);
            
            list<Stock_Landed_Amount__c> lstOfSLA = new list<Stock_Landed_Amount__c>();
            for(MRN_Line_Item__c objMRNLI : [Select id, Name, Ware_House_Formula__c, Part_Number__c, Part_Number__r.Name, Landed_Cost_Unit_Rate__c, MRN__c, MRN__r.Ware_House__c, MRN__r.MRN_Type__c,MRN__r.MRN_Delivery_Type__c from MRN_Line_Item__c where id IN: setOfMRNLineItemId and (MRN__r.MRN_Type__c ='Purchase Order' OR MRN__r.MRN_Type__c ='Direct') ])
            {
            system.debug('...str..'+objMRNLI.Part_Number__c+'-'+objMRNLI.MRN__r.Ware_House__c);
                if(mapProductWareHouseBaseStock.containskey(objMRNLI.Part_Number__c+'-'+objMRNLI.MRN__r.Ware_House__c) && mapProductWareHouseBaseStock.get(objMRNLI.Part_Number__c+'-'+objMRNLI.MRN__r.Ware_House__c) != null) 
                {
                    Stock_Landed_Amount__c objSLA = new Stock_Landed_Amount__c();
                    objSLA.Ware_House__c = objMRNLI.Ware_House_Formula__c;
                    objSLA.Product_Part__c = objMRNLI.Part_Number__c;
                    objSLA.Stock__c = mapProductWareHouseBaseStock.get(objMRNLI.Part_Number__c+'-'+objMRNLI.Ware_House_Formula__c);
                    objSLA.MRN_Line_Item__c = objMRNLI.Id;
                    lstOfSLA.add(objSLA);
                }
            }
            if(lstOfSLA.size()>0)
                insert lstOfSLA;
        }
    }
}