force-app/main/default/objects/MRN__c/MRN__c.object-meta.xml
<CustomObject>
    <label>MRN</label>
    <nameField>
        <displayFormat>MRN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN__c/fields/MRN_Type__c.field-meta.xml
<CustomField>
    <fullName>MRN_Type__c</fullName>
    <label>MRN Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Return</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>MRN</relationshipLabel>
    <relationshipName>MRN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/MRN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>MRN Line Item</label>
    <nameField>
        <displayFormat>MLN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN_Line_Item__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>BAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>MRN</label>
    <referenceTo>MRN__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Received_QTY__c.field-meta.xml
<CustomField>
    <fullName>Received_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Stock__c.Product_Part__c</field>
            <operation>equals</operation>
            <valueField>$Source.Part_Number__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_In__c.field-meta.xml
<CustomField>
    <fullName>Product_In__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Out__c.field-meta.xml
<CustomField>
    <fullName>Product_Out__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Stock_Quantity_Update_onMRN_Handler.cls
public class Stock_Quantity_Update_onMRN_Handler {
    public static void updatestock(List<mrn__c> triggernew,map<Id,mrn__c> oldMap){
        Set<id> mrnIdSet = new Set<id>();
        Set<id> setProductId = new Set<id>();
        list<MRN_Line_Item__c> MrnLineItemList = new list<MRN_Line_Item__c>();
        Map<id,stock__c> stockmap = new Map<id,stock__c>(); 
        list<stock__c> stocklist = new list<stock__c>();
        for(mrn__c mrn : triggernew){ 
            if(mrn.Stage__c =='Received' && oldMap.get(mrn.Id).Stage__c != mrn.Stage__c){ 
                mrnIdSet.add(mrn.id);
                System.debug('mrnid------ '+mrn.id);
            }       
        }
        
        if(!mrnIdSet.isempty()) 
        {
            MrnLineItemList = [SELECT Id,MRN__c,MRN__r.MRN_Type__c,MRN__r.Ware_House__c,Part_Number__c,Stock__c,Condition__c,Received_QTY__c,Bill_QTY__c  FROM MRN_Line_Item__c where MRN__c IN: mrnIdSet];
            if(!MrnLineItemList.isempty()) 
            { 
                System.debug('MrnLineItemList------ '+MrnLineItemList.size());
                for(MRN_Line_Item__c mli :MrnLineItemList) {
                    setProductId.add(mli.Part_Number__c);
                }
                
                map<string,Stock__c> mapIdRelatedStock = new map<string,Stock__c>();
                map<string, Stock__c> mapWareHouseProductbasedQuantity = new map<string, Stock__c>();
                for(Stock__c objStock : [select id,Name,Product_Part__c,Quantity__c,Ware_House__c,Product_Out__c,Product_IN__c  from Stock__c where Product_Part__c IN: setProductId])
                {
                    mapWareHouseProductbasedQuantity.put(objStock.Ware_House__c+'-'+objStock.Product_Part__c,objStock);
                    mapIdRelatedStock.put(objStock.Id,objStock);
                }
                
                if(!setProductId.isempty()) 
                {
                    for(MRN_Line_Item__c mli : MrnLineItemList){
                        Stock__c objStock = new Stock__c();
                        
                        if(mapWareHouseProductbasedQuantity.get(mli.MRN__r.Ware_House__c+'-'+mli.Part_Number__c) != null){
                            objStock = mapWareHouseProductbasedQuantity.get(mli.MRN__r.Ware_House__c+'-'+mli.Part_Number__c);
                            Decimal stockamount =0;
                            System.debug('objStock------ '+objStock);
                            if(objStock.Product_IN__c !=null){
                                stockamount=objStock.Product_IN__c;
                            }
                            if(mli.MRN__r.MRN_Type__c=='Sales Return'){
                                if(mli.Received_QTY__c!= null){
                                    objStock.Product_IN__c = objStock.Product_IN__c+mli.Received_QTY__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);}
                            }
                            else{
                                if(mli.Bill_QTY__c!= null){
                                    objStock.Product_IN__c = objStock.Product_IN__c+mli.Received_QTY__c;
                                    mapIdRelatedStock.put(objStock.Id,objStock);}
                            }
                        }
                        
                    }
                }
                if(!mapIdRelatedStock.isempty()) 
                    Update mapIdRelatedStock.values();
            }
        }
    }    
}