force-app/main/default/objects/Safety_rules__c/Safety_rules__c.object-meta.xml
<CustomObject>
    <label>Safety Rule</label>
    <nameField>
        <displayFormat>Rules-{0000}</displayFormat>
        <label>Safety Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safety Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Safety_rules__c/fields/Breakdown_equipment__c.field-meta.xml
<CustomField>
    <fullName>Breakdown_equipment__c</fullName>
    <description>Is breakdown equipment in a safe accessible location/ Clear workspace with easy emergency exit?</description>
    <label>Breakdown equipment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Electrical_hazard__c.field-meta.xml
<CustomField>
    <fullName>Electrical_hazard__c</fullName>
    <description>No electrical hazard or live exposed cables/switches/overhead</description>
    <label>Electrical hazard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Fire_Hazard__c.field-meta.xml
<CustomField>
    <fullName>Fire_Hazard__c</fullName>
    <description>Any fire hazard or flammable/chemical liquids in open/exposed manner?</description>
    <label>Fire Hazard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/General_Housekeeping__c.field-meta.xml
<CustomField>
    <fullName>General_Housekeeping__c</fullName>
    <description>General Housekeeping/lighting/slippery floor/stacking of scrap/items handling risk?</description>
    <label>General Housekeeping</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Other_Safety_Hazard__c.field-meta.xml
<CustomField>
    <fullName>Other_Safety_Hazard__c</fullName>
    <description>Any other Safety Hazard?</description>
    <label>Other Safety Hazard</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Personal_Protection_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Personal_Protection_Equipment__c</fullName>
    <description>Confirm Personal Protection Equipments in use (PPE) - Safety shoes/Helmets/Ear muffs/Eye Glass/Gloves/Reflectors/Belts as applicable?</description>
    <label>Personal Protection Equipment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Safety_rules__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipName>Safety_rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SafetyRuleController.cls
public class SafetyRuleController {
    
    @AuraEnabled 
    public static string saveSafetyRules(string ids,string Radiobutton1,string Radiobutton2,string Radiobutton3,string Radiobutton4,string Radiobutton5,string otherSafety){
        wrapper objwrap = new wrapper();
        try{
            Safety_rules__c srObj=new Safety_rules__c();
            srObj.Breakdown_equipment__c=Radiobutton2;
            srObj.Electrical_hazard__c=Radiobutton3;
            srObj.Service_Request__c=ids;
            srObj.Fire_Hazard__c=Radiobutton4;
            srObj.General_Housekeeping__c=Radiobutton5;
            srObj.Personal_Protection_Equipment__c=Radiobutton1;
            srObj.Other_Safety_Hazard__c=otherSafety;
            insert srObj;
                }
        catch(Exception ex){
            objwrap.success = false;
            objwrap.ErrorMessage = ex.getMessage();
        }
        return 'Success';
    }
    
    public class wrapper{
        public boolean success;
        public boolean feedAlready;
        public String SuccessMessage;
        public String ErrorMessage;
        
    }
}