force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/ConvertedAcconutId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAcconutId__c</fullName>
    <label>ConvertedAcconutId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/ConvertedContactId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedContactId__c</fullName>
    <label>ConvertedContactId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/ConvertedOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ConvertedOpportunityId__c</fullName>
    <label>ConvertedOpportunityId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/isconverted__c.field-meta.xml
<CustomField>
    <fullName>isconverted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isconverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.OEM_Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.isPrimary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/OEM_Customer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <label>Enquiry Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Proposal/Quote</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
                <isActive>false</isActive>
                <label>Discovery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Parts</fullName>
        <isActive>false</isActive>
        <label>Parts</label>
    </customValue>
    <customValue>
        <fullName>Engines</fullName>
        <isActive>false</isActive>
        <label>Engines</label>
    </customValue>
    <masterLabel>Lead Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/clsConvertLeadTest.cls
@isTest
public class clsConvertLeadTest 
{
    public static testMethod void firstMethod(){
        
        //insert Lead
        List<Lead__c> ldLst = new List<Lead__c>();
        Lead__c ld = new Lead__c();
        ld.Salutation__c = 'Mr.';
        ld.Name = 'TestedContact0021';		//lastName
        ld.Lead_Type__c = 'Sales';
        ld.Mobile__c = '9485893345';
        ld.Email__c = 'test@gmail.com';
        ld.Company__c = 'Tested Account1 Pvt. Ltd.';
        
        insert ld;
        System.debug('leadId---- '+ld.Id);
        ldLst.add(ld);
        System.debug('insertedLeadId----- '+ld.Id);
        clsUtility.testDataCustomSetting();
        // clsUtility.testDataAccountContact(20,20,true);
        String strRecordTypeId = [SELECT Id,DeveloperName,Name,SobjectType FROM RecordType WHERE SobjectType='Account' and DeveloperName = 'Customer'].Id;
        System.debug('strRecordTypeId----- '+strRecordTypeId);
        Account acc = New Account();
        acc.RecordTypeId = strRecordTypeId;
        acc.Name = ld.Company__c;
        acc.PAN_NO__c = 'ghtid8739I';
        acc.Type = 'Customer';
        acc.Print_Name__c = ld.Company__c;
        
        insert acc;
        System.debug('accId--- '+acc.Id);
        
        //insert WareHouse
        Ware_House__c wHouse = new Ware_House__c();
        wHouse.Name = 'Kolkata Warehouse';
        wHouse.Branch__c='Kolkata';
        insert wHouse; 
        
        // insert Contact
        Contact c = new Contact();
        c.AccountId= acc.id; 
        c.FirstName = 'TestedFirstName';
        c.LastName = 'TestedContact0021';
        insert c;
        
        // insert Opportunity
        Opportunity__c o = new Opportunity__c();
        o.Contact_Person__c = c.Id;
        o.OEM_Customer__c = acc.Id;
        o.Stage__c = 'New';
        o.Opportunity_Close_Date__c = date.today();
        o.Ware_House__c = wHouse.Id;
        insert o;
        ld.isconverted__c = true;
        ld.ConvertedAcconutId__c = acc.id;
        ld.ConvertedContactId__c = c.Id;
        ld.ConvertedOpportunityId__c = o.Id;
        update ld;
               
        //insert wrapper
        clsConvertLead.mainWrapper mw = new clsConvertLead.mainWrapper(); 
        mw.lstLead = ldLst;
        mw.AccName = acc;
        mw.ConName = c;
        mw.OppName = o; 
        
        clsConvertLead.convertLead(ld.Id);
        String objName = acc.Id.getSObjectType().getDescribe().getName();
        String recordName = 'LeadAccountMap';
        clsConvertLead.insertRecord(recordName, ld.Id, objName, acc.Id, acc.Name, strRecordTypeId);
        clsConvertLead.insertRecord(recordName, ld.Id, objName, null , acc.Name, strRecordTypeId);
        String objNameCon = c.Id.getSObjectType().getDescribe().getName();
        String recordNameCon = 'LeadContactMap';
        clsConvertLead.insertRecord(recordNameCon, ld.Id, objNameCon, c.Id, acc.Id, null);
        Boolean CreateOpp = true;
        Boolean IsDeleteConverted = true;
        String strRecordType = 'Customer';
        clsConvertLead.saveconvertrecord(ld.Id, acc.Id, o.Id, null, true , true, acc.name, strRecordType);
        clsConvertLead.insertRecord(recordNameCon, Ld.Id, 'Contact', null, acc.Id, null);
        clsConvertLead.saveconvertrecord(ld.Id, acc.Id, o.Id, c.Id, CreateOpp, IsDeleteConverted, acc.name, strRecordType);
    }
    
    @isTest public static void secondMethod(){
        Lead__c ldS = new Lead__c();
        ldS.Salutation__c = 'Mr.';
        ldS.Name = 'TestedContact0022';		//lastName
        ldS.Lead_Type__c = 'Sales';
        ldS.Mobile__c = '9485893346';
        ldS.Email__c = 'tests@gmail.com';
        ldS.Company__c = 'Tested Account1 Pvt. Ltd.'; 
        insert ldS;
        
        //insert WareHouse
        Ware_House__c wHouse = new Ware_House__c();
        wHouse.Name = 'Kolkata Warehouse';
        wHouse.Branch__c='Kolkata';
        insert wHouse;
        
        clsUtility.testDataCustomSetting();
        String strRecordTypeId = [SELECT Id,DeveloperName,Name,SobjectType FROM RecordType WHERE SobjectType='Account' and DeveloperName = 'Customer'].Id;
        System.debug('strRecordTypeId----- '+strRecordTypeId);
        Account acc = New Account();
        acc.RecordTypeId = strRecordTypeId;
        acc.Name = ldS.Company__c;
        acc.PAN_NO__c = 'ghtid8739I';
        acc.Type = 'Customer';
        acc.Print_Name__c=ldS.Company__c;
        insert acc;
        System.debug('accId--- '+acc.Id);
        
        // insert Contact
        Contact c = new Contact();
        c.AccountId= acc.id; 
        c.FirstName = 'TestedFirstName';
        c.LastName = 'TestedContact0021';
        insert c;
        
        // insert Opportunity
        Opportunity__c o = new Opportunity__c();
        o.Contact_Person__c = c.Id;
        o.OEM_Customer__c = acc.Id;
        o.Stage__c = 'New';
        o.Opportunity_Close_Date__c = date.today();
        o.Ware_House__c = wHouse.Id;
        insert o;
        
        clsConvertLead.convertLead(ldS.Id);
        String recordNameCon = 'LeadContactMap';
        String strRecordType = 'Customer';
        clsConvertLead.saveconvertrecord(ldS.Id, acc.id, o.id, c.Id, true , false, acc.name, strRecordType);
        clsConvertLead.saveconvertrecord(ldS.Id, acc.id, null, c.Id, false , true, acc.name, strRecordType);
        clsConvertLead.saveconvertrecord(ldS.Id, null, o.Id, c.Id, true , true, acc.name, strRecordType);
        clsConvertLead.insertRecord(recordNameCon, LdS.Id, 'Account', null, acc.Name, strRecordType); 
    }
}