force-app/main/default/objects/Charges__c/Charges__c.object-meta.xml
<CustomObject>
    <label>Charges</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charges__c/fields/Charges__c.field-meta.xml
<CustomField>
    <fullName>Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charges</label>
    <referenceTo>Tax__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charges__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRN</label>
    <referenceTo>MRN__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charges__c/fields/MRN_Charge_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>MRN_Charge_Exchange_Rate__c</fullName>
    <formula>IF( AND( MRN__r.Total_Item_Amount__c &gt; 0, Total_Amount__c &gt; 0 , MRN__r.Exchange_Rate__c &gt; 0 ),((Total_Amount__c / MRN__r.Exchange_Rate__c) / MRN__r.Total_Item_Amount__c)*100 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRN Charge Exchange Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN__c/MRN__c.object-meta.xml
<CustomObject>
    <label>MRN</label>
    <nameField>
        <displayFormat>MRN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.OEM_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MRN</relationshipLabel>
    <relationshipName>MRN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Ex_Work_Value__c.field-meta.xml
<CustomField>
    <fullName>Ex_Work_Value__c</fullName>
    <label>Ex Work Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Exchange Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Freight__c.field-meta.xml
<CustomField>
    <fullName>Freight__c</fullName>
    <label>Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Freight_of_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Freight_of_Invoice__c</fullName>
    <formula>IF( AND( Freight__c  &gt; 0, Ex_Work_Value__c  &gt; 0) , Freight__c / Ex_Work_Value__c  , 0)*100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Freight % of Invoice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Insurance_of_BOE__c.field-meta.xml
<CustomField>
    <fullName>Insurance_of_BOE__c</fullName>
    <label>Insurance of BOE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.20</fullName>
            </value>
            <value>
                <fullName>1.125</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/Inv_Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Inv_Surcharge__c</fullName>
    <formula>IF( AND( Surcharge__c  &gt; 0,  Ex_Work_Value__c  &gt; 0) , Surcharge__c / Ex_Work_Value__c , 0)*100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inv Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN__c/fields/MRN_Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>MRN_Delivery_Type__c</fullName>
    <label>MRN Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRN__c/fields/OEM_Customer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OEM/Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MRN</relationshipLabel>
    <relationshipName>MRN</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/MRN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>MRN Line Item</label>
    <nameField>
        <displayFormat>MLN-{00000}</displayFormat>
        <label>MRN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MRN_Line_Item__c/fields/Assessable_Value_Including_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Assessable_Value_Including_Insurance__c</fullName>
    <formula>Total_Item_Value_in_INR__c*((100 + VALUE( TEXT(MRN__r.Insurance_of_BOE__c)))/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assessable Value (Including Insurance)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/CGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c *  CGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Custom_Duty_Amount__c.field-meta.xml
<CustomField>
    <fullName>Custom_Duty_Amount__c</fullName>
    <formula>((Assessable_Value_Including_Insurance__c * Duty_Rates__c)/100 )*(( 100 + Sur_Rate__c)/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Custom Duty Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>PO_Taxable_Amount_input__c *  GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/IGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c * IGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Item_Value_with_Freight_and_Surcharges__c.field-meta.xml
<CustomField>
    <fullName>Item_Value_with_Freight_and_Surcharges__c</fullName>
    <formula>Total_Amount_GBP__c + ( Total_Amount_GBP__c* MRN__r.Freight_of_Invoice__c )/100 + (Total_Amount_GBP__c* MRN__r.Inv_Surcharge__c )/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Value with Freight and Surcharges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>MRN</label>
    <referenceTo>MRN__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Part_Number__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>MRN Line Items</relationshipLabel>
    <relationshipName>MRN_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/PO_QTY__c.field-meta.xml
<CustomField>
    <fullName>PO_QTY__c</fullName>
    <label>PO QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Received_QTY__c.field-meta.xml
<CustomField>
    <fullName>Received_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/SGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c * SGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Short_QTY__c.field-meta.xml
<CustomField>
    <fullName>Short_QTY__c</fullName>
    <formula>if(ispickval( MRN__r.MRN_Type__c ,&apos;Sales Return&apos;),0,Bill_QTY__c -  Received_QTY__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Short QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Part Serial #</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Taxable_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Amount_Formula__c</fullName>
    <formula>Total_Amount__c -  Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Taxable_Value__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Taxable Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Total_Amount_GBP__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_GBP__c</fullName>
    <formula>Bill_QTY__c *  Item_Price_Unit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Item Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Total_For_Book_formula__c.field-meta.xml
<CustomField>
    <fullName>Total_For_Book_formula__c</fullName>
    <formula>GST_Amount__c +  PO_CGST_Amount__c  +  PO_IGST_Amount__c  +  PO_SGST_Amount__c  +  PO_Taxable_Amount_input__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total For Books</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Total_Item_Value_in_INR__c.field-meta.xml
<CustomField>
    <fullName>Total_Item_Value_in_INR__c</fullName>
    <formula>IF( ISPICKVAL( MRN__r.MRN_Delivery_Type__c , &apos;import&apos;) , Item_Value_with_Freight_and_Surcharges__c * MRN__r.Exchange_Rate__c,  Total_Amount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Item Value in INR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MRN_Line_Item__c/fields/Total_Landed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Landed_Amount__c</fullName>
    <formula>IF(  ISPICKVAL(MRN__r.MRN_Delivery_Type__c, &apos;Import&apos;)  , 
( Total_Item_Value_In_INR_input__c + Custom_Duty_Amount__c)+ (  Total_Amount_Input__c * MRN__r.Exchange_Rate__c *    MRN__r.dcCharges__c  )+ ( Total_Amount_Input__c * MRN__r.Exchange_Rate__c * MRN__r.clgCharges__c ),
 Total_Item_Value_In_INR_input__c +(Total_Item_Value_In_INR_input__c * MRN__r.Total_Charges_Percentage__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Landed Amount (INR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MrnPurchanseOrderExt.cls
public class MrnPurchanseOrderExt {
    public MRN__c objMrn {get;set;}
    public List<MRN_Line_Item__c> objMrnItemList {get;set;}
    public List<Charges__c>objChargesList{get;set;}
    public Decimal poQty{get;set;}
    public Decimal billQty{get;set;}
    public Decimal recQty{get;set;}
    public Decimal shortQty{get;set;}
    public Decimal subTotalItemAmount{get;set;}
    
    public Decimal subTotalWithFreightAndSurchargeAmount{get;set;}
    public Decimal totalWithFreightAndSurchargeAmount{get;set;}
    public Decimal subTotalItemValueInINR{get;set;}
    public Decimal totalItemValueInINR{get;set;}
    public Decimal subTotalAssessableValue{get;set;}
    public Decimal subTotalCustomDutyAmount{get;set;}
    public Decimal subTotalLandedAmountInInr{get;set;}
    public Decimal subTotalTaxableValue{get;set;}
    public Decimal subTotalGSTAmount{get;set;}
    public Decimal totalGSTAmount{get;set;}
    public Decimal subTotalBookAmount{get;set;}
    public Decimal totalBookAmount{get;set;}
    public Decimal totalMRNExchangeCharge{get;set;}
    public Decimal totalChargeSUM{get;set;}
    public String strAmount{get;set;}
    public Decimal subPoQty{get;set;}
    // For Domestic
    public Decimal totalCgstAmount{get;set;}
    public Decimal totalSgstAmount{get;set;}
    public Decimal totalIgstAmount{get;set;}
    public Decimal totalTaxValueAmount{get;set;}
    
    public ImportWrapper objIW{get;set;}
    
    
    public MrnPurchanseOrderExt(ApexPages.StandardController controller)      
    {
        String strId = ApexPages.currentPage().getParameters().get('id');
        system.debug('strId-----'+strId);
        if(String.isNotBlank(strId)){
            objMrnItemList = new List<MRN_Line_Item__c>();
            objChargesList = new List<Charges__c>();
            
            poQty=0; billQty=0; recQty=0; shortQty=0; subTotalItemAmount=0;
            subTotalWithFreightAndSurchargeAmount=0; totalWithFreightAndSurchargeAmount =0;
            subTotalItemValueInINR=0; totalItemValueInINR=0; subTotalAssessableValue=0;
            subTotalCustomDutyAmount=0; subTotalLandedAmountInInr=0; subTotalTaxableValue=0;
            subTotalGSTAmount=0; totalGSTAmount=0; subTotalBookAmount=0; totalBookAmount=0;
            totalCgstAmount=0;totalSgstAmount=0;totalIgstAmount=0;totalTaxValueAmount=0;
            totalMRNExchangeCharge = 0; strAmount='';totalChargeSUM =0;subPoQty=0;
            
            List<String> lstMrnField = UtilityClass.getAllFields('MRN__c');
            List<String> lstMrnItemField = UtilityClass.getAllFields('MRN_Line_Item__c');
            List<String> lstChargesField = UtilityClass.getAllFields('Charges__c');
            system.debug('lstChargesField'+lstChargesField);
            String strMrnQuery = 'Select OEM_Customer__r.ShippingStreet,OEM_Customer__r.ShippingCity, OEM_Customer__r.ShippingState, OEM_Customer__r.ShippingPostalCode, OEM_Customer__r.ShippingCountry, Contact_Name__r.Name, OEM_Customer__r.Name, OEM_Customer__r.BillingStreet,OEM_Customer__r.BillingCity, OEM_Customer__r.BillingState, OEM_Customer__r.BillingPostalCode, OEM_Customer__r.BillingCountry,OEM_Customer__r.Billing_State_Code__c,OEM_Customer__r.Shipping_State_Code__c,' +String.Join(lstMrnField, ',')+ ' From MRN__c where Id =: strId';
            String strMrnItemQuery = 'Select Part_Number__r.Name,Part_Number__r.Specification__c,Part_Number__r.Part_Name__c,' +String.Join(lstMrnItemField, ',')+ ' From MRN_Line_Item__c where MRN__c =: strId';
            String strChargesQuery = 'Select Charges__r.Name,' +String.Join(lstChargesField, ',')+ ' From Charges__c where MRN__c =: strId';
            List<MRN__c> lstPurchaseOrder =  Database.query(strMrnQuery);
            if(lstPurchaseOrder.size()>0){
                objMrn=lstPurchaseOrder[0];
                system.debug('......objMrn.MRN_Delivery_Type__c..'+objMrn.MRN_Delivery_Type__c);
                objIW = new ImportWrapper();
                if(objMrn.MRN_Delivery_Type__c=='Import'){
                objIW.TotalInvValue = objMrn.Ex_Work_Value__c?.setScale(2);
                    
                objIW.TotalInvValueInINR = (objMrn.Ex_Work_Value__c * objMrn.Exchange_Rate__c)?.setScale(2);
                    
                objIW.InvSurcharge = (objMrn.Inv_Surcharge__c*100)?.setScale(2);
                objIW.InvSurchargeInINR = (objMrn.Surcharge__c * objMrn.Exchange_Rate__c)?.setScale(2);
                objIW.InsuranceOfBOEInINR = objIW.TotalInvValue * decimal.valueOf(objMrn.Insurance_of_BOE__c) * objMrn.Exchange_Rate__c;
                objIW.InsuranceOfBOEInINR = objIW.InsuranceOfBOEInINR?.setScale(2);
                objIW.FreightOfInvoice = (objMrn.Freight_of_Invoice__c)?.setScale(2);
                objIW.FreightOfInvoiceInINR = (objMrn.Freight__c * objMrn.Exchange_Rate__c)?.setScale(2);
                }
                
            }
            objMrnItemList=Database.query(strMrnItemQuery);
            if(objMrnItemList.size()>0){
                for(MRN_Line_Item__c mrnObj:objMrnItemList){
                    if(mrnObj.Quantity__c !=null){
                        poQty += mrnObj.Quantity__c;
                    }
                    if(mrnObj.Bill_QTY__c !=null){
                        billQty+=mrnObj.Bill_QTY__c;
                    }
                    if(mrnObj.Received_QTY__c !=null){
                        recQty+=mrnObj.Received_QTY__c;
                    }
                    if(mrnObj.Short_QTY__c !=null){
                        shortQty+=mrnObj.Short_QTY__c;
                    }
                    if(mrnObj.PO_QTY__c !=null){
                        subPoQty+=mrnObj.PO_QTY__c;
                    }
                    
                    if(mrnObj.Total_Amount_GBP__c !=null){
                        subTotalItemAmount+=mrnObj.Total_Amount_GBP__c;
                    }
                    if(mrnObj.Item_Value_with_Freight_and_Surcharges__c !=null){
                        totalWithFreightAndSurchargeAmount+=mrnObj.Item_Value_with_Freight_and_Surcharges__c;
                        subTotalWithFreightAndSurchargeAmount+=mrnObj.Item_Value_with_Freight_and_Surcharges__c;
                    }
                    if(mrnObj.Total_Item_Value_in_INR__c !=null){
                        subTotalItemValueInINR+=mrnObj.Total_Item_Value_in_INR__c;
                        totalItemValueInINR+=mrnObj.Total_Item_Value_in_INR__c;
                    }
                    if(mrnObj.Assessable_Value_Including_Insurance__c !=null){
                        subTotalAssessableValue+=mrnObj.Assessable_Value_Including_Insurance__c;
                    }
                    if(mrnObj.Custom_Duty_Amount__c !=null){
                        subTotalCustomDutyAmount+=mrnObj.Custom_Duty_Amount__c;
                    }
                    if(mrnObj.Total_Landed_Amount__c !=null){
                        subTotalLandedAmountInInr+=mrnObj.Total_Landed_Amount__c;
                    }
                    if(mrnObj.Taxable_Amount_Formula__c !=null){
                        subTotalTaxableValue+=mrnObj.Taxable_Amount_Formula__c;
                    }
                    if(mrnObj.GST_Amount__c !=null){
                        subTotalGSTAmount+=mrnObj.GST_Amount__c;
                        totalGSTAmount+=mrnObj.GST_Amount__c;
                    }
                    if(mrnObj.Total_For_Book_formula__c !=null){
                        subTotalBookAmount+=mrnObj.Total_For_Book_formula__c;
                        System.debug('book '+mrnObj.Total_For_Book_formula__c);
                        System.debug('Sub '+subTotalBookAmount);
                        totalBookAmount+=mrnObj.Total_For_Book_formula__c;
                    }
                    
                    // For Domestic 
                    if(mrnObj.CGST_Amount_Formula__c !=null){
                        totalCgstAmount+=mrnObj.CGST_Amount_Formula__c;
                    } 
                    if(mrnObj.SGST_Amount_Formula__c !=null){
                        totalSgstAmount+=mrnObj.SGST_Amount_Formula__c;
                    } 
                    if(mrnObj.IGST_Amount_Formula__c !=null){
                        totalIgstAmount+=mrnObj.IGST_Amount_Formula__c;
                    } 
                    if(mrnObj.Taxable_Value__c !=null){
                        totalTaxValueAmount+=mrnObj.Taxable_Value__c;
                    } 
                }
                System.debug('Sub1'+subTotalBookAmount);
                subTotalBookAmount = subTotalBookAmount?.setScale(2);
                System.debug('Sub2'+subTotalBookAmount);
            }
            objChargesList =  Database.query(strChargesQuery);
            
            decimal totalBookedAmount = 0;
            totalBookedAmount = subTotalBookAmount;
            if(objChargesList.size()>0){
                for(Charges__c chr:objChargesList){
                    if(chr.MRN_Charge_Exchange_Rate__c > 0){
                        totalWithFreightAndSurchargeAmount+=chr.MRN_Charge_Exchange_Rate__c;
                        totalMRNExchangeCharge+= chr.MRN_Charge_Exchange_Rate__c;
                    }        
                    if(chr.Total_Amount__c > 0){
                        totalItemValueInINR+=chr.Total_Amount__c;
                        totalChargeSUM +=chr.Total_Amount__c;
                    }  
                    if(chr.Total_Amount__c > 0 && chr.GST__c > 0){
                        totalGSTAmount+=(chr.Total_Amount__c*chr.GST__c)/100;
                    }
                    if(objMrn.MRN_Delivery_Type__c == 'Import')
                            totalBookAmount+= totalGSTAmount + chr.Total_Amount__c;
                    
                    if(objMrn.MRN_Delivery_Type__c == 'Domestic')
                            totalBookAmount+= chr.CGST_Amount__c+ chr.SGST_Amount__c+ chr.IGST_Amount__c+ chr.Total_Amount__c;
                    
                    if(objMrn.MRN_Delivery_Type__c == 'Import' && chr.Net_Amount__c >0)
                    {
                        totalBookedAmount = totalBookedAmount+chr.Net_Amount__c;
                    }                       
                }
                
                totalBookAmount=totalBookAmount+lstPurchaseOrder[0]?.Less_Insurance__c;
                totalWithFreightAndSurchargeAmount= totalWithFreightAndSurchargeAmount?.setScale(2);
                totalItemValueInINR= totalItemValueInINR?.setScale(2);
                totalGSTAmount= totalGSTAmount?.setScale(2);
                totalBookAmount= totalBookAmount?.setScale(2);
                if(objMrn.MRN_Delivery_Type__c == 'Import'){
                    totalBookedAmount = totalBookedAmount+lstPurchaseOrder[0]?.Less_Insurance__c;
                    totalBookedAmount= totalBookedAmount?.setScale(2);
                    totalBookAmount = totalBookedAmount;
                }
            }            
        }
        if(totalBookAmount > 0)
            strAmount = UtilityClass.NoToWord(totalBookAmount.intValue());
    }
    
    public class ImportWrapper{
        
        //Related To Purchase Order (For Import)
        public Decimal TotalInvValue{get;set;}
        public Decimal TotalInvValueInINR{get;set;}
        public Decimal InvSurcharge{get;set;}
        public Decimal InvSurchargeInINR{get;set;}
        public Decimal InsuranceOfBOEInINR{get;set;}
        public Decimal FreightOfInvoice{get;set;}
        public Decimal FreightOfInvoiceInINR{get;set;}
        
        public ImportWrapper(){
            TotalInvValue = 0;
            TotalInvValueInINR = 0;
            InvSurcharge = 0;
            InvSurchargeInINR = 0;
            InsuranceOfBOEInINR = 0;
            FreightOfInvoice = 0;
            FreightOfInvoiceInINR = 0;
        }
    }
}