force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line Item</label>
    <referenceTo>Sales_Order_Line_Item__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>LI-{00}</displayFormat>
        <label>Sales Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Deliverd_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Deliverd_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deliverd Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeliverylineitemTriggerHelper.cls
public class DeliverylineitemTriggerHelper {
    
    public static void onInsertMethod(list<Delivery_Note_Line_Item__c> newSolList){
        map<id,Sales_Order_Line_Item__c> Solimap = new map<id,Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilistget = new list<Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilist = new list<Sales_Order_Line_Item__c>();
        set<string> soliIdSet = new set<string>();
        for(Delivery_Note_Line_Item__c dcln:newSolList){
            Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c();
            soli.id = dcln.Sales_Order_Line_Item__c;
            soli.Deliverd_Quantity__c = dcln.Quantity__c;
            Solimap.put(soli.id,soli);
            soliIdSet.add(soli.id);
        } 
        
        if(!soliIdSet.isempty())
            Solilistget = [Select id,Deliverd_Quantity__c,Quantity__c from Sales_Order_Line_Item__c where id in:soliIdSet];
        
        if(!Solilistget.isempty())
            for(Sales_Order_Line_Item__c solitem:Solilistget){
                if(Solimap.containsKey(solitem.id)){
                    solitem.id = solitem.id;
                    solitem.Deliverd_Quantity__c = Solimap.get(solitem.id).Deliverd_Quantity__c + solitem.Deliverd_Quantity__c;
                    
                    Solilist.add(solitem);
                }   
            } 
        
        if(!Solilist.isempty())
            update Solilist;
    }
    
    public static void onDeleteMethod(list<Delivery_Note_Line_Item__c> oldSolList){
        map<id,Sales_Order_Line_Item__c> Solimap = new map<id,Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilistget = new list<Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilist = new list<Sales_Order_Line_Item__c>();
        set<string> soliIdSet = new set<string>();
        for(Delivery_Note_Line_Item__c dcln:oldSolList){
            Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c();
            soli.id = dcln.Sales_Order_Line_Item__c;
            soli.Deliverd_Quantity__c = dcln.Quantity__c;
            Solimap.put(soli.id,soli);
            soliIdSet.add(soli.id);
        } 
        
        if(!soliIdSet.isempty())
            Solilistget = [Select id,Deliverd_Quantity__c from Sales_Order_Line_Item__c where id in:soliIdSet];
        
        if(!Solilistget.isempty())
            for(Sales_Order_Line_Item__c solitem:Solilistget){
                if(Solimap.containsKey(solitem.id)){
                    solitem.id = solitem.id;
                    if(Solimap.get(solitem.id).Deliverd_Quantity__c > solitem.Deliverd_Quantity__c)
                    solitem.Deliverd_Quantity__c = Solimap.get(solitem.id).Deliverd_Quantity__c - solitem.Deliverd_Quantity__c;
                    else
                    solitem.Deliverd_Quantity__c = solitem.Deliverd_Quantity__c -Solimap.get(solitem.id).Deliverd_Quantity__c;    
                    Solilist.add(solitem);
                }   
            } 
        
        if(!Solilist.isempty())
            update Solilist;
    }
    
    public static void onupdateMethod(list<Delivery_Note_Line_Item__c> newSolList, map<id,Delivery_Note_Line_Item__c> NewSolMap,  map<id,Delivery_Note_Line_Item__c> OldSolMap){
        map<id,Sales_Order_Line_Item__c> Solimap = new map<id,Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilistget = new list<Sales_Order_Line_Item__c>();
        list<Sales_Order_Line_Item__c> Solilist = new list<Sales_Order_Line_Item__c>();
        set<string> soliIdSet = new set<string>();
        for(Delivery_Note_Line_Item__c dcln:newSolList){
            if(NewSolMap.get(dcln.id).Quantity__c != OldSolMap.get(dcln.id).Quantity__c){
                Sales_Order_Line_Item__c soli = new Sales_Order_Line_Item__c();
                soli.id = dcln.Sales_Order_Line_Item__c;
                soli.Deliverd_Quantity__c = dcln.Quantity__c;
                Solimap.put(soli.id,soli);
                soliIdSet.add(soli.id);
            }
        } 
        
        if(!soliIdSet.isempty())
            Solilistget = [Select id,Deliverd_Quantity__c from Sales_Order_Line_Item__c where id in:soliIdSet];
        
        if(!Solilistget.isempty())
            for(Sales_Order_Line_Item__c solitem:Solilistget){
                if(Solimap.containsKey(solitem.id)){
                    solitem.id = solitem.id;
                    solitem.Deliverd_Quantity__c = Solimap.get(solitem.id).Deliverd_Quantity__c + solitem.Deliverd_Quantity__c;
                    Solilist.add(solitem);
                }   
            } 
        
        if(!Solilist.isempty())
            update Solilist;
    }
    
}