force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Dispatch_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Dispatch_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Dispatch (Delivery Note)</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DeliveryNoteHelper.cls
public class DeliveryNoteHelper 
{
    public static void delLineItems(list<Sales_Order_Dispatch_Delivery_Note__c> lstdn)
    {
        list<Delivery_Note_Line_Item__c> deldli= new list<Delivery_Note_Line_Item__c>();
       set<ID> sid = new set<ID>();
        for(Sales_Order_Dispatch_Delivery_Note__c dn : lstdn)
        {
                sid.add(dn.id);
            
        }
		system.debug('delNoteId-- '+ sid);
        list<Delivery_Note_Line_Item__c> dnli = [select id ,Sales_Order_Dispatch_Delivery_Note__c from Delivery_Note_Line_Item__c where Sales_Order_Dispatch_Delivery_Note__c =: sid];
        system.debug('inQuery----  '+ dnli.size());
        if(dnli.size() > 0 ){
		for(Delivery_Note_Line_Item__c dlItem : dnli){
		deldli.add(dlItem);
		}
		}
		System.debug('lstSizeItem--- '+deldli.size());
		if(deldli.size() > 0){
		system.debug('------DELETED====');
		delete deldli;
        
		}
        
    }
}