force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/HSN_Code__c.field-meta.xml
<CustomField>
    <fullName>HSN_Code__c</fullName>
    <label>HSN Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Dispatch_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Dispatch_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Dispatch (Delivery Note)</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List__c/Packing_List__c.object-meta.xml
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Packing List No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Packing Lists</relationshipLabel>
    <relationshipName>Packing_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/Packing_List_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>DC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Gross_Weight_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kgs__c</fullName>
    <label>Gross Weight (Kgs)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Height_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches_CMS__c</fullName>
    <label>Height (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Length_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Length_Inches_CMS__c</fullName>
    <label>Length(Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Packing_List__c.field-meta.xml
<CustomField>
    <fullName>Packing_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packing List</label>
    <referenceTo>Packing_List__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Width_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Width_Inches_CMS__c</fullName>
    <label>Width (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/List_Price_Standard_price__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Standard_price__c</fullName>
    <label>List Price /Standard price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.isPrimary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Shipping Account Address)</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Delivery Note</relationshipLabel>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping  Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes (Shipping  Account)</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UpsertPackingListTest.cls
/*
--------------------------------------------------------------------------------------
Version#     Date                           Author                    Description
--------------------------------------------------------------------------------------
1          17-06-2021                   santosh Rathour            Initial Version
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
2         23-06-2021                    Rameshwar                      Update
--------------------------------------------------------------------------------------
*/
@isTest
public class UpsertPackingListTest
{
    @isTest
    static void ValidateproductOnLoad()
    {
        
        
        clsUtility.testDataCustomSetting();
        
        //insert Account
        Account acc = New Account();
        acc.Name = 'Test Supplier';
        acc.Print_Name__c = 'test';
        acc.PAN_NO__c = 'ghtid8739I';
        acc.BillingCity = 'Noida';
        acc.BillingStreet ='NRF road';
        acc.Region__c = 'East';
        acc.BillingState= 'Uttar Pradesh';
        acc.BillingPostalCode='256314';
        acc.BillingCountry='India';
        acc.Billing_State_Code__c='09';	
        
        insert acc;
        System.debug('accId--- '+acc.Id); 
        
        // insert Contact
        Contact c = new Contact();
        c.AccountId= acc.id; 
        c.FirstName = 'TestedFirstName';
        c.LastName = 'TestedContact0021';
        c.isPrimary__c =true;
        insert c;
        
        //insert wareHouse
        Ware_House__c wHouse = new Ware_House__c();
        wHouse.Name = 'Kolkata Warehouse';
        insert wHouse;
        
        // insert SalesOrder
        Sales_Order__c sOrder = new Sales_Order__c();
        sOrder.Ware_House__c = wHouse.Id;
        sOrder.Contact_Person__c = c.id;
        sOrder.Customer_Name__c = acc.id;
        sOrder.Shipping_Account__c = acc.id;
        insert sOrder;
        System.debug('sOrder--- '+sOrder.Id); 
        
        //insert Delivery Note
        Sales_Order_Dispatch_Delivery_Note__c objdispatchnote = new Sales_Order_Dispatch_Delivery_Note__c();
        objdispatchnote.Sales_Order__c = sOrder.Id;        
        insert objdispatchnote;
        System.debug('objdispatchnote--- '+objdispatchnote.Id);
        
        //insert Packing List
        Packing_List__c objpaclist = new Packing_List__c();
        objpaclist.Delivery_Note__c = objdispatchnote.Id;
        objpaclist.Date__c = date.today();
        insert objpaclist;
        System.debug('objpaclist---- '+objpaclist.Id);   
        
        //insert product/part
        Part__c p = new Part__c();
        p.Name = 'CH10929';
        p.Active__c = true; 
        p.List_Price_Standard_price__c = 3232.22;
        insert p;
        
        //	insert Delivery Note Line Item
        Delivery_Note_Line_Item__c dNLItems = new Delivery_Note_Line_Item__c();
        dNLItems.Sales_Order_Dispatch_Delivery_Note__c = objdispatchnote.Id;
        dNLItems.Ware_House__c = wHouse.Id;
        dNLItems.Product_Part__c = p.Id;
        dNLItems.Quantity__c = 1;
        dNLItems.HSN_Code__c = '84212300';
        insert dNLItems; 
        
        //insert Packing List Line Item
        Packing_List_Line_Item__c pLItem = new Packing_List_Line_Item__c();
        pLItem.Packing_List__c = objpaclist.Id;
        pLItem.Length_Inches_CMS__c = '10';
        pLItem.Width_Inches_CMS__c = '10';
        pLItem.Height_Inches_CMS__c = '10';
        pLItem.Gross_Weight_Kgs__c = '50';
        insert pLItem;
        
        String JsonMainwrap = UpsertPackingList.productOnLoad(objpaclist.Id);
        UpsertPackingList.WrappMain mainWrap = (UpsertPackingList.WrappMain)Json.deserialize(JsonMainwrap, UpsertPackingList.WrappMain.class);
        for(UpsertPackingList.innerWrp wc :mainWrap.inrWrap){
            wc.BOXNo = 'test1';
            wc.decHeight = 5.0;
            wc.decLength = 5.0;
            wc.decWeight = 5.0;
            wc.decWidth = 5.0;
            wc.isSelected = true;
            wc.strBoxType = 'Wooden';
            wc.strRemark = 'Test';
        }
        JsonMainwrap = Json.serialize(mainWrap);
        UpsertPackingList.addRecord(JsonMainwrap, objpaclist.Id);
        
        
    }
}