force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Dispatch_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Dispatch_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Dispatch (Delivery Note)</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List__c/Packing_List__c.object-meta.xml
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Packing List No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Packing Lists</relationshipLabel>
    <relationshipName>Packing_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/Packing_List_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>DC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/BOX_No__c.field-meta.xml
<CustomField>
    <fullName>BOX_No__c</fullName>
    <label>BOX No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Box_Type__c.field-meta.xml
<CustomField>
    <fullName>Box_Type__c</fullName>
    <label>Box Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wooden</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Loose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/DC_Date__c.field-meta.xml
<CustomField>
    <fullName>DC_Date__c</fullName>
    <label>DC Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Gross_Weight_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kgs__c</fullName>
    <label>Gross Weight (Kgs)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Height_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches_CMS__c</fullName>
    <label>Height (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Length_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Length_Inches_CMS__c</fullName>
    <label>Length(Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Packing_List__c.field-meta.xml
<CustomField>
    <fullName>Packing_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packing List</label>
    <referenceTo>Packing_List__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Part_No__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_No__c.field-meta.xml
<CustomField>
    <fullName>Part_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part No.</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Width_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Width_Inches_CMS__c</fullName>
    <label>Width (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UpsertPackingList.cls
public class UpsertPackingList {
    public static WrappMain recordlist {get;set;}
    
    @AuraEnabled 
    public static string productOnLoad(string RecordId)
    {
        WrappMain objWR = new WrappMain();  
        list<innerWrp> listIW = new list<innerWrp>();
        set<id> prePartId = new set<id>();
        Packing_List__c PLREC = [Select id,Delivery_Note__c FROM Packing_List__c where id =:RecordId ];
        for(Packing_List_Line_Item__c objDNLI : [SELECT BOX_No__c,Box_Type__c,DC_Date__c,Gross_Weight_Kgs__c,Height_Inches_CMS__c,Packing_List__r.Delivery_Note__c,
                                                 Id,Length_Inches_CMS__c,Name,Packing_List__c,Part_Name__c,Part_No__c,Part_No__r.name,Part_No__r.Part_Name__c,
                                                 Quantity__c,Width_Inches_CMS__c,Remark__c FROM Packing_List_Line_Item__c WHERE  Packing_List__c =: RecordId])
        {
            innerWrp objIW = new innerWrp();
            objIW.objDNLI = objDNLI;
            objIW.strBoxType = objDNLI.Box_Type__c; 
            objIW.decLength = Decimal.valueOf(objDNLI.Length_Inches_CMS__c); 
            objIW.decWidth = Decimal.valueOf(objDNLI.Width_Inches_CMS__c);
            objIW.decHeight = Decimal.valueOf(objDNLI.Height_Inches_CMS__c); 
            objIW.decWeight = Decimal.valueOf(objDNLI.Gross_Weight_Kgs__c); 
            objIW.BOXNo = objDNLI.BOX_No__c;
            objIW.recId = objDNLI.id;
            objIW.partname = objDNLI.Part_No__r.Part_Name__c;
            objIW.partnum = objDNLI.Part_No__r.name;
            objIW.partid = objDNLI.Part_No__c;
            objIW.quantity = Integer.valueof(objDNLI.Quantity__c);
            objIW.isSelected= true;
            objIW.strRemark = objDNLI.Remark__c;
            listIW.add(objIW);
        }
        if(!listIW.isempty()) for(innerWrp pl:listIW) prePartId.add(pl.objDNLI.Part_No__c);
        list<Delivery_Note_Line_Item__c> ObjDN =[Select id, Product_Part__c,Product_Part__r.Name,
                                                 Product_Part__r.Part_Name__c, Quantity__c,Sales_Order_Dispatch_Delivery_Note__c
                                                 from Delivery_Note_Line_Item__c where Product_Part__c NOT IN: prePartId 
                                                 AND  Sales_Order_Dispatch_Delivery_Note__c =: PLREC.Delivery_Note__c];
        if(!ObjDN.isempty())
            for(Delivery_Note_Line_Item__c objDNLI : ObjDN){
                innerWrp objIW = new innerWrp();
                //objIW.objDNLI = objDNLI;  
                objIW.partname = objDNLI.Product_Part__r.Part_Name__c;
                objIW.partnum = objDNLI.Product_Part__r.name;
                objIW.partid = objDNLI.Product_Part__c;
                objIW.quantity = Integer.valueof(objDNLI.Quantity__c);
                objIW.isSelected= false;
                listIW.add(objIW);
            }
        
        objWR.inrWrap = listIW;
        system.debug('....objWR...'+objWR);
        return json.serialize(objWR);
    }
    
    
    @AuraEnabled
    public static string addRecord(string strWrap, string recordId)
    {
        //list<Sales_Order_Dispatch_Delivery_Note__c> lstDN = new list<Sales_Order_Dispatch_Delivery_Note__c>();
        //Packing_List__c objPackingList = new Packing_List__c();
        //objPackingList.Delivery_Note__c = recordId;
        //insert objPackingList;
        
        System.debug('add Record method called');
        list<Packing_List_Line_Item__c> lstDNLT = new list<Packing_List_Line_Item__c>();
        WrappMain objwrap = (WrappMain)Json.deserialize(strWrap, WrappMain.class);
        try
        {
            List<innerWrp> lstWrappNew = objwrap.inrWrap;
            System.debug('lstWrappNewSz---- '+lstWrappNew);
            for( integer i = 0 ; i<lstWrappNew.size();  i++)
            {
                if(lstWrappNew[i].isSelected)
                {
                     Packing_List_Line_Item__c objPLItems = new Packing_List_Line_Item__c();
                     objPLItems.Part_No__c = lstWrappNew[i].partid;
                     objPLItems.Quantity__c = lstWrappNew[i].quantity;
                     objPLItems.Box_Type__c = lstWrappNew[i].strBoxType;
                    objPLItems.BOX_No__c = lstWrappNew[i].BOXNo;
                     objPLItems.Length_Inches_CMS__c = string.valueof(lstWrappNew[i].decLength);
                     objPLItems.Width_Inches_CMS__c = string.valueof(lstWrappNew[i].decWidth);
                     objPLItems.Height_Inches_CMS__c = string.valueof(lstWrappNew[i].decHeight);
                     objPLItems.Gross_Weight_Kgs__c = string.valueof(lstWrappNew[i].decWeight);
                     objPLItems.Packing_List__c = recordId;
                     objPLItems.Remark__c = lstWrappNew[i].strRemark;
                     if(!string.isBlank(lstWrappNew[i].recId)) objPLItems.id=lstWrappNew[i].recId;
                     lstDNLT.add(objPLItems);
                }
            }
            if(lstDNLT.size()>0)
                upsert lstDNLT;
            objwrap.success = true;
        }
        catch(exception e)
        {
            objwrap.success = false;
            objwrap.strMessage = e.getMessage();
        }
        system.debug('..........'+json.serialize(objwrap));
        return json.serialize(objwrap); 
    }   
    
    public class WrappMain
    {   
        @AuraEnabled public list<innerWrp> inrWrap;
        @AuraEnabled public Boolean isSelectedProduct;
        @AuraEnabled public boolean success;       
        @AuraEnabled public string strMessage;
    }
    
    public class innerWrp
    {
        @AuraEnabled public Packing_List_Line_Item__c objDNLI; 
        @AuraEnabled public boolean isSelected; 
        @AuraEnabled public string strBoxType; 
        @AuraEnabled public string BOXNo;
        @AuraEnabled public decimal decLength; 
        @AuraEnabled public decimal decWidth;
        @AuraEnabled public decimal decHeight;
        @AuraEnabled public decimal decWeight;
        @AuraEnabled public integer quantity;
        @AuraEnabled public string rowError;
        @AuraEnabled public string recId;
        @AuraEnabled public string partname;
        @AuraEnabled public string partnum;
        @AuraEnabled public string partid;
        @AuraEnabled public string strRemark;
    }

}