force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Dispatch_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Dispatch_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Dispatch (Delivery Note)</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Product_Part__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>PO Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.isPrimary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders (Shipping Account Address)</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Contact_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Person Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Party__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.isPrimary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Notes</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Customer_Party__c.field-meta.xml
<CustomField>
    <fullName>Customer_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/ Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders Dispatch (Delivery Note)</relationshipLabel>
    <relationshipName>Sales_Orders_Dispatch_Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Delivery_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Number__c</fullName>
    <formula>if( text( Sales_Order__r.Ware_House__r.City__c) == &apos;Kolkata&apos;, &apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;GDNT&apos;+RIGHT( Name , LEN(Name) - 4),if( text(Sales_Order__r.Ware_House__r.City__c) == &apos;Gurugram&apos;, &apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;GDNT&apos;+RIGHT( Name , LEN(Name) - 4),&apos;Please select Place on supply on SO.&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Note Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Delivery Note</relationshipLabel>
    <relationshipName>Delivery_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping  Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Notes (Shipping  Account)</relationshipLabel>
    <relationshipName>Delivery_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <formula>Product_In__c  -  Product_Out__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/Stock_Landed_Amount__c.object-meta.xml
<CustomObject>
    <label>Stock Landed Amount</label>
    <nameField>
        <displayFormat>SLA-{000000}</displayFormat>
        <label>Stock Landed Amount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Landed Amount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Landed_Price__c.field-meta.xml
<CustomField>
    <fullName>Landed_Price__c</fullName>
    <formula>if(ISblank(MRN_Line_Item__c), Landed_Amount_Historical__c ,MRN_Line_Item__r.Landed_Cost_Unit_Rate__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Landed Price/ Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Landed_Amount__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stock Landed Amount</relationshipLabel>
    <relationshipName>Stock_Landed_Amount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Warehouse_City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Warehouse City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/customLookUpController.cls
public with sharing class customLookUpController 
{
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName) 
    {
        String searchKey = searchKeyWord + '%';
        String sQuery = '';
        
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5
        if(ObjectName =='Sales_Order_Dispatch_Delivery_Note__c'){
            sQuery =  'select id, Delivery_Note_Number__c from ' +ObjectName + ' where Delivery_Note_Number__c LIKE: searchKey order by createdDate DESC limit 5';
        } else{
            sQuery =  'select id, Name from ' +ObjectName + ' where Name LIKE: searchKey order by createdDate DESC limit 5';
        }       
        
        return Database.query(sQuery);
    }
    
    @AuraEnabled 
    public static SObject[] getSearchDeliveryNoteLI1(string strDeliveryNoteId, string objectName)
    {
        try
        {
            string filter = '';
            if(strDeliveryNoteId != null && strDeliveryNoteId !=''){
                map<String , Schema.SObjectType> globalDescription = Schema.getGlobalDescribe();
                Schema.sObjectType sObjType = globalDescription.get(objectName);
                Schema.DescribeSObjectResult describeResult = sObjType.getDescribe();
                List<string> leadfieldNames = new List<String>(describeResult.fields.getMap().keySet()); 
                string soql = 'select ' + string.join(leadfieldNames, ',') +',Sales_Order_Dispatch_Delivery_Note__r.Name,Sales_Order_Dispatch_Delivery_Note__r.Date__c,Ware_House__r.Name,Stock__r.Total_Product__c,Product_Part__r.Name,Product_Part__r.CreatedDate from ' + objectName ; 
                system.debug('......'+soql);
                if(strDeliveryNoteId != '')     
                    soql += ' where Sales_Order_Dispatch_Delivery_Note__c =: strDeliveryNoteId';
                system.debug('====='+soql);
                //soql += 'order by Name limit 10';
                return Database.query(soql);
            }else{
                return null;
            }
        }
        catch(Exception ex)
        {
            system.debug('Exception---- '+ex.getMessage());
            return null;
        }
    }
    
    @AuraEnabled
    public static string getSearchDeliveryNoteLI(string strDeliveryNoteId, string objectName)
    {
        mainWrapper objmainWrap = new mainWrapper();
        objmainWrap.lstSubMain = new List<SubMainWraip>();
        objmainWrap.listPurchaseOrderLI = new List<SubMainWraip>();
        try
        {
            string filter = '';
            if(strDeliveryNoteId != null && strDeliveryNoteId !=''){
                map<string,Stock__c> mapNoOfStock = new map<string,Stock__c>();
                for(Stock__c objStock : [Select Id,Name,Ware_House__c,Ware_House__r.City__c,Product_Part__c,Quantity__c,Total_Quantity__c,(SELECT CreatedDate,Landed_Price__c FROM Stock_Landed_Amount__r Where Landed_Price__c > 0  ORDER BY CreatedDate DESC ) from Stock__c]){
                    mapNoOfStock.put(objStock.Product_Part__c+'-'+objStock.Ware_House__c,objStock);
                }
                map<String , Schema.SObjectType> globalDescription = Schema.getGlobalDescribe();
                Schema.sObjectType sObjType = globalDescription.get(objectName);
                Schema.DescribeSObjectResult describeResult = sObjType.getDescribe();
                List<string> leadfieldNames = new List<String>(describeResult.fields.getMap().keySet()); 
                
                /* Adding the object and filter by name to the soql */
                string soql = 'select ' + string.join(leadfieldNames, ',') +',Sales_Order_Dispatch_Delivery_Note__r.Shipping_Account__c,Sales_Order_Dispatch_Delivery_Note__r.Contact_Person_Name__c, Sales_Order_Dispatch_Delivery_Note__r.Customer_Party__c,Sales_Order_Dispatch_Delivery_Note__r.Sales_Order__r.Contact_Person__c,Sales_Order_Dispatch_Delivery_Note__r.Sales_Order__r.Ware_House__c,Sales_Order_Dispatch_Delivery_Note__r.Name,Sales_Order_Dispatch_Delivery_Note__r.Date__c,Ware_House__r.Name,Ware_House__r.City__c,Product_Part__r.Name,Product_Part__r.CreatedDate,Product_Part__r.Part_Name__c from ' + objectName ; 
                system.debug('......'+soql);
                if(strDeliveryNoteId != '')     
                    soql += ' where Sales_Order_Dispatch_Delivery_Note__c =: strDeliveryNoteId';
                system.debug('====='+soql);
                
                
                //soql += 'order by Name limit 10';
                List<Delivery_Note_Line_Item__c> lstSODN = Database.query(soql);
                system.debug('..lstSODN...'+lstSODN.size());
                for(Delivery_Note_Line_Item__c objSODN : lstSODN){
                    SubMainWraip objSMW = new SubMainWraip();
                    objSMW.objDNLI = objSODN;
                    objSMW.IsEdit = false;
                   
                    Integer IntQty =0;
                    Decimal unitprice = 0;
                    
                    if(objSODN.Product_Part__c !=null && objSODN.Sales_Order_Dispatch_Delivery_Note__r.Sales_Order__r.Ware_House__c !=null){
                        stock__c stk = mapNoOfStock.get(objSODN.Product_Part__c+'-'+objSODN.Sales_Order_Dispatch_Delivery_Note__r.Sales_Order__r.Ware_House__c);
                        IntQty = Integer.ValueOf(stk.Total_Quantity__c);
                        System.debug(stk.Name);
                        objSMW.StockId =stk.Id; 
                        if(!stk.Stock_Landed_Amount__r.isEmpty())
                            unitprice=stk.Stock_Landed_Amount__r[0].Landed_Price__c;
                    }
                    if(IntQty !=null)
                        objSMW.StockTotalProduct =IntQty;
                    else
                        objSMW.StockTotalProduct =0;
                    
                   
                    objSMW.DnUnitQty = objSODN.Quantity__c  ;
                    objSMW.DnUnitPrice = unitprice ;
                    objSMW.DnAmount =   objSODN.Quantity__c * objSMW.DnUnitPrice;
                    objSMW.DnDiscountPer = objSODN.Discount__c ;
                    objSMW.DnDiscountAmount = objSMW.DnAmount * objSODN.Discount__c ;
                    objSMW.DnTaxableAmount = objSMW.DnAmount - objSMW.DnDiscountAmount   ;
                    objSMW.DnCGSTRate = objSODN.CGST__c  ;
                    objSMW.DnCGSTAmount = objSMW.DnTaxableAmount * objSMW.DnCGSTRate ;
                    objSMW.DnSGSTRate = objSODN.SGST__c  ;
                    objSMW.DnSGSTAmount = objSMW.DnTaxableAmount * objSMW.DnSGSTRate ;
                    objSMW.DnIGSTRate = objSODN.IGST__c  ;
                    objSMW.DnIGSTAmount = objSMW.DnTaxableAmount * objSMW.DnIGSTRate ;
                    objSMW.DnNetAmount =  objSMW.DnTaxableAmount + objSMW.DnCGSTAmount + objSMW.DnSGSTAmount + objSMW.DnIGSTAmount;
                    
                    objmainWrap.lstSubMain.add(objSMW);
                }
                system.debug('..objmainWrap.lstSubMain...'+objmainWrap.lstSubMain.size());
                //return Database.query(soql);
            }
        }catch(Exception e)
        {
            objMainWrap.isSuccess= false;
            objMainWrap.strMessage = ExceptionMessage.getExceptionMsg(e);
        }
        return JSON.serialize(objmainWrap);
    }
    
    public Class mainWrapper
    {
        public boolean isSuccess;
        public string strMessage;
        public list<SubMainWraip> lstSubMain;
        public list<SubMainWraip> listPurchaseOrderLI;
    }
    public Class SubMainWraip
    {
        public Delivery_Note_Line_Item__c objDNLI;
        public Purchase_Order_Line_Item__c objPOLI;
        public boolean IsEdit;
        public Integer StockTotalProduct;
        public string StockId;
         public decimal DnUnitQty;
        public decimal DnUnitPrice;
        public decimal DnAmount;
        public decimal DnDiscountPer;
        public decimal DnDiscountAmount;
        public decimal DnTaxableAmount;
        public decimal DnCGSTRate;
        public decimal DnCGSTAmount;
        public decimal DnSGSTRate;
        public decimal DnSGSTAmount;
        public decimal DnIGSTRate;
        public decimal DnIGSTAmount;
        public decimal DnNetAmount;
        
    }
}