force-app/main/default/objects/Delivery_Note_Line_Item__c/Delivery_Note_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Delivery Note Line Item</label>
    <nameField>
        <displayFormat>DNL-{0000}</displayFormat>
        <label>Delivery Note Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Note Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Part_Serial__c.field-meta.xml
<CustomField>
    <fullName>Part_Serial__c</fullName>
    <label>Part Serial</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Note_Line_Item__c/fields/Sales_Order_Dispatch_Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Dispatch_Delivery_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Dispatch (Delivery Note)</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Delivery Note Line Items</relationshipLabel>
    <relationshipName>Delivery_Note_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List__c/Packing_List__c.object-meta.xml
<CustomObject>
    <label>Packing List</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Packing List No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List__c/fields/Delivery_Note__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Delivery Note</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Packing Lists</relationshipLabel>
    <relationshipName>Packing_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/Packing_List_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Packing List Line Item</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>DC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing List Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/BOX_No__c.field-meta.xml
<CustomField>
    <fullName>BOX_No__c</fullName>
    <label>BOX No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Box_Type__c.field-meta.xml
<CustomField>
    <fullName>Box_Type__c</fullName>
    <label>Box Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wooden</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Loose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Customer_Part_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part_No__c</fullName>
    <label>Customer Part No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/DC_Date__c.field-meta.xml
<CustomField>
    <fullName>DC_Date__c</fullName>
    <label>DC Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Gross_Weight_Kgs__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kgs__c</fullName>
    <label>Gross Weight (Kgs)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Height_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches_CMS__c</fullName>
    <label>Height (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Length_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Length_Inches_CMS__c</fullName>
    <label>Length(Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Packing_List__c.field-meta.xml
<CustomField>
    <fullName>Packing_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Packing List</label>
    <referenceTo>Packing_List__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Part_No__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Part_No__c.field-meta.xml
<CustomField>
    <fullName>Part_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part No.</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Packing List Line Items</relationshipLabel>
    <relationshipName>Packing_List_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Packing_List_Line_Item__c/fields/Width_Inches_CMS__c.field-meta.xml
<CustomField>
    <fullName>Width_Inches_CMS__c</fullName>
    <label>Width (Inches,CMS)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/isTaxinvoice__c.field-meta.xml
<CustomField>
    <fullName>isTaxinvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTax Invoice?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/addPackingListControl.cls
public class addPackingListControl {
    public static WrappMain recordlist {get;set;}
    
    @AuraEnabled 
    public static string productOnLoad(string RecordId)
    {
        
        WrappMain objWR = new WrappMain();  
        list<innerWrp> listIW = new list<innerWrp>();
        list<Packing_List_Line_Item__c> prelist = [SELECT BOX_No__c,Box_Type__c,DC_Date__c,Gross_Weight_Kgs__c,Height_Inches_CMS__c,Packing_List__r.Delivery_Note__c,
                                           Id,Length_Inches_CMS__c,Name,Packing_List__c,Part_Name__c,Part_No__c,
                                           Quantity__c,Width_Inches_CMS__c, Remark__c FROM Packing_List_Line_Item__c WHERE Packing_List__r.Delivery_Note__c =:recordid];
        set<id> prePartId = new set<id>();
        if(!prelist.isempty()) for(Packing_List_Line_Item__c pl:prelist) prePartId.add(pl.Part_No__c);
        for(Delivery_Note_Line_Item__c objDNLI : [Select id,Part_Serial__c, Product_Part__c,Product_Part__r.Name,Product_Part__r.Part_Name__c, Quantity__c,Sales_Order_Dispatch_Delivery_Note__c from Delivery_Note_Line_Item__c where Product_Part__c NOT IN: prePartId AND  Sales_Order_Dispatch_Delivery_Note__c =: RecordId])
        {
            innerWrp objIW = new innerWrp();
            objIW.objDNLI = objDNLI;
            objIW.custmnum= objDNLI.Part_Serial__c;
            
            objIW.isSelected= false;
            listIW.add(objIW);
        }
        objWR.inrWrap = listIW;
        objWR.AllDone =  false;
        if(listIW.isempty()) 
        objWR.AllDone =  true;
        system.debug('....objWR...'+objWR);
        return json.serialize(objWR);
    }
    
    
    @AuraEnabled
    public static string addRecord(string strWrap, string recordId)
    {
        list<Sales_Order_Dispatch_Delivery_Note__c> lstDN = new list<Sales_Order_Dispatch_Delivery_Note__c>();
        Packing_List__c objPackingList = new Packing_List__c();
        objPackingList.Delivery_Note__c = recordId;
        objPackingList.Date__c =system.today();
        insert objPackingList;
        
        System.debug('add Record method called');
        list<Packing_List_Line_Item__c> lstDNLT = new list<Packing_List_Line_Item__c>();
        WrappMain objwrap = (WrappMain)Json.deserialize(strWrap, WrappMain.class);
        try
        {
            List<innerWrp> lstWrappNew = objwrap.inrWrap;
            System.debug('lstWrappNewSz---- '+lstWrappNew);
            System.debug('lstWrappNewSz---- '+lstWrappNew.size());
            for( integer i = 0 ; i<lstWrappNew.size();  i++)
            {
                if(lstWrappNew[i].isSelected)
                {
                    Packing_List_Line_Item__c objPLItems = new Packing_List_Line_Item__c();
                    objPLItems.Part_No__c = lstWrappNew[i].objDNLI.Product_Part__c;
                    objPLItems.Quantity__c = lstWrappNew[i].objDNLI.Quantity__c;
                    objPLItems.Box_Type__c = lstWrappNew[i].strBoxType;
                    objPLItems.BOX_No__c = lstWrappNew[i].BOXNo;
                    objPLItems.Length_Inches_CMS__c = string.valueof(lstWrappNew[i].decLength);
                    objPLItems.Width_Inches_CMS__c = string.valueof(lstWrappNew[i].decWidth);
                    objPLItems.Height_Inches_CMS__c = string.valueof(lstWrappNew[i].decHeight);
                    objPLItems.Gross_Weight_Kgs__c = string.valueof(lstWrappNew[i].decWeight);
                    objPLItems.Remark__c = lstWrappNew[i].strRemark;
                    objPLItems.Customer_Part_No__c = lstWrappNew[i].custmnum;
                    
                    objPLItems.Packing_List__c = objPackingList.Id;
                    lstDNLT.add(objPLItems);
                }
            }
            if(lstDNLT.size()>0)
                insert lstDNLT;
            objwrap.success = true;
        }
        catch(exception e)
        {
            objwrap.success = false;
            objwrap.strMessage = e.getMessage();
        }
        
        String str = productOnLoad(recordId);
        WrappMain objwrap2 = (WrappMain)Json.deserialize(str, WrappMain.class);
        if(objwrap2.AllDone)
        {
            Sales_Order_Dispatch_Delivery_Note__c DNrecord = new Sales_Order_Dispatch_Delivery_Note__c();
            DNrecord.id = recordId;
            DNrecord.isTaxinvoice__c = true;
            update DNrecord;
        }
        system.debug('..........'+json.serialize(objwrap));
        return json.serialize(objwrap); 
    }   
    
    public class WrappMain
    {   
        @AuraEnabled public list<innerWrp> inrWrap;
        @AuraEnabled public Boolean isSelectedProduct;
        @AuraEnabled public boolean success;       
        @AuraEnabled public string strMessage;
        @AuraEnabled public boolean AllDone;  
    }
    
    public class innerWrp
    {
        @AuraEnabled public Delivery_Note_Line_Item__c objDNLI; 
        @AuraEnabled public boolean isSelected;
        @AuraEnabled public string custmnum;
        @AuraEnabled public string strBoxType;
        @AuraEnabled public string BOXNo;
        @AuraEnabled public decimal decLength; 
        @AuraEnabled public decimal decWidth;
        @AuraEnabled public decimal decHeight;
        @AuraEnabled public decimal decWeight;
        @AuraEnabled public string rowError;
        @AuraEnabled public string strRemark;
    }
}