force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PON-{000000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Contact_No__c</fullName>
    <formula>Contact_person__r.Phone</formula>
    <label>Contact No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Contact_person__c.field-meta.xml
<CustomField>
    <fullName>Contact_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Name_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/CGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c * CGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/IGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c  *  IGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Net_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c  +  CGST_Amount_Formula__c  +  IGST_Amount_Formula__c  +  SGST_Amount_Formula__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/SGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>SGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c * SGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Taxable_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Amount_Formula__c</fullName>
    <formula>Total_Amount__c -  Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line_Item__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Contact_No__c</fullName>
    <label>Contact No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/E_Mail__c.field-meta.xml
<CustomField>
    <fullName>E_Mail__c</fullName>
    <label>E-Mail</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/GSTIN_No__c.field-meta.xml
<CustomField>
    <fullName>GSTIN_No__c</fullName>
    <label>GSTIN No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Warehouse_City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Warehouse City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PurchaseOrder.cls
public class PurchaseOrder {
    public Purchase_Order__c objPO {get;set;}
    public Account objSupplier {get;set;}
    public Contact objSupplierContact {get;set;}
    public Ware_House__c objWHBillTo {get;set;}
    public Ware_House__c objWHShipTo {get;set;}
    //public List<wrapper> lstPOIW {get; set;}
    public List<Purchase_Order_Line_Item__c> lstPOI {get;set;}
    public decimal subTotalTaxableAmount{get;set;}
    public decimal subTotalAmount{get;set;}
    public Decimal SubTotalIGST{get;set;}
    public Decimal SubTotalCGST{get;set;}
    public Decimal SubTotalSGST{get;set;}
    public decimal TotalTaxableAmount{get;set;}
    public decimal TotalAmount{get;set;}
    public String TotalAmountInWords{get;set;}
    public Decimal TotalIGST{get;set;}
    public Decimal TotalCGST{get;set;}
    public Decimal TotalSGST{get;set;}
    public Decimal TotalGST{get;set;}
    
    public PurchaseOrder(ApexPages.StandardController controller){
        String strId = ApexPages.currentPage().getParameters().get('id');
        
        if(String.isNotBlank(strId)){
            
            lstPOI = new List<Purchase_Order_Line_Item__c>();
            objWHBillTo = new Ware_House__c();
            objWHShipTo = new Ware_House__c();
            subTotalTaxableAmount = 0;
            subTotalAmount = 0;
            SubTotalIGST = 0;
            SubTotalCGST = 0;
            SubTotalSGST = 0;
            TotalTaxableAmount = 0;
            TotalAmount = 0;
            TotalAmountInWords ='';
            TotalIGST = 0;
            TotalCGST = 0;
            TotalSGST = 0;
            TotalGST = 0;
            
            List<String> lstPurchaseOrderField = UtilityClass.getAllFields('Purchase_Order__c');
            List<String> lstPurchaseOrderItemField = UtilityClass.getAllFields('Purchase_Order_Line_Item__c');
            
            String strPurchaseOrderQuery = 'Select ' +String.Join(lstPurchaseOrderField, ',')+ ' From Purchase_Order__c where Id =: strId';
            String strPurchaseOrderItemQuery = 'Select ' +String.Join(lstPurchaseOrderItemField, ',')+ ' From Purchase_Order_Line_Item__c where Purchase_Order__c =: strId';
            
            List<Purchase_Order__c> lstPurchaseOrder =  Database.query(strPurchaseOrderQuery);
            if(lstPurchaseOrder.size() > 0){
                objPO = lstPurchaseOrder[0];
                if(String.isNotEmpty(objPO.Supplier__c)){
                    objSupplier = [Select Id,Name, BillingCity,BillingCountry, BillingPostalCode,BillingState,BillingStreet,GSTIN_No__c ,Billing_State_Code__c,
                                   (Select Id, Email, MobilePhone, Name from contacts ) 
                                   from Account 
                                   where Id =: objPO.Supplier__c];
                    if(objSupplier.contacts.size() > 0){
                        objSupplierContact = objSupplier.contacts[0];
                    }
                }
                // Receiver And Consignee Details from wareHouse
                if(String.isNotBlank(objPO.Bill_To__c) && String.isNotBlank(objPO.Ship_To__c)){
                    set<String> setCity = new set<String>();
                    setCity.add(objPO.Bill_To__c);
                    setCity.add(objPO.Ship_To__c);
                    List<Ware_House__c> lstWareHouse = [Select Id, City__c, Contact_No__c,  Contact_Person__c,  Country__c, E_Mail__c,  GSTIN_No__c,State_Code__c,  State_Province__c,  Street__c,Name, Zip_Postal_Code__c  
                                                       From Ware_House__c 
                                                       where City__c =:setCity];
                    for(Ware_House__c objWH : lstWareHouse){
                        if(objPO.Bill_To__c ==  objWH.City__c)
                            objWHBillTo = objWH;
                        if(objPO.Ship_To__c ==  objWH.City__c)
                            objWHShipTo = objWH;
                    }
                }
                    
            }
             
            lstPOI = Database.query(strPurchaseOrderItemQuery);
            if(lstPOI.size() > 0){
                for(Purchase_Order_Line_Item__c objPOLI : lstPOI){
                    if(objPOLI.Taxable_Amount_Formula__c > 0)
                        subTotalTaxableAmount += objPOLI.Taxable_Amount_Formula__c;
                    if(objPOLI.Net_Amount_Formula__c > 0)
                        subTotalAmount += objPOLI.Net_Amount_Formula__c;
                    if(objPOLI.IGST_Amount_Formula__c > 0)
                        SubTotalIGST += objPOLI.IGST_Amount_Formula__c;
                    if(objPOLI.CGST_Amount_Formula__c > 0)
                        SubTotalCGST += objPOLI.CGST_Amount_Formula__c;
                    if(objPOLI.SGST_Amount_Formula__c > 0)
                        SubTotalSGST += objPOLI.SGST_Amount_Formula__c;
                }
                
                TotalTaxableAmount = subTotalTaxableAmount;
                TotalAmount = subTotalAmount;
                TotalIGST = SubTotalIGST;
                TotalCGST = SubTotalCGST;
                TotalSGST = SubTotalSGST;
                TotalGST = TotalIGST+TotalCGST+TotalSGST;
                
                if(TotalAmount > 0){
                    TotalAmount = TotalAmount.round();
                    TotalAmountInWords = UtilityClass.NoToWord(TotalAmount.intValue());
                }
            }
        }
    }   
    
    /*public class wrapper{
        public Purchase_Order_Line_Item__c objPOLI;
        public Decimal CGSTAmount;
        public Decimal SGSTAmount;
        public Decimal IGSTAmount;
        
        public wrapper(){
            objPOLI = new Purchase_Order_Line_Item__c();
            CGSTAmount = 0;
            SGSTAmount = 0;
            IGSTAmount = 0;
        }
        
    }*/

}