force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Customer Asset</label>
    <nameField>
        <label>Engine Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/Part_Request__c.object-meta.xml
<CustomObject>
    <label>Part Request</label>
    <nameField>
        <displayFormat>PR-{00}</displayFormat>
        <label>Part Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Request__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Parts Request</relationshipLabel>
    <relationshipName>Parts_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Parts Request</relationshipLabel>
    <relationshipName>Parts_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/WarrantyClaimTriggerHelperTest.cls
@isTest
public class WarrantyClaimTriggerHelperTest {
    @isTest
    private static void inserPartRequestOfEnadCustomerTest()
    {
        clsUtility.testDataCustomSetting();
        list<Account> lstAcc = clsUtility.testDataAccountContact(5,5,false);
        Account acc = clsUtility.testDataEndCustomerAcc(10);
        list<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(lstAcc[0],acc,3);
        list<Service_Request__c> lstSR = clsUtility.testDataServiceRequest(3,false,lstAsset);
        
        List<Part__c> lstPart = new List<Part__c>();
        List<Part_Request__c> lstPartRequest = new List<Part_Request__c>();
        
        for(Integer i = 1; i<= 5 ; i++) {
            Part__c objPart = new Part__c(Part_Name__c = 'TestPart'+i,
                                          Name = 'TP'+i);
            lstPart.add(objPart);
        }
        insert lstPart;
        
        for(Service_Request__c objSR : lstSR) {
            for(Part__c objPart : lstPart) {
                for(integer i = 0;i<2;i++)
                {
                    Part_Request__c objPartReq = new Part_Request__c(Part__c = objPart.Id,Service_Request__c = objSR.Id);
                    lstPartRequest.add(objPartReq);
                }
            } 
        }
        insert lstPartRequest;  
        clsUtility.testInsertWarrantyCase(lstSR);
    }
}