force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Customer Asset</label>
    <nameField>
        <label>Engine Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>OEM</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/ESN__c.field-meta.xml
<CustomField>
    <fullName>ESN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ESN</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OEM</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceRequestHandlerTest.cls
/*
--------------------------------------------------------------------------------------
Version#     Date                           Author                    Description
--------------------------------------------------------------------------------------
1.0          19-Dec-2019                   Deepak Pandey            Initial Version
--------------------------------------------------------------------------------------
*/
@istest
public class ServiceRequestHandlerTest{
    @istest
    static void execute(){
        clsUtility.testDataCustomSetting();
        Account objAccOEM = clsUtility.testDataOEMAcc(5);
        Account objAccENDCustomer = clsUtility.testDataEndCustomerAcc(5);
        list<Asset__c> lstAssetAccountNumber = clsUtility.testDataCustomerAsset(objAccOEM,objAccENDCustomer,1);
        list<Service_Request__c> lstSR = clsUtility.testDataServiceRequest(5,true,lstAssetAccountNumber);
        clsUtility.testDataAddServiceTeam(lstSR,true);
        Asset__c objAss = new Asset__c();
        objAss.Name ='uniqueName Data test';
        objAss.OEM__c  = objAccOEM.Id;
        objAss.End_Customer__C  = objAccENDCustomer.Id;
        Insert objAss;
        lstSR[0].ESN__c = objAss.Id;
        update lstSR[0];
    }
}