force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Customer Asset</label>
    <nameField>
        <label>Engine Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Complaint_Type__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Type__c</fullName>
    <label>Complaint Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakdown</fullName>
            </value>
            <value>
                <fullName>Running with Problem</fullName>
            </value>
            <value>
                <fullName>Planned Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/ESN__c.field-meta.xml
<CustomField>
    <fullName>ESN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ESN</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/fields/Issue_Reported__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reported__c</fullName>
    <label>Issue Reported</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SafetyRuleControllerTest.cls
@isTest
public class SafetyRuleControllerTest {
@isTest
    public static void testcreateSaftyRules(){
                clsUtility.testDataCustomSetting();
            Asset__c objAss = new Asset__c(Name ='test',Account_Number__C  = 1,Company__c = 'Test Company');

        Service_Request__c sf=new Service_Request__c();
        sf.Issue_Reported__c='test';
        sf.Complaint_Type__c='Breakdown';
        sf.ESN__c=objAss.Id;
        insert sf;
        SafetyRuleController.saveSafetyRules(sf.Id,'test','test','test','test','test','test');
    }
}