force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Customer Asset</label>
    <nameField>
        <label>Engine Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Parts Requested</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckOutcls_Test.cls
@isTest
public class CheckOutcls_Test {
    
    @isTest
    Static List<Service_Request__c> TestData() {
        
        clsUtility.testDataCustomSetting();
        Account EndCustom = clsUtility.testDataEndCustomerAcc(1);
        Account OEMAcc = clsUtility.testDataOEMAcc(1);
        
        List<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(OEMAcc, EndCustom, 1);
        List<Service_Request__c> lstServiceRequest = clsUtility.testDataServiceRequest(1, false, lstAsset);
        clsUtility.testDataAddServiceTeam(lstServiceRequest, true);
        
        return lstServiceRequest;
    }
    
    @isTest
    Static void MethodOne(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 1'];
        System.runAs(objUser) {
          string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id); 
          string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
          strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();
        
    }
    
    @isTest    
    Static void MethodTwo(){
        
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();

        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 2'];
        System.runAs(objUser) {
         string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id); 
         string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
         strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();
    }
    
    @isTest    
    Static void MethodThree(){
        
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();

        Test.startTest();
            User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 3'];
            System.runAs(objUser) {
            string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
           string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
           strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
   
    @isTest    
    Static void MethodFour(){
        
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 4'];
        System.runAs(objUser) {
             string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
            strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    } 
    
    @isTest    
    Static void MethodFive(){
        
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 4'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
    
    @isTest    
    Static void MethodSix(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 3'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
    
    @isTest    
    Static void MethodSeven(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
         User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 2'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
    
    @isTest    
    Static void MethodEight(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 1'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
    
    @isTest    
    Static void MethodNine(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        lstServiceRequest[0].Status__c = 'On Hold';
        update lstServiceRequest[0];
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 1'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
    
    @isTest    
    Static void MethodTen(){
        List<Service_Request__c> lstServiceRequest = CheckOutcls_Test.TestData();
        lstServiceRequest[0].Status__c = 'Closed';
        update lstServiceRequest[0];
        Test.startTest();
        User objUser = [Select id, LastName, Email from User where LastName = 'TestEngineer 1'];
        System.runAs(objUser) {
             //string strwrap = CheckIncls.updateCheckIn(lstServiceRequest[0].Id);  
            string strwrapCheckOut = CheckOutcls.updateCheckOut(lstServiceRequest[0].Id); 
        }
        Test.stopTest();  
    }
}