force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Customer Asset</label>
    <nameField>
        <label>Engine Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/Powerparts_Service_Request_Team__c.object-meta.xml
<CustomObject>
    <label>Powerparts Service Request Team</label>
    <nameField>
        <displayFormat>Team-{0000}</displayFormat>
        <label>Service Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Powerparts Service Request Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer1__c.field-meta.xml
<CustomField>
    <fullName>Engineer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Engineer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Branch Manager</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>A&amp;I Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer2__c.field-meta.xml
<CustomField>
    <fullName>Engineer2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer3__c.field-meta.xml
<CustomField>
    <fullName>Engineer3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Engineer4__c.field-meta.xml
<CustomField>
    <fullName>Engineer4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Engineer</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Service Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Powerparts_Service_Request_Team3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Powerparts_Service_Request_Team__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Powerparts Service Request Team</relationshipLabel>
    <relationshipName>Powerparts_Service_Request_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ServiceRequestTeamHandler_Test.cls
@isTest
public class ServiceRequestTeamHandler_Test {
    
    @isTest
    static void methodOne() {
        Profile objProfile = [Select Id, Name from Profile where Name='Service Engineer'];
        
        User objUser = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser;
        
        User objUser1 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser1;
        
        User objUser2 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer123@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser2;
        
        User objUser4 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser4;
        
        clsUtility.testDataCustomSetting();
        Account EndCustom = clsUtility.testDataEndCustomerAcc(1);
        Account OEMAcc = clsUtility.testDataOEMAcc(1);
        
        List<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(OEMAcc, EndCustom, 1);
        List<Service_Request__c> lstServiceRequest = clsUtility.testDataServiceRequest(1, false, lstAsset);
        
        Powerparts_Service_Request_Team__c objPSR = new Powerparts_Service_Request_Team__c();
        objPSR.Service_Request__c = lstServiceRequest[0].Id;
        objPSR.Engineer1__c = objUser4.Id;
        objPSR.Engineer2__c = objUser.Id;
        objPSR.Engineer3__c = objUser1.Id;
        objPSR.Engineer4__c = objUser2.Id;
        insert objPSR;
        list<Powerparts_Service_Request_Team__c> lstPPT = new list<Powerparts_Service_Request_Team__c>();
        lstPPT.add(objPSR);
        try{
            ServiceRequestTeamHandler.onafterInsert(lstPPT);
        }catch(exception ex){
        
        }
        
        
        //clsUtility.testDataAddServiceTeam(lstServiceRequest, true);
        clsUtility.testDataContentDoc(lstServiceRequest, 5); 
        List<Powerparts_Service_Request_Team__c> lstSRT = [Select id, Service_Request__c ,Engineer1__c, Engineer2__c ,Engineer3__c,Engineer4__c 
                                                           from Powerparts_Service_Request_Team__c
                                                           where Service_Request__c =:lstServiceRequest[0].id ];
        lstSRT[0].Engineer4__c = null;
        update lstSRT;
        
        try{
            ServiceRequestTeamHandler.onafterInsert(lstPPT);
        }catch(exception ex){
        
        }
    }
    
    @isTest
    static void methodTwo() {
        Profile objProfile = [Select Id, Name from Profile where Name='Service Engineer'];
        
        User objUser = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser;
        
        User objUser1 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser1;
        
        User objUser2 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer123@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser2;
        
        User objUser4 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser4;
        
        User objUser5 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465900909@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser5;
        
        clsUtility.testDataCustomSetting();
        Account EndCustom = clsUtility.testDataEndCustomerAcc(1);
        Account OEMAcc = clsUtility.testDataOEMAcc(1);
        
        List<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(OEMAcc, EndCustom, 1);
        List<Service_Request__c> lstServiceRequest = clsUtility.testDataServiceRequest(1, false, lstAsset);
        
        Powerparts_Service_Request_Team__c objPSR = new Powerparts_Service_Request_Team__c();
        objPSR.Service_Request__c = lstServiceRequest[0].Id;
        objPSR.Engineer1__c = objUser4.Id;
        objPSR.Engineer2__c = objUser.Id;
        objPSR.Engineer3__c = objUser1.Id;
        objPSR.Engineer4__c = objUser2.Id;
        insert objPSR;
        
        objPSR.Engineer2__c = objUser5.Id;
        update objPSR;
        
        
        //clsUtility.testDataAddServiceTeam(lstServiceRequest, true);
        clsUtility.testDataContentDoc(lstServiceRequest, 5); 
        List<Powerparts_Service_Request_Team__c> lstSRT = [Select id, Service_Request__c ,Engineer1__c, Engineer2__c ,Engineer3__c,Engineer4__c 
                                                           from Powerparts_Service_Request_Team__c
                                                           where Service_Request__c =:lstServiceRequest[0].id ];
        lstSRT[0].Engineer4__c = null;
        update lstSRT;
    }
    
    @isTest
    static void methodThree() {
        Profile objProfile = [Select Id, Name from Profile where Name='Service Engineer'];
        
        User objUser = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser;
        
        User objUser1 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser1;
        
        User objUser2 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer123@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser2;
        
        User objUser4 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser4;
        
        User objUser5 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465900909@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser5;
        
        clsUtility.testDataCustomSetting();
        Account EndCustom = clsUtility.testDataEndCustomerAcc(1);
        Account OEMAcc = clsUtility.testDataOEMAcc(1);
        
        List<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(OEMAcc, EndCustom, 1);
        List<Service_Request__c> lstServiceRequest = clsUtility.testDataServiceRequest(1, false, lstAsset);
        
        Powerparts_Service_Request_Team__c objPSR = new Powerparts_Service_Request_Team__c();
        objPSR.Service_Request__c = lstServiceRequest[0].Id;
        objPSR.Engineer1__c = objUser4.Id;
        objPSR.Engineer2__c = objUser.Id;
        objPSR.Engineer3__c = objUser1.Id;
        objPSR.Engineer4__c = objUser2.Id;
        insert objPSR;
        
        objPSR.Engineer3__c = objUser5.Id;
        update objPSR;
        
        
        //clsUtility.testDataAddServiceTeam(lstServiceRequest, true);
        clsUtility.testDataContentDoc(lstServiceRequest, 5); 
        List<Powerparts_Service_Request_Team__c> lstSRT = [Select id, Service_Request__c ,Engineer1__c, Engineer2__c ,Engineer3__c,Engineer4__c 
                                                           from Powerparts_Service_Request_Team__c
                                                           where Service_Request__c =:lstServiceRequest[0].id ];
        lstSRT[0].Engineer4__c = null;
        update lstSRT;
    }
    
    @isTest
    static void methodFour() {
        Profile objProfile = [Select Id, Name from Profile where Name='Service Engineer'];
        
        User objUser = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser;
        
        User objUser1 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer1234234@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser1;
        
        User objUser2 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer123@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser2;
        
        User objUser4 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser4;
        
        User objUser5 = new User(ProfileId = objProfile.Id,
                                        LastName = 'TestEngineer ',
                                        Email = 'TestEngineer@test.com',
                                        Username = 'TestEngineer12343655465900909@test.com',
                                        CompanyName = 'Test Pvt Ltd',
                                        Alias = 'TEngi',
                                        TimeZoneSidKey = 'America/Los_Angeles',
                                        EmailEncodingKey = 'ISO-8859-1',
                                        LocaleSidKey = 'en_US',
                                        LanguageLocaleKey = 'en_US');
                //lstUser.add(objUser);
        
        insert objUser5;
        
        clsUtility.testDataCustomSetting();
        Account EndCustom = clsUtility.testDataEndCustomerAcc(1);
        Account OEMAcc = clsUtility.testDataOEMAcc(1);
        
        List<Asset__c> lstAsset = clsUtility.testDataCustomerAsset(OEMAcc, EndCustom, 1);
        List<Service_Request__c> lstServiceRequest = clsUtility.testDataServiceRequest(1, false, lstAsset);
        
        Powerparts_Service_Request_Team__c objPSR = new Powerparts_Service_Request_Team__c();
        objPSR.Service_Request__c = lstServiceRequest[0].Id;
        objPSR.Engineer1__c = objUser4.Id;
        objPSR.Engineer2__c = objUser.Id;
        objPSR.Engineer3__c = objUser1.Id;
        objPSR.Engineer4__c = objUser2.Id;
        insert objPSR;
        
        objPSR.Engineer4__c = objUser5.Id;
        update objPSR;
        
        
        //clsUtility.testDataAddServiceTeam(lstServiceRequest, true);
        clsUtility.testDataContentDoc(lstServiceRequest, 5); 
        List<Powerparts_Service_Request_Team__c> lstSRT = [Select id, Service_Request__c ,Engineer1__c, Engineer2__c ,Engineer3__c,Engineer4__c 
                                                           from Powerparts_Service_Request_Team__c
                                                           where Service_Request__c =:lstServiceRequest[0].id ];
        lstSRT[0].Engineer4__c = null;
        update lstSRT;
    }
}