force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Request__c/Part_Request__c.object-meta.xml
<CustomObject>
    <label>Part Request</label>
    <nameField>
        <displayFormat>PR-{00}</displayFormat>
        <label>Part Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Request__c/fields/Approval_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Approval_Date_Time__c</fullName>
    <label>Approval Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Free_of_charge__c.field-meta.xml
<CustomField>
    <fullName>Free_of_charge__c</fullName>
    <label>Free of Charge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Material_costs__c.field-meta.xml
<CustomField>
    <fullName>Material_costs__c</fullName>
    <formula>Part_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Old_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Old_Part_Number__c</fullName>
    <label>Old Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Parts Request</relationshipLabel>
    <relationshipName>Parts_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Part_Cost__c.field-meta.xml
<CustomField>
    <fullName>Part_Cost__c</fullName>
    <label>Part Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Part_Request_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Part_Request_Date_Time__c</fullName>
    <label>Part Request Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <label>Part Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Affected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Parts Request</relationshipLabel>
    <relationshipName>Parts_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/SOA__c.field-meta.xml
<CustomField>
    <fullName>SOA__c</fullName>
    <label>SOA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Out of Warranty</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Part_Cost__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/VOR__c.field-meta.xml
<CustomField>
    <fullName>VOR__c</fullName>
    <label>VOR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Warranty_Claim__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warranty Claim</label>
    <referenceTo>Warranty_Claim__c</referenceTo>
    <relationshipLabel>Parts Request</relationshipLabel>
    <relationshipName>Parts_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Request__c/fields/Warranty_Type__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Type__c</fullName>
    <label>Warranty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Warranty</fullName>
            </value>
            <value>
                <fullName>out of Warranty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty_Claim__c/Warranty_Claim__c.object-meta.xml
<CustomObject>
    <label>Warranty Claim</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Warranty Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warranty Claim</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warranty_Claim__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Request__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.End_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Warranty Claim</relationshipLabel>
    <relationshipName>Warranty_Claim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WarrantyClaimTriggerHelper.cls
/*
--------------------------------------------------------------------------------------
Version#     Date                           Author                    Description
--------------------------------------------------------------------------------------
1.0          9-Dec-2019                   Deepak Pandey            Initial Version
--------------------------------------------------------------------------------------
*/
public class WarrantyClaimTriggerHelper
{
    public static void warrantyClaimTriggerExecute(list<Warranty_Claim__c> triggerNew,Map<Id,Warranty_Claim__c> triggerNewMap,list<Warranty_Claim__c> triggerOld,Map<Id,Warranty_Claim__c> triggeroldMap,boolean isAfter,boolean isBefore,boolean isInsert,boolean isUpdate,boolean isDelete)
    {
        //Call Methods
        if(isinsert && isafter)
        {
            inserPartRequestOfEnadCustomer(triggerNew);
        }
    }
    static void inserPartRequestOfEnadCustomer(list<Warranty_Claim__c> triggerNew)
    {
        set<Id> setOfSR = new set<Id>();
        map<Id,Id> mapIdWCRelatedSR = new map<Id,Id>();
        for(Warranty_Claim__c objWC : triggerNew)
        {
            if(objWC.Service_Request__c != null)
            {
                mapIdWCRelatedSR.put(objWC.Service_Request__c, objWC.Id);
            }
        }
        if(mapIdWCRelatedSR.size()>0)
        {
            list<Part_Request__c> lstPR = new list<Part_Request__c>();
            map<Id, list<Part_Request__c>> mapServiceReqRelatedPR = new map<Id, list<Part_Request__c>>();
            for(Part_Request__c objPR : [Select Id, Name, Approval_Date_Time__c, Description__c, Free_of_charge__c, Material_costs__c, Part__c, Old_Part_Number__c, Part_Cost__c, Part_Request_Date_Time__c, Part_Request_Number__c , Part_Type__c, Quantity__c, Remark__c, Service_Request__c, SOA__c, Total_Cost__c, VOR__c, Warranty_Type__c,Warranty_Claim__c from Part_Request__c where Service_Request__c IN: mapIdWCRelatedSR.keyset()])
            {
                if(mapIdWCRelatedSR.containskey(objPR.Service_Request__c) && mapIdWCRelatedSR.get(objPR.Service_Request__c) != null)
                {
                    //Part_Request__c objPRNew = new Part_Request__c(); 
                    //objPRNew = objPR.clone();
                    objPR.Warranty_Claim__c = mapIdWCRelatedSR.get(objPR.Service_Request__c);
                    objPR.Service_Request__c = null;
                    lstPR.add(objPR);
                }
            }
            if(lstPR.size()>0)
                update lstPR;
        }
    }
}