force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/List_Price_Standard_price__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Standard_price__c</fullName>
    <label>List Price /Standard price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOI__c.field-meta.xml
<CustomField>
    <fullName>UOI__c</fullName>
    <label>UOI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <label>Usage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELC</fullName>
            </value>
            <value>
                <fullName>DEO</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Engine Parts</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/Purchase_Indent__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Purchase Indent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Indents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent__c/fields/Purchase_Indent_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Indent_Number__c</fullName>
    <formula>if(
	text( Ware_House__r.City__c ) == &apos;Kolkata&apos;, 
	&apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PIN&apos;+RIGHT( Name , LEN(Name) - 4),
	if( text(Ware_House__r.City__c) == &apos;Gurugram&apos;, 
		&apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), 
		 LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PIN&apos;+RIGHT( Name , LEN(Name) - 4),
		&apos;Please select Branch Office .&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Indent Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Reference_No__c</fullName>
    <label>Reference No old</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Indents</relationshipLabel>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Sales_Order_Acknowledge_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Acknowledge_Number__c</fullName>
    <formula>if( text(Ware_House__r.City__c) == &apos;Kolkata&apos;, &apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;SOD&apos;+RIGHT( Name , LEN(Name) - 4),if( text(Ware_House__r.City__c) == &apos;Gurugram&apos;, &apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;SOD&apos;+RIGHT( Name , LEN(Name) - 4),&apos;Please select office branch for the Opportunity.&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order Acknowledge Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Shipping_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State_Code__c</fullName>
    <label>Shipping State Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/SOA_No__c.field-meta.xml
<CustomField>
    <fullName>SOA_No__c</fullName>
    <label>SOA No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <formula>Product_In__c  -  Product_Out__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Warehouse_City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Warehouse City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomLookupForPI.cls
public without sharing class  CustomLookupForPI {
    
    @AuraEnabled
    public static List <sObject> searchLookupValue(string queryText, String objectName, string wareHouse, String strWrap,String eveobject) {
        System.debug('--wareHouse-- '+wareHouse);
        System.debug('--strWrap-- '+strWrap);
        System.debug('--queryText-- '+queryText);
        System.debug('--eveobject-- '+eveobject);
        System.debug('--objectName-- '+objectName);
        Set<string> existpartid = new set<string>();
        if(string.isNotBlank(strWrap) && objectName == 'Part__c'){
            if(eveobject == 'MRN'){
                MRNcontroller.wrapper objmainWrap = (MRNcontroller.wrapper)Json.deserialize(strWrap, MRNcontroller.wrapper.class);
                for(MRNcontroller.DeliveryNoteLIWrapper dnl : objmainWrap.lstDeliveryNoteLIWrap){
                    existpartid.add(dnl.objPart.id);
                    System.debug('---- '+dnl.objPart.id);
                } 
            }
            if(eveobject == 'PO' && strWrap!='["null"]'){
               system.debug('....strWrap..'+strWrap); 
                PurchaseOrderCMP.mainWrapper objmainWrap = (PurchaseOrderCMP.mainWrapper)Json.deserialize(strWrap, PurchaseOrderCMP.mainWrapper.class);
                for(PurchaseOrderCMP.OrderItemWapper oiw : objmainWrap.lstOIW){
                    existpartid.add(oiw.objPart.id);
                    System.debug('---- '+oiw.objPart);
                } 
            }
        }
         
        system.debug('queryText --- ' + queryText +'Object Name --- '+objectName +'wareHouse ---'+wareHouse);        
        String searchKey = queryText + '%';
        String sQuery = '';
		String strFields = '';
        
        if(String.isNotBlank(objectName)){
            if(objectName == 'Part__c')
                strFields = 'Id, Name,Part_Name__c,Usage__c,HSN_CODE__c,List_Price_Standard_price__c,UOM__c,UOI__c';
                //strFields = 'Id, Name,Part_Name__c,Usage__c,HSN_CODE__c,List_Price_Standard_price__c,UOM__c,UOI__c,(select id, Total_Quantity__c, Ware_House__c from Stocks__r where Ware_House__c =: wareHouse)';
            else if(objectName == 'User')
                strFields = 'Id, Name';
            else if(objectName == 'Sales_Order__c')
				strFields = 'Id, Name, Bill_To__c, SOA_No__c, Sales_Order_Acknowledge_Number__c';
            else if(objectName == 'Purchase_Indent__c')
				strFields = 'Id, Name, Purchase_Indent_Number__c, Reference_No__c';
            else if(objectName == 'Ware_House__c')
                strFields = 'Id, Name, State_Code__c ';
            else 
                strFields = 'Id, Name';
        }
        if(queryText == null || queryText == ''){
            if(String.isNotBlank(wareHouse) && (objectName == 'Sales_Order__c' || objectName == 'Purchase_Indent__c'))
                sQuery = 'select '+strFields+' from ' +objectName + ' where Ware_House__c =: wareHouse order by LastViewedDate DESC limit 5';
            else if(objectName == 'Account')
                sQuery = 'select '+strFields+' ,RecordType.Name, Billing_State_Code__c, Shipping_State_Code__c from ' +objectName + ' where RecordType.Name = \'Supplier\' order by LastViewedDate DESC limit 5';
            else  if(objectName == 'Part__c')  
                sQuery = 'select '+strFields+' from ' +objectName + ' WHERE Id NOT IN : existpartid order by LastViewedDate DESC limit 5';
            else    
                sQuery = 'select '+strFields+' from ' +objectName + ' order by LastViewedDate DESC limit 5';
        }
        else {
            if(String.isNotBlank(wareHouse) && objectName == 'Sales_Order__c')
                sQuery = 'select '+strFields+' from ' +objectName + ' where Ware_House__c =: wareHouse AND Sales_Order_Acknowledge_Number__c LIKE: searchKey order by LastViewedDate DESC limit 5';
            else if(String.isNotBlank(wareHouse) && objectName == 'Purchase_Indent__c')
                sQuery = 'select '+strFields+' from ' +objectName + ' where Ware_House__c =: wareHouse AND Purchase_Indent_Number__c LIKE: searchKey order by LastViewedDate DESC limit 5';
            else if(objectName == 'Account')
                sQuery = 'select '+strFields+' ,RecordType.Name, Billing_State_Code__c, Shipping_State_Code__c from ' +objectName + ' where RecordType.Name = \'Supplier\' AND Name LIKE: searchKey order by LastViewedDate DESC limit 5';
            else  if(objectName == 'Part__c')  
                sQuery = 'select '+strFields+' from ' +objectName + ' WHERE Id NOT IN : existpartid AND Name LIKE: searchKey order by LastViewedDate DESC limit 5';
            else   
                sQuery = 'select '+strFields+' from ' +objectName + ' where Name LIKE: searchKey order by LastViewedDate DESC limit 5';
        }       
            
        System.debug(sQuery);
        List <sObject> lstOfRecords = Database.query(sQuery);
        
        /*if(sQuery != null && sQuery != ''){
            List < Part__c > lstOfRecords = Database.query(sQuery);
            if(lstOfRecords.size() > 0){
                for (Part__c obj: lstOfRecords) {
                    returnList.add(obj);
                }
            }
        }*/
        
        return lstOfRecords;
    }
}