force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pdf_Header__mdt/Pdf_Header__mdt.object-meta.xml
<CustomObject>
    <label>Pdf Header</label>
    <pluralLabel>Pdf Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pdf_Header__mdt/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kolkata</fullName>
                <default>true</default>
                <label>Kolkata</label>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/Purchase_Indent__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Purchase Indent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Indents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Indent_By__c.field-meta.xml
<CustomField>
    <fullName>Indent_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indent By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Indent_Date__c.field-meta.xml
<CustomField>
    <fullName>Indent_Date__c</fullName>
    <label>Indent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Procurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Import</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Purchase_Indent_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Indent_Number__c</fullName>
    <formula>if(
	text( Ware_House__r.City__c ) == &apos;Kolkata&apos;, 
	&apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PIN&apos;+RIGHT( Name , LEN(Name) - 4),
	if( text(Ware_House__r.City__c) == &apos;Gurugram&apos;, 
		&apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), 
		 LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;PIN&apos;+RIGHT( Name , LEN(Name) - 4),
		&apos;Please select Branch Office .&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Indent Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Reference_No__c</fullName>
    <label>Reference No old</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Purchase Indents</relationshipLabel>
    <relationshipName>Purchase_Indents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/Purchase_Indent_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Indent Line Item</label>
    <nameField>
        <label>Purchase Indent Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Indent Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Purchase_Indent__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Indent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Indent</label>
    <referenceTo>Purchase_Indent__c</referenceTo>
    <relationshipLabel>Purchase Indent Line Items</relationshipLabel>
    <relationshipName>Purchase_Indent_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>QTY</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Indent_Line_Item__c/fields/Stock_Actual__c.field-meta.xml
<CustomField>
    <fullName>Stock_Actual__c</fullName>
    <label>Stock Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/GSTIN_No__c.field-meta.xml
<CustomField>
    <fullName>GSTIN_No__c</fullName>
    <label>GSTIN No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Warehouse_City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Warehouse City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PurchaseIndentCtrl.cls
public class PurchaseIndentCtrl
{
    public Purchase_Indent__c PurchaseInd{get;set;} 
    public contact con{get;set;}
    public Account Acc{get;set;}
    public list<Purchase_Indent_Line_Item__c> PILitem{get;set;}
    
     public Pdf_Header__mdt pdfheader{get;set;}
    
    
    public PurchaseIndentCtrl(ApexPages.StandardController controller)      
    {
        PILitem=new list<Purchase_Indent_Line_Item__c>();
        PurchaseInd=new Purchase_Indent__c();
        con=new contact();
        Acc=new Account();
        
        id queryString = ApexPages.currentPage().getParameters().get('id');
        pdfheader=new Pdf_Header__mdt();
        
        if(queryString !=null){
            PurchaseInd=[select Id,Name,CreatedDate,Procurement__c,Department__c,Ware_House__r.Branch__c,Ware_House__r.City__c,Indent_Date__c,Indent_By__c,Indent_By__r.Name,Reference_No__c,Reference_Date__c,Purchase_Indent_Number__c,Terms_and_Conditions__c from Purchase_Indent__c where id =:queryString limit 1];  
                 
           string branch = PurchaseInd.Ware_House__r.Branch__c ;
            List<String> pdfheaderField = UtilityClass.getAllFields('Pdf_Header__mdt');
            String pdfHeaderQuery = 'Select ' +String.Join(pdfheaderField, ',')+ ' From Pdf_Header__mdt WHERE Branch__c =:branch Order by Effected_Date__c ASC LIMIT 1';
            pdfheader =  Database.query(pdfHeaderQuery);
            
            /*system.debug(PurchaseOrd.Id+'opp.....'+PurchaseOrd.Contact_Person__c);
            if(PurchaseOrd.Contact_Person__c !=null)
                con = [select id,Name,Email,MobilePhone,Accountid from contact where id=:PurchaseOrd.Contact_Person__c limit 1];
            
            system.debug('contact'+con.id);
            if(con.Accountid !=null)
                Acc=[select id ,GSTIN_No__c,BillingCity,BillingCountry,BillingState,BillingStreet,BillingAddress,BillingPostalCode,ShippingCountry,ShippingCity,ShippingPostalCode,ShippingStreet,ShippingState,ShippingAddress, name,Billing_State_Code__c,Shipping_State_Code__c from Account where id =:con.Accountid];*/
            
         
            PILitem=[select Id,Name,Part_Name__c,Purchase_Indent__c,Product_Part__c,Product_Part__r.Name,Remark__c,QTY__c,Stock_Actual__c,Product_Part__r.UOM__c from Purchase_Indent_Line_Item__c where Purchase_Indent__c=:PurchaseInd.id];
            
         
            String myGeneratedFileName = PurchaseInd.Purchase_Indent_Number__c+'.pdf';
            Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename='+myGeneratedFilename);
        }
    }  
    
}