force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pdf_Header__mdt/Pdf_Header__mdt.object-meta.xml
<CustomObject>
    <label>Pdf Header</label>
    <pluralLabel>Pdf Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Return__c/Sales_Order_Return__c.object-meta.xml
<CustomObject>
    <label>Sales Order Return</label>
    <nameField>
        <displayFormat>SOR-{0000}</displayFormat>
        <label>Voucher No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Return__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Returns (Shipping Account)</relationshipLabel>
    <relationshipName>Sales_Order_Returns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Return_Line_Item__c/Sales_Order_Return_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Return Line Item</label>
    <nameField>
        <displayFormat>SORLI-{00000}</displayFormat>
        <label>Sales Order Return Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Return Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Return_Line_Item__c/fields/Doc_No__c.field-meta.xml
<CustomField>
    <fullName>Doc_No__c</fullName>
    <label>Doc No.</label>
    <referenceTo>Sales_Order_Return__c</referenceTo>
    <relationshipLabel>Sales Order Return Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Return_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Return_Line_Item__c/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <formula>Taxable_Amount__c + CGST_Amount__c + IGST_Amount__c + SGST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Return_Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Sales Order Return Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Return_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesorderReturnPdf.cls
public class SalesorderReturnPdf {
    public Sales_Order_Return__c lstSOR{get; set;}
     public list<Contact> conlst{get; set;}
    public Contact con{get; set;}
    public List<Sales_Order_Return_Line_Item__c> lstSORlineitem{get; set;}
    public Pdf_Header__mdt pdfheader{get;set;}
    public Decimal GrossTotal{get; set;}
    public Decimal TCSAmount{get; set;}
    public Decimal NetValue{get; set;}
    public Decimal Quantity{get; set;}
    public string totalAmountinWords{get; set;}
    
    
    public SalesorderReturnPdf(ApexPages.StandardController controller){
        String strId = ApexPages.currentPage().getParameters().get('id');
        pdfheader=new Pdf_Header__mdt();
        List<String> pdfheaderField = UtilityClass.getAllFields('Pdf_Header__mdt');
        String pdfHeaderQuery = 'Select ' +String.Join(pdfheaderField, ',')+ ' From Pdf_Header__mdt Order by Effected_Date__c ASC LIMIT 1';
        pdfheader =  Database.query(pdfHeaderQuery);
       
        lstSOR=[select id, Shipping_Account__c from Sales_Order_Return__c where id =:strId ];
        
        conlst=[select id,name,email, Mobilephone from contact where Accountid =:lstSOR.Shipping_Account__c limit 1 ]; 
        con=conlst[0];
        GrossTotal = 0;
        TCSAmount = 0;
        NetValue = 0;
        Quantity = 0;
        Decimal totalamount = 0;
        totalAmountinWords = '';
        
        List<String> SORlineitem = UtilityClass.getAllFields('Sales_Order_Return_Line_Item__c');
        String strSORlineitemquery = 'Select ' +String.Join(SORlineitem, ',')+',Part_Number__r.name,Part_Number__r.uom__c, Part_Number__r.Part_Name__c, Part_Number__r.HSN_CODE__c'+' From Sales_Order_Return_Line_Item__c where Doc_No__c =: strId';
        lstSORlineitem =  Database.query(strSORlineitemquery);  
        if(!lstSORlineitem.isempty())
            for(Sales_Order_Return_Line_Item__c dli :lstSORlineitem){
                GrossTotal = GrossTotal + dli.Net_Amount__c;
            }
        totalamount = GrossTotal;

        NetValue = totalamount;
        
        totalAmountinWords = UtilityClass.NoToWord(NetValue.intValue());
        totalAmountinWords = 'Ruppes '+totalAmountinWords+' only';
    }
    
}