force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Freeze</fullName>
                <isActive>false</isActive>
                <label>Freeze</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>LI-{00}</displayFormat>
        <label>Sales Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Sales Order Line Items (Stock)</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Product_Out__c.field-meta.xml
<CustomField>
    <fullName>Product_Out__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Warehouse_City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Warehouse City</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesOrderHelperTest.cls
@isTest
public class SalesOrderHelperTest {
    @istest static void testSalesOrder(){
        //insert WareHouse
        Ware_House__c wHouse = new Ware_House__c();
        wHouse.Name = 'Gurgaon Ware House';
        wHouse.City__c = 'Gurugram';
        insert wHouse; 
        
        //insert Product
        Part__c part = new Part__c();
        part.Name = 'Apart';
        insert part; 
        
        //insert Stock
        Stock__c stk = new Stock__c(); 
        stk.Product_Part__c = part.Id;
        stk.Ware_House__c = whouse.Id;
        stk.Quantity__c = 10;
        stk.Product_Out__c = 10;
        insert stk; 
        
        //insert SalesOrder
        Sales_Order__c sOrder = new Sales_Order__c(); 
        sOrder.Bill_To__c = 'Gurugram';
        insert sOrder;
        
        //insert LineItem
        Sales_Order_Line_Item__c sItem = new Sales_Order_Line_Item__c();
        sItem.Sales_Order__c = sOrder.Id;
        sItem.Product_Part__c = part.Id;
        sItem.Quantity__c = 10;
        insert sItem; 
        //update salesOrder
        sOrder.Status__c = 'Approved';
        update sOrder; 
    }	 
    
}