force-app/main/default/objects/Bank_Details__mdt/Bank_Details__mdt.object-meta.xml
<CustomObject>
    <description>Bank Details for Tax Invoice and Service Invoice</description>
    <label>Bank Detail</label>
    <pluralLabel>Bank Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bank_Details__mdt/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__mdt/fields/Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Address__c</fullName>
    <label>Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bank_Details__mdt/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Bank_Details__mdt/fields/IFC_RTGS_NEFT__c.field-meta.xml
<CustomField>
    <fullName>IFC_RTGS_NEFT__c</fullName>
    <label>IFC/RTGS/NEFT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Billing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_State_Code__c</fullName>
    <formula>Customer_Name__r.Billing_State_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.isPrimary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DC_No__c.field-meta.xml
<CustomField>
    <fullName>DC_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DC  No.</label>
    <referenceTo>Sales_Order_Dispatch_Delivery_Note__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/IGST_Amount__c.field-meta.xml
<CustomField>
    <fullName>IGST_Amount__c</fullName>
    <formula>Taxable_Amount__c  *  IGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <formula>Taxable_Amount__c + CGST_Amount__c + SGST_Amount__c + IGST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <label>SGST%</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Taxable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Amount__c</fullName>
    <formula>Amount__c  -  Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/Sales_Order_Dispatch_Delivery_Note__c.object-meta.xml
<CustomObject>
    <label>Delivery Note</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery note name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Dispatch_Delivery_Note__c/fields/Delivery_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Note_Number__c</fullName>
    <formula>if( text( Sales_Order__r.Ware_House__r.City__c) == &apos;Kolkata&apos;, &apos;PPLCU&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;GDNT&apos;+RIGHT( Name , LEN(Name) - 4),if( text(Sales_Order__r.Ware_House__r.City__c) == &apos;Gurugram&apos;, &apos;PPLHO&apos;+RIGHT(text(YEAR( DATEVALUE(CreatedDate))), LEN(text(YEAR( DATEVALUE(CreatedDate)))) - 2)+&apos;GDNT&apos;+RIGHT( Name , LEN(Name) - 4),&apos;Please select Place on supply on SO.&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Note Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxCumServiceInvoicePDF.cls
public class TaxCumServiceInvoicePDF {
    
    public Invoice__c objInvoice {get;set;}
    //public Account objSupplier {get;set;}
    //public Contact objSupplierContact {get;set;}
    public Bank_Details__mdt objBankDetail{get;set;}
    public List<Invoice_Line_Item__c> lstILI {get;set;}
    public decimal subTotalTaxableAmount{get;set;}
    public decimal subTotalAmount{get;set;}
    public decimal subTotalQuatity{get;set;}
    public Decimal SubTotalIGST{get;set;}
    public Decimal SubTotalCGST{get;set;}
    public Decimal SubTotalSGST{get;set;}
    public decimal TotalTaxableAmount{get;set;}
    public decimal TotalAmount{get;set;}
    public String TotalAmountInWords{get;set;}
    public Decimal TotalIGST{get;set;}
    public Decimal TotalCGST{get;set;}
    public Decimal TotalSGST{get;set;}
    public Decimal TotalGST{get;set;}
    public Decimal CGST{get;set;}
    public Decimal SGST{get;set;}
    public Decimal IGST{get;set;}
    public Decimal GSTOnReverseCharge{get;set;}
    public Decimal RoundOffValue{get;set;}
    
    public TaxCumServiceInvoicePDF(ApexPages.StandardController controller){
        String strId = ApexPages.currentPage().getParameters().get('id');
        
        if(String.isNotBlank(strId)){
            objInvoice = new Invoice__c();
            objBankDetail = new Bank_Details__mdt();
            lstILI = new List<Invoice_Line_Item__c>();
            subTotalTaxableAmount = 0;
            subTotalAmount = 0;
            SubTotalIGST = 0;
            SubTotalCGST = 0;
            SubTotalSGST = 0;
            TotalTaxableAmount = 0;
            subTotalQuatity =0 ;
            TotalAmount = 0;
            TotalAmountInWords ='';
            TotalIGST = 0;
            TotalCGST = 0;
            TotalSGST = 0;
            TotalGST = 0;
            CGST =0;
            SGST =0;
            IGST =0;
            GSTOnReverseCharge =0;
            RoundOffValue =0;
            
            List<String> lstInvoiceField = UtilityClass.getAllFields('Invoice__c');
            List<String> lstInvoiceLineItemField = UtilityClass.getAllFields('Invoice_Line_Item__c');
            
            String strInvoiceQuery = 'Select ' +String.Join(lstInvoiceField, ',')+ ',ESN_No__r.Name,Customer_Name__r.Name, Contact_Person__r.Name, Contact_Person__r.Email, DC_No__r.Delivery_Note_Number__c From Invoice__c where Id =: strId';
            String strInvoiceLineItemQuery = 'Select ' +String.Join(lstInvoiceLineItemField, ',')+ ',Part_Number__r.Name From Invoice_Line_Item__c where Invoice__c =: strId';            
            
            List<Invoice__c> lstInvoiceOrder =  Database.query(strInvoiceQuery);
            if(lstInvoiceOrder.size() > 0){
                objInvoice = lstInvoiceOrder[0];
                /*if(String.isNotEmpty(objInvoice.Supplier__c)){
                    objSupplier = [Select Id,Name, BillingCity,BillingCountry, BillingPostalCode,BillingState,BillingStreet,GSTIN_No__c ,Billing_State_Code__c,
                                   (Select Id, Email, MobilePhone, Name from contacts ) 
                                   from Account 
                                   where Id =: objInvoice.Supplier__c];
                    if(objSupplier.contacts.size() > 0){
                        objSupplierContact = objSupplier.contacts[0];
                    }
                }*/
                
                    
            }
             
            lstILI = Database.query(strInvoiceLineItemQuery);
            if(lstILI.size() > 0){
                for(Invoice_Line_Item__c objILI : lstILI){
                    if(objILI.Taxable_Amount__c > 0)
                        subTotalTaxableAmount += objILI.Taxable_Amount__c;
                    if(objILI.Net_Amount__c > 0)
                        subTotalAmount += objILI.Net_Amount__c;
                    if(objILI.IGST_Amount__c > 0)
                        SubTotalIGST += objILI.IGST_Amount__c;
                    if(objILI.CGST_Amount__c > 0)
                        SubTotalCGST += objILI.CGST_Amount__c;
                    if(objILI.SGST_Amount__c > 0)
                        SubTotalSGST += objILI.SGST_Amount__c;
                    if(objILI.Quantity__c > 0)
                        subTotalQuatity += objILI.Quantity__c;
                    if(objILI.CGST__c > 0 )
                        CGST = objILI.CGST__c;
                    if(objILI.SGST__c > 0 )
                        SGST = objILI.SGST__c;
                    if(objILI.IGST__c > 0 )
                        IGST = objILI.IGST__c;
                }
                
                TotalTaxableAmount = subTotalTaxableAmount;
                TotalAmount = subTotalAmount;
                TotalIGST = SubTotalIGST;
                TotalCGST = SubTotalCGST;
                TotalSGST = SubTotalSGST;
                TotalGST = TotalIGST+TotalCGST+TotalSGST;
                
                if(subTotalTaxableAmount > 0 )
                    GSTOnReverseCharge = (subTotalTaxableAmount *18 )/100;
                
                    if(TotalAmount > 0){
                    RoundOffValue =TotalAmount;
                    TotalAmount = TotalAmount.round();
                    RoundOffValue = RoundOffValue - TotalAmount;
                    TotalAmountInWords = UtilityClass.NoToWord(TotalAmount.intValue());
                }
            }
            
            //Get Bank Details
            List<Bank_Details__mdt> lstBankDetails = [select Id, Bank_Name__c, Bank_Account_Number__c, Bank_Address__c, IFC_RTGS_NEFT__c 
                                                      from Bank_Details__mdt 
                                                      order By Created_Date__c Desc];
            if(lstBankDetails.size() > 0)
                objBankDetail = lstBankDetails[0];
            
        }
    }   
    
}