force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>18/100</defaultValue>
    <label>GST%</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/SGST__c.field-meta.xml
<CustomField>
    <fullName>SGST__c</fullName>
    <label>SGST %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/OEM_Customer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/List_Price_Standard_price__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Standard_price__c</fullName>
    <label>List Price /Standard price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>PPL-{000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Customer_Party__c.field-meta.xml
<CustomField>
    <fullName>Customer_Party__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/addPPProductControl.cls
public class addPPProductControl {
    public static WrappMain recordlist {get;set;}
    
    @AuraEnabled 
    public static string productOnLoad(string RecordId)
    {
        System.debug('QuoteRecordId---- '+RecordId);
        string objname =findObjectNameFromRecordIdPrefix(RecordId);
        System.debug('object is '+ objname);
        Boolean IGST=false;
        set<string> stateset = new set<string>();
        list<Ware_House__c> whlist=[SELECT State_Code__c,State_Province__c FROM Ware_House__c];
        for(Ware_House__c wh:whlist) stateset.add(wh.State_Province__c);
        String state='';
        if(objname  =='Quote__c')
            state=[SELECT Id,Customer_Party__r.ShippingState From Quote__c WHERE id=:RecordId].Customer_Party__r.ShippingState;
        if(objname  =='Opportunity__c')
            state=[SELECT Id,OEM_Customer__r.ShippingState From Opportunity__c WHERE id=:RecordId].OEM_Customer__r.ShippingState;
        
        if(stateset.contains(state)) IGST =true;
        
        recordlist = new WrappMain();
        recordlist.lstWrapp = new list<prodwrapp>(); 
        List<prodwrappChild> lstWrappTwoNew = new List<prodwrappChild>();
        recordlist.lstWrappTwo = lstWrappTwoNew;
        recordlist.lineitemid = new set<id>();
        recordlist.quoteId = new set<Id>();
        recordlist.isSelectedProduct = false;
        recordlist.quoteId.add(RecordId);
        recordlist.objectname = objname;
        recordlist.success = true;
        recordlist.igstvalue =IGST;
        System.debug('------- '+IGST);
        system.debug('....recordlist...'+recordlist);
        return json.serialize(recordlist);
    }
    
    @AuraEnabled
    public static string onselectPick(string strWrap)
    {
        System.debug('Select pick method called');
        WrappMain objwrap = (WrappMain)Json.deserialize(strWrap, WrappMain.class);
        try
        { 
            for(Part__c objP : [select id, name, List_Price_Standard_price__c, Product_Family__c  from Part__c limit 10]) 
            {
                prodwrapp objwrapp = new prodwrapp(); 
                objwrapp.objProd = objP;
                objwrapp.isSelected = false;
                objwrap.lstWrapp.add(objwrapp);
            }   
            objwrap.isSelectedProduct = true;
            objwrap.success = true;
        }
        catch(exception e)
        {
            objwrap.success = false;
            objwrap.strMessage=e.getMessage();
        }
        system.debug('..........'+json.serialize(objwrap));
        return json.serialize(objwrap);  
    }   
    
    @AuraEnabled
    public static string addRecord(string strWrap)
    {
        System.debug('add Record method called');
        WrappMain objwrap = (WrappMain)Json.deserialize(strWrap, WrappMain.class);
        try
        {
            List<prodwrapp> lstWrappNew = objwrap.lstWrapp;
            List<prodwrappChild> lstWrappTwoNew = new List<prodwrappChild>();
            Set<id> lineitemids = new set<id>();
            System.debug('lstWrappNewSz---- '+lstWrappNew.size());
            for( integer i = 0 ; i<lstWrappNew.size();  i++)
            {
                if(lstWrappNew[i].isSelected)
                {
                    prodwrappChild objchild = new prodwrappChild();
                    objchild.isSelected = true;
                    Line_Item__c objOppPro = new Line_Item__c();
                    objOppPro.ProductName__c = lstWrappNew[i].objProd.name; 
                    objOppPro.List_Price__c = lstWrappNew[i].objProd.List_Price_Standard_price__c;
                    objOppPro.Sales_Price__c = lstWrappNew[i].objProd.List_Price_Standard_price__c;
                    objOppPro.Quantity__c = 1;
                    objOppPro.HSN_Code__c = lstWrappNew[i].objProd.HSN_CODE__c;
                    objOppPro.Product_Part__c = lstWrappNew[i].objProd.id;
                    if(objwrap.igstvalue){
                        objOppPro.IGST__c=lstWrappNew[i].objProd.GST__c;
                        objOppPro.CGST__c=0;
                        objOppPro.SGST__c=0;
                    }
                    else{
                        objOppPro.IGST__c=0;
                        objOppPro.CGST__c=lstWrappNew[i].objProd.GST__c;
                        objOppPro.SGST__c=lstWrappNew[i].objProd.GST__c;
                    }
                    objchild.objProdchild = objOppPro;
                    if(objwrap.lineitemid == null)
                    {
                        lstWrappTwoNew.add(objchild);
                        lineitemids.add(objOppPro.Product_Part__c);  
                        objwrap.lineitemid = lineitemids;
                    }
                    else
                    {
                        if(objwrap.lineitemid.contains(objOppPro.Product_Part__c) == False)
                        {
                            lstWrappTwoNew.add(objchild); 
                            lineitemids.add(objOppPro.Product_Part__c);  
                            objwrap.lineitemid.addall(lineitemids);
                        }                   
                    }  
                }
            }
            objwrap.success = true;
            if(objwrap.lstWrappTwo == null)
            {
                objwrap.lstWrappTwo = lstWrappTwoNew;
            }
            else
            {
                objwrap.lstWrappTwo.addall(lstWrappTwoNew);
            }    
        }
        catch(exception e)
        {
            objwrap.success = false;
            objwrap.strMessage = e.getMessage();
        }
        system.debug('..........'+json.serialize(objwrap));
        return json.serialize(objwrap); 
    }   
    
    @AuraEnabled
    public static string saveRecord(string strWrap, string RecordId)
    {
        string objname =findObjectNameFromRecordIdPrefix(RecordId);
        WrappMain objwrap = (WrappMain)Json.deserialize(strWrap, WrappMain.class);
        try
        {
            List<prodwrappChild> OppLineChild = objwrap.lstWrappTwo;
            List<Line_Item__c> insertOppProduct = new List<Line_Item__c>();
            for(prodwrappChild obj : OppLineChild)
            {
                Line_Item__c objOppProduct = obj.objProdchild;
                if(objOppProduct.Quantity__c > 0 && objOppProduct.Sales_Price__c >0)
                {
                    if(objname  =='Quote__c')
                        objOppProduct.Quote__c = RecordId;
                    if(objname  =='Opportunity__c')
                        objOppProduct.Opportunity__c = RecordId;
                    insertOppProduct.add(objOppProduct);
                }
            }
            if(!insertOppProduct.isEmpty())
            {
                objwrap.success = true;
                database.insert(insertOppProduct,false);
                objwrap.strMessage = system.label.Add_Product_Success_Msg;
            }
        }
        catch(exception e)
        {
            objwrap.success = false;
            objwrap.strMessage = e.getMessage();
        }
        return json.serialize(objwrap);
    }    
    
    public class WrappMain
    {    
        @AuraEnabled public list<prodwrapp> lstWrapp {get;set;}
        @AuraEnabled public list<prodwrappChild> lstWrappTwo {get;set;}
        @AuraEnabled public set<Id> lineitemid {get;set;}
        @AuraEnabled public set<Id> quoteId {get;set;}
        @AuraEnabled public boolean igstvalue {get;set;} 
        @AuraEnabled public string objectname {get;set;}
        @AuraEnabled public Boolean isSelectedProduct {get; set;}
        @AuraEnabled public boolean success;       
        @AuraEnabled public string strMessage;
    }
    public class prodwrapp
    {    
        @AuraEnabled public Part__c objProd{get;set;}
        @AuraEnabled public Boolean isSelected {get; set;}
    }
    public class prodwrappChild
    {
        @AuraEnabled public Line_Item__c objProdchild{get;set;}
        @AuraEnabled public integer  total{get;set;}
        @AuraEnabled public Boolean isSelected {get; set;}
    }
    
    //This Method get object name base of recordid
    public static String findObjectNameFromRecordIdPrefix(String recordIdOrPrefix){
        String objectName = '';
        try{
            //Get prefix from record ID
            //This assumes that you have passed at least 3 characters
            String myIdPrefix = String.valueOf(recordIdOrPrefix).substring(0,3);
            
            //Get schema information
            Map<String, Schema.SObjectType> gd =  Schema.getGlobalDescribe(); 
            
            //Loop through all the sObject types returned by Schema
            for(Schema.SObjectType stype : gd.values()){
                
                //if (!sObj.contains('__')) to exclude managed package objects
                
                Schema.DescribeSObjectResult r = stype.getDescribe();
                String prefix = r.getKeyPrefix();
                
                
                //Check if the prefix matches with requested prefix
                if(prefix!=null && prefix.equals(myIdPrefix)){
                    objectName = r.getName();
                    
                    break;
                }
            }
        }catch(Exception e){
            System.debug(e);
        }
        return objectName;
    }
}