force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>Amount_Formula__c</fullName>
    <formula>Quantity__c  * Sales_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>EP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/CGST_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>CGST_Amount_Formula__c</fullName>
    <formula>Taxable_Amount_Formula__c  *  CGST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/DiscountN__c.field-meta.xml
<CustomField>
    <fullName>DiscountN__c</fullName>
    <label>DiscountN</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Expected_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_date__c</fullName>
    <label>Expected date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>18/100</defaultValue>
    <label>GST%</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <formula>Quantity__c * Sales_Price__c * GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <formula>Product_Part__r.Part_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Saleable_Stock__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Stock__c</fullName>
    <label>Saleable Stock</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>ENQ-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Product/Part</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products/Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>EP</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/HSN_CODE__c.field-meta.xml
<CustomField>
    <fullName>HSN_CODE__c</fullName>
    <label>HSN CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Part_Name__c</fullName>
    <label>Part Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Saleable_Stock__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Stock__c</fullName>
    <label>Saleable Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>Dozen</fullName>
            </value>
            <value>
                <fullName>NOS</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAN 20L</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
            <value>
                <fullName>DRUM 208 LTR.</fullName>
            </value>
            <value>
                <fullName>DRUM 210L</fullName>
            </value>
            <value>
                <fullName>GRAM</fullName>
            </value>
            <value>
                <fullName>LITRE</fullName>
            </value>
            <value>
                <fullName>LOT</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>METER</fullName>
            </value>
            <value>
                <fullName>ML</fullName>
            </value>
            <value>
                <fullName>MONTH</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PAIL 20 LTR.</fullName>
            </value>
            <value>
                <fullName>PCS</fullName>
            </value>
            <value>
                <fullName>QTR.</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>VISIT</fullName>
            </value>
            <value>
                <fullName>YEAR</fullName>
            </value>
            <value>
                <fullName>Foot</fullName>
                <isActive>false</isActive>
                <label>Foot</label>
            </value>
            <value>
                <fullName>Gallon</fullName>
                <isActive>false</isActive>
                <label>Gallon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pdf_Header__mdt/Pdf_Header__mdt.object-meta.xml
<CustomObject>
    <label>Pdf Header</label>
    <pluralLabel>Pdf Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pdf_Header__mdt/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kolkata</fullName>
                <default>true</default>
                <label>Kolkata</label>
            </value>
            <value>
                <fullName>Gurugram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>PPL-{000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/recordTypes/AMC.recordType-meta.xml
<RecordType>
    <fullName>AMC</fullName>
    <active>true</active>
    <label>AMC</label>
</RecordType>

force-app/main/default/objects/Quote__c/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <formula>TEXT( Opportunity__r.Application__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <label>CGST (%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <label>IGST (%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales From</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ware_House__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Gurugram</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClsAMCQuote.cls
public class ClsAMCQuote {
    public list<Line_item__c> lineitem{get;set;}
    public Quote__c quot{get;set;}
    public string sign{get;set;}
     public decimal roundAmt{get;set;}
    public decimal totalGatAmount{get;set;}
    
       public Pdf_Header__mdt pdfheader{get;set;}
     //public decimal roundvalue{get;set;}
     //public decimal roundvalues{get;set;}
    
    public ClsAMCQuote(ApexPages.StandardController controller) {
        id queryString = ApexPages.currentPage().getParameters().get('id');
        lineitem= new list<Line_item__c>();
        quot= new Quote__c();
         
          pdfheader=new Pdf_Header__mdt();
        
       
        
        quot=[select id,name ,ownerid,Opportunity__r.Ware_House__r.Branch__c from Quote__c where id=:queryString];
        
          string branch = quot.Opportunity__r.Ware_House__r.Branch__c ;
            List<String> pdfheaderField = UtilityClass.getAllFields('Pdf_Header__mdt');
            String pdfHeaderQuery = 'Select ' +String.Join(pdfheaderField, ',')+ ' From Pdf_Header__mdt WHERE Branch__c =:branch Order by Effected_Date__c ASC LIMIT 1';
            pdfheader =  Database.query(pdfHeaderQuery);
        
          String pageName = ApexPages.currentPage().getUrl();
            system.debug(' pageName '+pageName);
            
              if(pageName.contains('AMC')  )
            {              
                ApexPages.currentPage().getHeaders().put('content-disposition', 'filename=' +'  AMC Quote - '+quot.Name+'.PDF');
                system.debug('strfileName '+' AMC Quote-'+quot.Name);       
                
            }
        else{
            
                ApexPages.currentPage().getHeaders().put('content-disposition', 'filename=' +'  Service Quote - '+quot.Name+'.PDF');
                system.debug('strfileName '+' Service Quote-'+quot.Name);   
        }
        
         user ur =[SELECT Id,Branch__c,User_Signature__c from user where id =:quot.OwnerId];
        if(!String.isBlank(ur.User_Signature__c))
        sign = ur.User_Signature__c;
        
        if(String.isBlank(ur.User_Signature__c))
        sign =System.Label.Default_User_Sign;
        
        system.debug(sign);
        
        lineitem=[select Application__c,Amount_Formula__c,CGST__c,Delivery_Date__c,Description__c,GST__c,GST_Amount__c,
               Discount__c,DiscountN__c,Expected_date__c,HSN_Code__c,IGST__c,Name,List_Price__c,Opportunity__c,
               Product_Part__c,Product_Part__r.uom__c,Product_Part__r.HSN_Code__c,Part_Name__c,Quantity__c,Quote__c,Remark__c,
               Saleable_Stock__c,Sales_Order__c,CGST_Amount_Formula__c,IGST_Amount_Formula__c,SGST_Amount_Formula__c,
               Taxable_Amount_Formula__c,Sales_Price__c,Total_Amount_Formula__c,SGST__c,Part_Serial_No__c,Total_Amount_GST__c,Discount_Amount__c,
               Product_Part__r.Name,Product_Part__r.Part_Name__c,Net_Amount__c from Line_Item__c where Quote__c=:queryString];
        
    }

}