force-app/main/default/objects/Sales_Order_Line_Item__c/Sales_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line Item</label>
    <nameField>
        <displayFormat>LI-{00}</displayFormat>
        <label>Sales Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Deliverd_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Deliverd_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Deliverd Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Freeze_Qunatity__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Qunatity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Freeze Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Freeze_Stock__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Freeze Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Freeze Sales Order Part</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Sales Order Line Items</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Sales Order Line Items (Stock)</relationshipLabel>
    <relationshipName>Sales_Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line_Item__c/fields/warehouse__c.field-meta.xml
<CustomField>
    <fullName>warehouse__c</fullName>
    <formula>CASESAFEID(Sales_Order__r.Ware_House__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>warehouse</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stk-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Freeze_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Freeze Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Part__c.field-meta.xml
<CustomField>
    <fullName>Product_Part__c</fullName>
    <label>Product/Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Total_Unbooked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Unbooked_Quantity__c</fullName>
    <formula>Total_Quantity__c -  Freeze_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Unbooked Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Ware_House__c.field-meta.xml
<CustomField>
    <fullName>Ware_House__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ware House</label>
    <referenceTo>Ware_House__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ware_House__c/Ware_House__c.object-meta.xml
<CustomObject>
    <label>Ware House</label>
    <nameField>
        <label>Ware House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ware Houses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SalesOrderLineItemTriggerHelper.cls
public class SalesOrderLineItemTriggerHelper {
    
    public static void onInsertMethod(list<Sales_Order_Line_Item__c> newSolList){
        Set<string> productIdSet = new set<string>();
        for(Sales_Order_Line_Item__c sol: newSolList)
            productIdSet.add(sol.Product_Part__c);
        List<String> stockfields = UtilityClass.getAllFields('stock__c');
        String stockstring = 'Select ' +String.Join(stockfields, ',')+ ' From stock__c Where Product_Part__c in:productIdSet';
        list<stock__c> stocklist =  Database.query(stockstring);
        map<string,stock__c> stockmap = new map<string,stock__c> ();
        if(!stocklist.isempty()){
            for(stock__c stockrecord: stocklist){
                stockmap.put(stockrecord.Product_Part__c+'-'+stockrecord.Ware_House__c, stockrecord);
            }   
        }
        list<stock__c> updateStock = new list<stock__c>();
        for(Sales_Order_Line_Item__c solitem: newSolList){
            Stock__c currentStock = new stock__c();
            if(stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c) !=null){
                currentStock= stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c);
            }
            solitem.Stock__c = currentStock.id;
            if(solitem.Freeze_Qunatity__c<= currentStock.Total_Unbooked_Quantity__c && solitem.Freeze_Qunatity__c!=0 && solitem.Freeze_Qunatity__c <= solitem.Quantity__c){
                solitem.Freeze_Stock__c = currentStock.id;
                currentStock.Freeze_Quantity__c = currentStock.Freeze_Quantity__c +solitem.Freeze_Qunatity__c;
                updateStock.add(currentStock);
            }   
        } 
        if(!updateStock.isEmpty())
            update updateStock;
    }
    
    public static void onDeleteMethod(list<Sales_Order_Line_Item__c> newSolList){
        Set<string> productIdSet = new set<string>();
        for(Sales_Order_Line_Item__c sol: newSolList)
            productIdSet.add(sol.Product_Part__c);
        List<String> stockfields = UtilityClass.getAllFields('stock__c');
        String stockstring = 'Select ' +String.Join(stockfields, ',')+ ' From stock__c Where Product_Part__c in:productIdSet';
        list<stock__c> stocklist =  Database.query(stockstring);
        map<string,stock__c> stockmap = new map<string,stock__c> ();
        if(!stocklist.isempty()){
            for(stock__c stockrecord: stocklist){
                stockmap.put(stockrecord.Product_Part__c+'-'+stockrecord.Ware_House__c, stockrecord);
            }   
        }
        list<stock__c> updateStock = new list<stock__c>();
        for(Sales_Order_Line_Item__c solitem: newSolList){
            Stock__c currentStock = new stock__c();
            if(stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c) !=null){
                currentStock= stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c);
            }
            if(solitem.Freeze_Qunatity__c<= currentStock.Total_Unbooked_Quantity__c && solitem.Freeze_Qunatity__c!=0 && solitem.Freeze_Qunatity__c <= solitem.Quantity__c){
                currentStock.Freeze_Quantity__c = currentStock.Freeze_Quantity__c - solitem.Freeze_Qunatity__c;
                updateStock.add(currentStock);
            }   
        } 
        if(!updateStock.isEmpty())
            update updateStock;
    }
    
    public static void onupdateMethod(list<Sales_Order_Line_Item__c> newSolList, map<id,Sales_Order_Line_Item__c> NewSolMap,  map<id,Sales_Order_Line_Item__c> OldSolMap){
        Set<string> productIdSet = new set<string>();
        List<user> Userlist = [Select Id,isUnfreezeUser__c from user Where id =:UserInfo.getUserId()];
        user Currentuser = new User();
        if(!Userlist.isEmpty())
           Currentuser = Userlist[0];
        for(Sales_Order_Line_Item__c sol: newSolList)
            productIdSet.add(sol.Product_Part__c);
        List<String> stockfields = UtilityClass.getAllFields('stock__c');
        String stockstring = 'Select ' +String.Join(stockfields, ',')+ ' From stock__c Where Product_Part__c in:productIdSet';
        list<stock__c> stocklist =  Database.query(stockstring);
        map<string,stock__c> stockmap = new map<string,stock__c> ();
        if(!stocklist.isempty()){
            
            for(stock__c stockrecord: stocklist){
                stockmap.put(stockrecord.Product_Part__c+'-'+stockrecord.Ware_House__c, stockrecord);
            }   
        }
        list<stock__c> updateStock = new list<stock__c>();
        for(Sales_Order_Line_Item__c solitem: newSolList){
            Stock__c currentStock = new stock__c();
            if(stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c) !=null){
                currentStock= stockmap.get(solitem.Product_Part__c+'-'+solitem.warehouse__c);
            }
            solitem.Stock__c = currentStock.id;
            
            if(solitem.Freeze_Qunatity__c<= currentStock.Total_Unbooked_Quantity__c &&  solitem.Freeze_Qunatity__c <= solitem.Quantity__c && OldSolMap.get(solitem.id).Freeze_Qunatity__c != NewSolMap.get(solitem.id).Freeze_Qunatity__c){
                 if(OldSolMap.get(solitem.id).Freeze_Qunatity__c < NewSolMap.get(solitem.id).Freeze_Qunatity__c ){
                    //freeze Stock
                    solitem.Freeze_Stock__c = currentStock.id;
                    currentStock.Freeze_Quantity__c = currentStock.Freeze_Quantity__c +((NewSolMap.get(solitem.id).Freeze_Qunatity__c)-OldSolMap.get(solitem.id).Freeze_Qunatity__c);
                    updateStock.add(currentStock); 
                }
                else if(OldSolMap.get(solitem.id).Freeze_Qunatity__c > NewSolMap.get(solitem.id).Freeze_Qunatity__c && Currentuser.isUnfreezeUser__c ==true){
                    //Unfreeze Stock
                    solitem.Freeze_Stock__c = currentStock.id;
                    currentStock.Freeze_Quantity__c = currentStock.Freeze_Quantity__c -((OldSolMap.get(solitem.id).Freeze_Qunatity__c)-NewSolMap.get(solitem.id).Freeze_Qunatity__c);
                    updateStock.add(currentStock); 
                }
            }   
        } 
        if(!updateStock.isEmpty())
            update updateStock;
        
        for(Sales_Order_Line_Item__c solitem: newSolList){
            if(NewSolMap.get(solitem.id).Deliverd_Quantity__c !=OldSolMap.get(solitem.id).Deliverd_Quantity__c && NewSolMap.get(solitem.id).Quantity__c ==NewSolMap.get(solitem.id).Deliverd_Quantity__c)
                solitem.Freeze_Stock__c=null;
        }
    }

    
    
}